### ISSUE TITLE
Failed to save label in OHIF Viewer - Detection task on 2D images

### ISSUE THREAD

**Issue by manishdhakal** [Project-MONAI/MONAILabel#1111]
**Description**
I am not able to save the labels of the DICOM file because  of the missing tmp dicom file.

**Reproducing the bug**
1. Go to OHIF study list with "/ohif" url and select a dicom file.
2. Add segment labels from the with "MONAI Label" menu from the right of the screen. 
3. Click on the "Submit Label" button from the "Active Learning" section. 

**Screenshot**
![image](https://user-images.githubusercontent.com/36515191/199405732-2835f896-0976-41dd-a61f-178fe717a013.png)

**Terminal Output**
```
[2022-11-02 11:11:32,798] [488649] [MainThread] [INFO] (monailabel.endpoints.datastore:100) - Saving Label for 1.3.12.2.1107.5.4.3.123456789012345.19950922.121803.8 for tag: final by admin
[2022-11-02 11:11:32,835] [488649] [MainThread] [INFO] (monailabel.endpoints.datastore:111) - Save Label params: {"label_info":[{"id":"0+1","labelmapIndex":0,"segmentIndex":1,"color":[61,184,67,255],"meta":{"SegmentedPropertyCategoryCodeSequence":{"CodeValue":"T-D0050","CodingSchemeDesignator":"SRT","CodeMeaning":"Tissue"},"SegmentNumber":1,"SegmentLabel":"kimberly","SegmentDescription":"","SegmentAlgorithmType":"SEMIAUTOMATIC","SegmentAlgorithmName":"MONAI","SegmentedPropertyTypeCodeSequence":{"CodeValue":"T-D0050","CodingSchemeDesignator":"SRT","CodeMeaning":"Tissue"}},"name":"kimberly","description":""},{"id":"0+2","labelmapIndex":0,"segmentIndex":2,"color":[26,79,7,255],"meta":{"SegmentedPropertyCategoryCodeSequence":{"CodeValue":"T-D0050","CodingSchemeDesignator":"SRT","CodeMeaning":"Tissue"},"SegmentNumber":2,"SegmentLabel":"christine","SegmentDescription":"","SegmentAlgorithmType":"SEMIAUTOMATIC","SegmentAlgorithmName":"MONAI","SegmentedPropertyTypeCodeSequence":{"CodeValue":"T-D0050","CodingSchemeDesignator":"SRT","CodeMeaning":"Tissue"}},"name":"christine","description":""}]}
[2022-11-02 11:11:32,835] [488649] [MainThread] [INFO] (monailabel.datastore.dicom:147) - Input - Image Id: 1.3.12.2.1107.5.4.3.123456789012345.19950922.121803.8
[2022-11-02 11:11:32,835] [488649] [MainThread] [INFO] (monailabel.datastore.dicom:148) - Input - Label File: /tmp/tmpel9wrmhe.bin
[2022-11-02 11:11:32,836] [488649] [MainThread] [INFO] (monailabel.datastore.dicom:149) - Input - Label Tag: final
[2022-11-02 11:11:32,836] [488649] [MainThread] [INFO] (monailabel.datastore.dicom:150) - Input - Label Info: {'label_info': [{'id': '0+1', 'labelmapIndex': 0, 'segmentIndex': 1, 'color': [61, 184, 67, 255], 'meta': {'SegmentedPropertyCategoryCodeSequence': {'CodeValue': 'T-D0050', 'CodingSchemeDesignator': 'SRT', 'CodeMeaning': 'Tissue'}, 'SegmentNumber': 1, 'SegmentLabel': 'kimberly', 'SegmentDescription': '', 'SegmentAlgorithmType': 'SEMIAUTOMATIC', 'SegmentAlgorithmName': 'MONAI', 'SegmentedPropertyTypeCodeSequence': {'CodeValue': 'T-D0050', 'CodingSchemeDesignator': 'SRT', 'CodeMeaning': 'Tissue'}}, 'name': 'kimberly', 'description': ''}, {'id': '0+2', 'labelmapIndex': 0, 'segmentIndex': 2, 'color': [26, 79, 7, 255], 'meta': {'SegmentedPropertyCategoryCodeSequence': {'CodeValue': 'T-D0050', 'CodingSchemeDesignator': 'SRT', 'CodeMeaning': 'Tissue'}, 'SegmentNumber': 2, 'SegmentLabel': 'christine', 'SegmentDescription': '', 'SegmentAlgorithmType': 'SEMIAUTOMATIC', 'SegmentAlgorithmName': 'MONAI', 'SegmentedPropertyTypeCodeSequence': {'CodeValue': 'T-D0050', 'CodingSchemeDesignator': 'SRT', 'CodeMeaning': 'Tissue'}}, 'name': 'christine', 'description': ''}]}
[2022-11-02 11:11:32,836] [488649] [MainThread] [INFO] (monailabel.datastore.dicom:69) - Image ID: 1.3.12.2.1107.5.4.3.123456789012345.19950922.121803.8
[2022-11-02 11:11:32,836] [488649] [MainThread] [INFO] (monailabel.datastore.dicom:71) - Image Dir (cache): /home/manish/.cache/monailabel/dicom/488fca1f7f3f98331f6f7756beca0d35/1.3.12.2.1107.5.4.3.123456789012345.19950922.121803.8
[2022-11-02 11:11:33,255] [488649] [MainThread] [INFO] (monailabel.datastore.utils.convert:69) - Image: (512, 512, 96)
[2022-11-02 11:11:33,256] [488649] [MainThread] [INFO] (monailabel.datastore.utils.convert:70) - Label: (25165824,)
[2022-11-02 11:11:33,256] [488649] [MainThread] [INFO] (monailabel.datastore.utils.convert:73) - Label (reshape): (512, 512, 96)
[2022-11-02 11:11:33,484] [488649] [MainThread] [INFO] (monailabel.datastore.utils.convert:82) - binary_to_image latency : 0.647972583770752 (sec)
[2022-11-02 11:11:33,484] [488649] [MainThread] [INFO] (monailabel.datastore.dicom:160) - Label File: /tmp/tmpsf5ix4k3.nii.gz
[2022-11-02 11:11:34,470] [488649] [MainThread] [INFO] (monailabel.datastore.utils.convert:101) - 0 => 1 => kimberly
[2022-11-02 11:11:34,470] [488649] [MainThread] [INFO] (monailabel.datastore.utils.convert:101) - 1 => 2 => christine
[2022-11-02 11:11:34,470] [488649] [MainThread] [INFO] (monailabel.datastore.utils.convert:140) - {
  "ContentCreatorName": "Reader1",
  "ClinicalTrialSeriesID": "Session1",
  "ClinicalTrialTimePointID": "1",
  "SeriesDescription": "Segmentation",
  "SeriesNumber": "300",
  "InstanceNumber": "1",
  "segmentAttributes": [
    [
      {
        "labelID": 1,
        "SegmentLabel": "kimberly",
        "SegmentDescription": "",
        "SegmentAlgorithmType": "AUTOMATIC",
        "SegmentAlgorithmName": "MONAILABEL",
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeValue": "123037004",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Anatomical Structure"
        },
        "SegmentedPropertyTypeCodeSequence": {
          "CodeValue": "78961009",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "kimberly"
        },
        "recommendedDisplayRGBValue": [
          61,
          184,
          67
        ]
      },
      {
        "labelID": 2,
        "SegmentLabel": "christine",
        "SegmentDescription": "",
        "SegmentAlgorithmType": "AUTOMATIC",
        "SegmentAlgorithmName": "MONAILABEL",
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeValue": "123037004",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Anatomical Structure"
        },
        "SegmentedPropertyTypeCodeSequence": {
          "CodeValue": "78961009",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "christine"
        },
        "recommendedDisplayRGBValue": [
          26,
          79,
          7
        ]
      }
    ]
  ],
  "ContentLabel": "SEGMENTATION",
  "ContentDescription": "MONAI Label - Image segmentation",
  "ClinicalTrialCoordinatingCenterName": "MONAI",
  "BodyPartExamined": ""
}
[2022-11-02 11:11:34,470] [488649] [MainThread] [INFO] (monailabel.utils.others.generic:61) - Running Command:: itkimage2segimage --inputImageList /tmp/tmpsf5ix4k3.nii.gz --inputDICOMDirectory /home/manish/.cache/monailabel/dicom/488fca1f7f3f98331f6f7756beca0d35/1.3.12.2.1107.5.4.3.123456789012345.19950922.121803.8 --outputDICOM /tmp/tmp_ufwppqs.dcm --inputMetadata /tmp/tmprt7mrncn.json
[2022-11-02 11:11:34,494] [488649] [MainThread] [INFO] (monailabel.utils.others.generic:74) - dcmqi repository URL: git@github.com:QIICR/dcmqi.git revision: ef9e227 tag: v1.2.4
[2022-11-02 11:11:34,657] [488649] [MainThread] [INFO] (monailabel.utils.others.generic:74) - Searching recursively /home/manish/.cache/monailabel/dicom/488fca1f7f3f98331f6f7756beca0d35/1.3.12.2.1107.5.4.3.123456789012345.19950922.121803.8 for DICOM files
W: FrameOfReferenceUID (0020,0052) absent in FrameOfReferenceModule (type 1)
W: PositionReferenceIndicator (0020,1040) absent in FrameOfReferenceModule (type 2)
Condition failed: Tag not found in ../../include/dcmqi/ConverterBase.h:296
Fatal error encountered.
[2022-11-02 11:11:34,663] [488649] [MainThread] [INFO] (monailabel.utils.others.generic:76) - Return code: 1
[2022-11-02 11:11:34,663] [488649] [MainThread] [INFO] (monailabel.datastore.utils.convert:169) - nifti_to_dicom_seg latency : 1.1785941123962402 (sec)
[2022-11-02 11:11:34,665] [488649] [MainThread] [ERROR] (uvicorn.error:369) - Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/monailabel/endpoints/datastore.py", line 210, in api_save_label
    return save_label(background_tasks, image, params, tag, label, user.username)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/monailabel/endpoints/datastore.py", line 113, in save_label
    label_id = instance.datastore().save_label(image, label_file, tag, save_params)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/monailabel/datastore/dicom.py", line 167, in save_label
    label_series_id = dicom_web_upload_dcm(label_file, self._client)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/monailabel/datastore/utils/dicom.py", line 114, in dicom_web_upload_dcm
    dataset = dcmread(input_file)
  File "/mnt/HDD2/manish/conda/envs/munai/lib/python3.9/site-packages/pydicom/filereader.py", line 993, in dcmread
    fp = open(fp, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp_ufwppqs.dcm'
```

**Expected behavior**
The labels of the DICOM files should have been saved to the server.

**Additional context**
I am trying to annotate 2D DICOM images with OHIF viewer.

**Comment by diazandr3s** [comment]
Hi @manishdhakal,

Thanks for opening this issue.

This task isn't a segmentation task but a detection task. You may find this monaibundle useful: https://github.com/Project-MONAI/model-zoo/tree/dev/models/lung_nodule_ct_detection - this example is for 3D images, though

MONAI Label was initially designed for segmentation tasks. Detection tasks are not as mature as segmentation tasks.

Are you using the radiology app? If yes, I'd suggest you start the MONAI Label with the monaibundle and modify it accordingly to work on 2D images

Hope this helps,

**Comment by SachidanandAlle** [comment]
The DICOM conversion failed for the mask.. due to following error.. So basically you have a series (image volume) for which some of the required headers are missing.  Try some other DICOM series.. or you can convert one of the MSD dataset images using plastimatch and upload to your server.
`plastimatch convert --patient-id spleen_10 --patient-name spleen_10 --input spleen_10.nii.gz --output-dicom test`


```
[2022-11-02 11:11:34,657] [488649] [MainThread] [INFO] (monailabel.utils.others.generic:74) - Searching recursively /home/manish/.cache/monailabel/dicom/488fca1f7f3f98331f6f7756beca0d35/1.3.12.2.1107.5.4.3.123456789012345.19950922.121803.8 for DICOM files
W: FrameOfReferenceUID (0020,0052) absent in FrameOfReferenceModule (type 1)
W: PositionReferenceIndicator (0020,1040) absent in FrameOfReferenceModule (type 2)
Condition failed: Tag not found in ../../include/dcmqi/ConverterBase.h:296
Fatal error encountered.
[2022-11-02 11:11:34,663] [488649] [MainThread] [INFO] (monailabel.utils.others.generic:76) - Return code: 1
```

**Comment by SachidanandAlle** [comment]
please feel free to reopen if the issue still exists.
