### ISSUE TITLE
Met RuntimeError: Unknown type: itkMatrixF44

### ISSUE THREAD

**Issue by Isabelle-Liu** [Project-MONAI/MONAILabel#1174]
**Describe the bug**
Met RuntimeError: Unknown type: itkMatrixF44 when using Monailabel(3D slicer) on dataset

**Expected behavior**
After clicking on train button in the 3D slicer, It should load the dataset, train and show accuracy.

**Error Message**
```
[2022-12-04 18:04:55,005] [8376] [MainThread] [INFO] (monailabel.tasks.train.basic_train:344) - Total Records for Validation: 2
Loading dataset:   0%|          | 0/2 [00:00<?, ?it/s]
Loading dataset:   0%|          | 0/2 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\transforms\transform.py", line 91, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\transforms\transform.py", line 55, in _apply_transform
    return transform(parameters)
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\transforms\io\dictionary.py", line 154, in __call__
    data = self._loader(d[key], reader)
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\transforms\io\array.py", line 271, in __call__
    meta_data = switch_endianness(meta_data, "<")
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\transforms\io\array.py", line 84, in switch_endianness
    data = {k: switch_endianness(v, new) for k, v in data.items()}
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\transforms\io\array.py", line 84, in <dictcomp>
    data = {k: switch_endianness(v, new) for k, v in data.items()}
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\transforms\io\array.py", line 86, in switch_endianness
    raise RuntimeError(f"Unknown type: {type(data).__name__}")
RuntimeError: Unknown type: itkMatrixF44
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monailabel\interfaces\utils\app.py", line 132, in <module>
    run_main()
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monailabel\interfaces\utils\app.py", line 117, in run_main
    result = a.train(request)
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monailabel\interfaces\app.py", line 421, in train
    result = task(request, self.datastore())
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monailabel\tasks\train\basic_train.py", line 396, in __call__
    res = self.train(0, world_size, req, datalist)
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monailabel\tasks\train\basic_train.py", line 453, in train
    context.evaluator = self._create_evaluator(context)
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monailabel\tasks\train\basic_train.py", line 557, in _create_evaluator
    val_data_loader=self.val_data_loader(context),
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monailabel\tasks\train\basic_train.py", line 275, in val_data_loader
    dataset, datalist = self._dataset(context, context.val_datalist)
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monailabel\tasks\train\basic_train.py", line 202, in _dataset
    else SmartCacheDataset(datalist, transforms, replace_rate)
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\data\dataset.py", line 979, in __init__
    super().__init__(data, transform, cache_num, cache_rate, num_init_workers, progress, copy_cache, as_contiguous)
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\data\dataset.py", line 793, in __init__
    self.set_data(data)
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\data\dataset.py", line 1013, in set_data
    super().set_data(data)
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\data\dataset.py", line 818, in set_data
    self._cache = _compute_cache()
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\data\dataset.py", line 807, in _compute_cache
    return self._fill_cache()
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\data\dataset.py", line 827, in _fill_cache
    return list(
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\multiprocessing\pool.py", line 868, in next
    raise value
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\data\dataset.py", line 847, in _load_cache_item
    item = apply_transform(_xform, item)
  File "C:\Users\Shadow\anaconda3\envs\monailabel-some\lib\site-packages\monai\transforms\transform.py", line 118, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x000001EFC3B460A0>
[2022-12-04 18:05:03,719] [9128] [ThreadPoolExecutor-0_0] [INFO] (monailabel.utils.async_tasks.utils:77) - Return code: 1
```

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
================================
Printing MONAI config...
================================
MONAI version: 1.1.dev2249
Numpy version: 1.21.5
Pytorch version: 1.13.0
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 6ac8fa0b0d0f475a8cceea86b12e448c19aeb050
MONAI __file__: C:\Users\Shadow\anaconda3\lib\site-packages\monai\__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.10
Nibabel version: 4.0.2
scikit-image version: 0.19.2
Pillow version: 9.2.0
Tensorboard version: 2.11.0
gdown version: 4.5.4
TorchVision version: 0.14.0
tqdm version: 4.64.1
lmdb version: 1.3.0
psutil version: 5.9.0
pandas version: 1.4.4
einops version: 0.6.0
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: 0.4.3

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Windows
Win32 version: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Win32 edition: Core
Platform: Windows-10-10.0.19044-SP0
Processor: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
Machine: AMD64
Python version: 3.9.13
Process name: python.exe
Command: ['C:/Users/Shadow/anaconda3\\python.exe', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\Shadow\\AppData\\Roaming\\jupyter\\runtime\\kernel-a5f85ec8-3f4f-4fdd-9eb1-8bb5a5ffb8ba.json']
Open files: [popenfile(path='C:\\Users\\Shadow\\.ipython\\profile_default\\history.sqlite', fd=-1), popenfile(path='C:\\Windows\\System32\\en-US\\KernelBase.dll.mui', fd=-1), popenfile(path='C:\\Windows\\System32\\en-US\\kernel32.dll.mui', fd=-1), popenfile(path='C:\\Windows\\System32\\en-US\\tzres.dll.mui', fd=-1)]
Num physical CPUs: 4
Num logical CPUs: 8
Num usable CPUs: 8
CPU usage (%): [25.5, 6.8, 18.4, 10.4, 7.1, 3.6, 2.3, 8.3]
CPU freq. (MHz): 3200
Load avg. in last 1, 5, 15 mins (%): [0.0, 0.0, 0.0]
Disk usage (%): 53.7
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 12.0
Available memory (GB): 6.6
Used memory (GB): 5.4

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 11.7
cuDNN enabled: True
cuDNN version: 8500
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
GPU 0 Name: Quadro P5000
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 20
GPU 0 Total memory (GB): 16.0
GPU 0 CUDA capability (maj.min): 6.1
```

**Additional context**
Follow the monailabel quickstart

**Comment by SachidanandAlle** [comment]
Downgrade ITk version to 5.2 something.. that should solve the problem.. or upgrade the monai version to latest 1.1rc1

**Comment by Isabelle-Liu** [comment]
> Downgrade ITk version to 5.2 something.. that should solve the problem.. or upgrade the monai version to latest 1.1rc1

Thank you so much. Downgrade ITk works for me.

**Comment by sofisappia** [comment]
> > Downgrade ITk version to 5.2 something.. that should solve the problem.. or upgrade the monai version to latest 1.1rc1
> 
> Thank you so much. Downgrade ITk works for me.

Struggled with this same issue for a few days and and [SachidanandAlle's suggestion](https://github.com/Project-MONAI/MONAILabel/issues/1174#issuecomment-1336568320) worked for me too!

**Comment by domadaaaa** [comment]
> 
It doesn't work, my ITk version is 5.3.0
