### ISSUE TITLE
RuntimeError: DefaultCPUAllocator: not enough memory

### ISSUE THREAD

**Issue by sofisappia** [Project-MONAI/MONAILabel#1211]
**Describe the bug**
While trying to train a customized version of the segmentation model in the radiology app, I get a DefaultCPUAllocator error. I am training on ultrasound images of size 744 x 562 x n, where n can range from 50 - 800. The solution provided in issue #1211 seems to be outdated (links are no longer working)

**Server logs**
[2022-12-15 14:46:47,862] [3004] [MainThread] [INFO] (monailabel.utils.async_tasks.task:36) - Train request: {'model': 'segmentation_placenta', 'name': 'train_01', 'pretrained': True, 'device': 'cuda', 'max_epochs': 50, 'early_stop_patience': -1, 'val_split': 0.2, 'train_batch_size': 1, 'val_batch_size': 1, 'multi_gpu': True, 'gpus': 'all', 'dataset': 'SmartCacheDataset', 'dataloader': 'ThreadDataLoader', 'client_id': 'user-xyz'}
[2022-12-15 14:46:47,871] [3004] [ThreadPoolExecutor-0_0] [INFO] (monailabel.utils.async_tasks.utils:59) - COMMAND:: C:\Users\Sofia\miniconda3\envs\monailabel_clone\python.exe -m monailabel.interfaces.utils.app -m train -r {"model":"segmentation_placenta","name":"train_01","pretrained":true,"device":"cuda","max_epochs":50,"early_stop_patience":-1,"val_split":0.2,"train_batch_size":1,"val_batch_size":1,"multi_gpu":true,"gpus":"all","dataset":"SmartCacheDataset","dataloader":"ThreadDataLoader","client_id":"user-xyz"}
[2022-12-15 14:46:48,075] [8908] [MainThread] [INFO] (__main__:38) - Initializing App from: C:\Users\Sofia\Documents\monai_test\apps\radiology; studies: C:\Users\Sofia\Documents\monai_test\datasets\Task01_Placenta\imagesTr; conf: {'models': 'segmentation_placenta'}
[2022-12-15 14:46:52,258] [8908] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for MONAILabelApp Found: <class 'main.MyApp'>
[2022-12-15 14:46:52,275] [8908] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.deepedit.DeepEdit'>
[2022-12-15 14:46:52,276] [8908] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.deepgrow_2d.Deepgrow2D'>
[2022-12-15 14:46:52,277] [8908] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.deepgrow_3d.Deepgrow3D'>
[2022-12-15 14:46:52,277] [8908] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.localization_spine.LocalizationSpine'>
[2022-12-15 14:46:52,278] [8908] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.localization_vertebra.LocalizationVertebra'>
[2022-12-15 14:46:52,279] [8908] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation.Segmentation'>
[2022-12-15 14:46:52,280] [8908] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation_placenta.SegmentationPlacenta'>
[2022-12-15 14:46:52,281] [8908] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation_spleen.SegmentationSpleen'>
[2022-12-15 14:46:52,282] [8908] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation_vertebra.SegmentationVertebra'>
[2022-12-15 14:46:52,282] [8908] [MainThread] [INFO] (main:87) - +++ Adding Model: segmentation_placenta => lib.configs.segmentation_placenta.SegmentationPlacenta
[2022-12-15 14:46:52,312] [8908] [MainThread] [INFO] (main:91) - +++ Using Models: ['segmentation_placenta']
[2022-12-15 14:46:52,312] [8908] [MainThread] [INFO] (monailabel.interfaces.app:129) - Init Datastore for: C:\Users\Sofia Sappia\Documents\monai_test\datasets\Task01_Placenta\imagesTr
[2022-12-15 14:46:52,312] [8908] [MainThread] [INFO] (monailabel.datastore.local:128) - Auto Reload: False; Extensions: ['*.nii.gz', '*.nii', '*.nrrd', '*.jpg', '*.png', '*.tif', '*.svs', '*.xml']
[2022-12-15 14:46:52,791] [8908] [MainThread] [INFO] (monailabel.datastore.local:574) - Invalidate count: 0
[2022-12-15 14:46:52,792] [8908] [MainThread] [INFO] (main:117) - +++ Adding Inferer:: segmentation_placenta => <lib.infers.segmentation.Segmentation object at 0x000001A7ADF8DB80>
[2022-12-15 14:46:52,792] [8908] [MainThread] [INFO] (main:173) - {'segmentation_placenta': <lib.infers.segmentation.Segmentation object at 0x000001A7ADF8DB80>, 'Histogram+GraphCut': <monailabel.scribbles.infer.HistogramBasedGraphCut object at 0x000001A7ADF8DA90>, 'GMM+GraphCut': <monailabel.scribbles.infer.GMMBasedGraphCut object at 0x000001A7B053A160>}
[2022-12-15 14:46:52,792] [8908] [MainThread] [INFO] (main:186) - +++ Adding Trainer:: segmentation_placenta => <lib.trainers.segmentation.Segmentation object at 0x000001A7B053A280>
[2022-12-15 14:46:52,793] [8908] [MainThread] [INFO] (monailabel.utils.sessions:51) - Session Path: C:\Users\Sofia Sappia\.cache\monailabel\sessions
[2022-12-15 14:46:52,793] [8908] [MainThread] [INFO] (monailabel.utils.sessions:52) - Session Expiry (max): 3600
[2022-12-15 14:46:52,793] [8908] [MainThread] [INFO] (monailabel.tasks.train.basic_train:365) - Train Request (input): {'model': 'segmentation_placenta', 'name': 'train_01', 'pretrained': True, 'device': 'cuda', 'max_epochs': 50, 'early_stop_patience': -1, 'val_split': 0.2, 'train_batch_size': 1, 'val_batch_size': 1, 'multi_gpu': True, 'gpus': 'all', 'dataset': 'SmartCacheDataset', 'dataloader': 'ThreadDataLoader', 'client_id': 'user-xyz', 'local_rank': 0}
[2022-12-15 14:46:52,793] [8908] [MainThread] [INFO] (monailabel.tasks.train.basic_train:375) - CUDA_VISIBLE_DEVICES: None
[2022-12-15 14:46:52,916] [8908] [MainThread] [INFO] (monailabel.tasks.train.basic_train:380) - Distributed/Multi GPU is limited
[2022-12-15 14:46:52,916] [8908] [MainThread] [INFO] (monailabel.tasks.train.basic_train:395) - Distributed Training = FALSE
[2022-12-15 14:46:52,916] [8908] [MainThread] [INFO] (monailabel.tasks.train.basic_train:422) - 0 - Train Request (final): {'name': 'train_01', 'pretrained': True, 'device': 'cuda', 'max_epochs': 50, 'early_stop_patience': -1, 'val_split': 0.2, 'train_batch_size': 1, 'val_batch_size': 1, 'multi_gpu': False, 'gpus': 'all', 'dataset': 'SmartCacheDataset', 'dataloader': 'ThreadDataLoader', 'model': 'segmentation_placenta', 'client_id': 'user-xyz', 'local_rank': 0, 'run_id': '20221215_1446'}
[2022-12-15 14:46:52,916] [8908] [MainThread] [INFO] (monailabel.tasks.train.basic_train:521) - 0 - Using Device: cuda; IDX: None
[2022-12-15 14:46:52,916] [8908] [MainThread] [INFO] (monailabel.tasks.train.basic_train:343) - Total Records for Training: 711
[2022-12-15 14:46:52,916] [8908] [MainThread] [INFO] (monailabel.tasks.train.basic_train:344) - Total Records for Validation: 178
Loading dataset:   0%|          | 0/178 [00:00<?, ?it/s]
Loading dataset:   1%|          | 1/178 [00:12<37:32, 12.73s/it]
(...)
Loading dataset:  93%|#########3| 166/178 [21:03<01:18,  6.56s/it]
Loading dataset:  93%|#########3| 166/178 [21:06<01:31,  7.63s/it]
Traceback (most recent call last):
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\transforms\transform.py", line 91, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\transforms\transform.py", line 55, in _apply_transform
    return transform(parameters)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\transforms\spatial\dictionary.py", line 416, in __call__
    d[key] = self.spacing_transform(
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\utils\deprecate_utils.py", line 221, in _wrapper
    return func(*args, **kwargs)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\transforms\spatial\array.py", line 603, in __call__
    data_array = self.sp_resample(
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\utils\deprecate_utils.py", line 221, in _wrapper
    return func(*args, **kwargs)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\transforms\spatial\array.py", line 315, in __call__
    img = affine_xform(img.unsqueeze(0), theta=xform, spatial_size=spatial_size).squeeze(0)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\networks\layers\spatial_transforms.py", line 575, in forward
    grid = nn.functional.affine_grid(theta=theta[:, :sr], size=list(dst_size), align_corners=self.align_corners)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\torch\nn\functional.py", line 4332, in affine_grid
    return torch.affine_grid_generator(theta, size, align_corners)
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 1508295600 bytes.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monailabel\interfaces\utils\app.py", line 132, in <module>
    run_main()
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monailabel\interfaces\utils\app.py", line 117, in run_main
    result = a.train(request)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monailabel\interfaces\app.py", line 421, in train
    result = task(request, self.datastore())
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monailabel\tasks\train\basic_train.py", line 396, in __call__
    res = self.train(0, world_size, req, datalist)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monailabel\tasks\train\basic_train.py", line 453, in train
    context.evaluator = self._create_evaluator(context)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monailabel\tasks\train\basic_train.py", line 557, in _create_evaluator
    val_data_loader=self.val_data_loader(context),
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monailabel\tasks\train\basic_train.py", line 275, in val_data_loader
    dataset, datalist = self._dataset(context, context.val_datalist)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monailabel\tasks\train\basic_train.py", line 202, in _dataset
    else SmartCacheDataset(datalist, transforms, replace_rate)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\data\dataset.py", line 979, in __init__
    super().__init__(data, transform, cache_num, cache_rate, num_init_workers, progress, copy_cache, as_contiguous)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\data\dataset.py", line 793, in __init__
    self.set_data(data)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\data\dataset.py", line 1013, in set_data
    super().set_data(data)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\data\dataset.py", line 818, in set_data
    self._cache = _compute_cache()
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\data\dataset.py", line 807, in _compute_cache
    return self._fill_cache()
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\data\dataset.py", line 827, in _fill_cache
    return list(
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\multiprocessing\pool.py", line 870, in next
    raise value
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\data\dataset.py", line 847, in _load_cache_item
    item = apply_transform(_xform, item)
  File "C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\transforms\transform.py", line 118, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.spatial.dictionary.Spacingd object at 0x000001A7B7465CA0>

**To Reproduce**
1. Go to anaconda command prompt
2. Install radiology app
3. Prepare dataset with exisiting labels (images in datasets/Task01_Placenta/imagesTr; labels in subfolder labels/final)
4. Run commands: monailabel start_server --app apps/radiology --studies datasets/Task01_Placenta/imagesTr --conf models segmentation_placenta
5. Open 3D slicer and MONAI label plugin, connect to server
6. Click on train

**Expected behavior**
Training output of the model, reporting loss in the log.

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```

================================
Printing MONAI config...
================================
MONAI version: 1.0.1
Numpy version: 1.23.4
Pytorch version: 1.13.0
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 8271a193229fe4437026185e218d5b06f7c8ce69
MONAI __file__: C:\Users\Sofia\miniconda3\envs\monailabel_clone\lib\site-packages\monai\__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.10
Nibabel version: 4.0.2
scikit-image version: 0.19.3
Pillow version: 9.2.0
Tensorboard version: 2.11.0
gdown version: 4.6.0
TorchVision version: 0.14.0
tqdm version: 4.64.1
lmdb version: 1.4.0
psutil version: 5.9.4
pandas version: NOT INSTALLED or UNKNOWN VERSION.
einops version: 0.6.0
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: 0.4.3

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

================================
Printing system config...
================================
System: Windows
Win32 version: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Win32 edition: Professional
Platform: Windows-10-10.0.22000-SP0
Processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
Machine: AMD64
Python version: 3.9.15
Process name: python.exe
Command: ['C:\\Users\\Sofia\\miniconda3\\envs\\monailabel_clone\\python.exe', '-c', 'import monai; monai.config.print_debug_info()']
Open files: [popenfile(path='C:\\Windows\\System32\\en-US\\KernelBase.dll.mui', fd=-1), popenfile(path='C:\\Windows\\System32\\en-US\\kernel32.dll.mui', fd=-1)]
Num physical CPUs: 8
Num logical CPUs: 16
Num usable CPUs: 16
CPU usage (%): [5.0, 3.1, 0.0, 5.0, 5.6, 3.1, 3.8, 4.4, 0.6, 1.9, 1.2, 2.5, 1.2, 1.2, 1.9, 65.0]
CPU freq. (MHz): 2496
Load avg. in last 1, 5, 15 mins (%): [0.0, 0.0, 0.0]
Disk usage (%): 83.0
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 31.7
Available memory (GB): 21.1
Used memory (GB): 10.7

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 11.7
cuDNN enabled: True
cuDNN version: 8500
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
GPU 0 Name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 20
GPU 0 Total memory (GB): 4.0
GPU 0 CUDA capability (maj.min): 8.6

**Comment by tangy5** [comment]
Hi @sofisappia , thanks for reporting this. 
I saw the logs, you are trying to cache 178 images with original dimension of 744x562xN. Maybe it's too large to cache to the memory. 

You can disable the cache dataset and use normal dataset to train the model with these images.  By overriding the Context in basic_trainer: 
https://github.com/Project-MONAI/MONAILabel/blob/6da745682b31638bada5616882b7a54ecf88fbcc/monailabel/tasks/train/basic_train.py#L237
within the radiology app. 

Or train with less data, and train them iteratively. 
Hope this helps. Thanks.

**Comment by diazandr3s** [comment]
Agree with @tangy5.
For this dataset size, you may want to use **PersistentDataset** instead.

**Comment by sofisappia** [comment]
Thank you both @diazandr3s and @tangy5 ! Setting it to PersistentDataset solved the issue.
