### ISSUE TITLE
PIL.Image.DecompressionBombError: Image size (445833922 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

### ISSUE THREAD

**Issue by BenoitKAO** [Project-MONAI/MONAILabel#1230]
Thank you for your marvelous work!

While using QuPath with your plugin in training my annotations, I received errors.
Please help in solving these errors.

--- 
[2022-12-28 21:03:17,778] [191288] [MainThread] [INFO] (monailabel.utils.async_tasks.task:41) - Train request: {'model': 'ss', 'train_batch_size': 10, 'val_batch_size': 10}
[2022-12-28 21:03:17,778] [191288] [ThreadPoolExecutor-2_0] [INFO] (monailabel.utils.async_tasks.utils:49) - Before:: /miniconda3/envs:
[2022-12-28 21:03:17,779] [191288] [ThreadPoolExecutor-2_0] [INFO] (monailabel.utils.async_tasks.utils:53) - After:: /miniconda3/envs:
[2022-12-28 21:03:17,779] [191288] [ThreadPoolExecutor-2_0] [INFO] (monailabel.utils.async_tasks.utils:65) - COMMAND:: /miniconda3/envs/p39/bin/python -m monailabel.interfaces.utils.app -m train -r {"model":"ss","train_batch_size":10,"val_batch_size":10,"gpus":"all"}
[2022-12-28 21:03:17,878] [202303] [MainThread] [INFO] (__main__:38) - Initializing App from: /MONAILabel/monailabel/apps/pathology; studies: /MONAILabel/monailabel/datasets/pathology; conf: {}
[2022-12-28 21:03:19,114] [202303] [MainThread] [INFO] (numexpr.utils:148) - Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2022-12-28 21:03:19,114] [202303] [MainThread] [INFO] (numexpr.utils:160) - NumExpr defaulting to 8 threads.
[2022-12-28 21:03:20,654] [202303] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for MONAILabelApp Found: <class 'main.MyApp'>
[2022-12-28 21:03:20,657] [202303] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation_nuclei.SegmentationNuclei'>
[2022-12-28 21:03:20,658] [202303] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.nuclick.NuClick'>
[2022-12-28 21:03:20,658] [202303] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.hovernet_nuclei.HovernetNuclei'>
[2022-12-28 21:03:20,658] [202303] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.ss.SegmentationNuclei'>
[2022-12-28 21:03:20,658] [202303] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.classification_nuclei.ClassificationNuclei'>
[2022-12-28 21:03:20,658] [202303] [MainThread] [INFO] (main:83) - +++ Adding Model: classification_nuclei => lib.configs.classification_nuclei.ClassificationNuclei
[2022-12-28 21:03:21,073] [202303] [MainThread] [INFO] (main:83) - +++ Adding Model: hovernet_nuclei => lib.configs.hovernet_nuclei.HovernetNuclei
[2022-12-28 21:03:21,148] [202303] [MainThread] [INFO] (main:83) - +++ Adding Model: nuclick => lib.configs.nuclick.NuClick
[2022-12-28 21:03:21,211] [202303] [MainThread] [INFO] (main:83) - +++ Adding Model: ss => lib.configs.ss.SegmentationNuclei
[2022-12-28 21:03:21,279] [202303] [MainThread] [INFO] (main:83) - +++ Adding Model: segmentation_nuclei => lib.configs.segmentation_nuclei.SegmentationNuclei
[2022-12-28 21:03:21,325] [202303] [MainThread] [INFO] (main:87) - +++ Using Models: ['classification_nuclei', 'hovernet_nuclei', 'nuclick', 'ss', 'segmentation_nuclei']
[2022-12-28 21:03:21,325] [202303] [MainThread] [INFO] (monailabel.interfaces.app:135) - Init Datastore for: /MONAILabel/monailabel/datasets/pathology
[2022-12-28 21:03:21,325] [202303] [MainThread] [INFO] (monailabel.datastore.local:129) - Auto Reload: False; Extensions: ['*.nii.gz', '*.nii', '*.nrrd', '*.jpg', '*.png', '*.tif', '*.svs', '*.xml']
[2022-12-28 21:03:21,327] [202303] [MainThread] [INFO] (monailabel.datastore.local:576) - Invalidate count: 0
[2022-12-28 21:03:21,483] [202303] [MainThread] [INFO] (main:129) - +++ Adding Inferer:: classification_nuclei => <lib.infers.classification_nuclei.ClassificationNuclei object at 0x7f29d0a49100>
[2022-12-28 21:03:21,883] [202303] [MainThread] [INFO] (main:129) - +++ Adding Inferer:: hovernet_nuclei => <lib.infers.hovernet_nuclei.HovernetNuclei object at 0x7f29ae3176a0>
[2022-12-28 21:03:21,941] [202303] [MainThread] [INFO] (main:129) - +++ Adding Inferer:: nuclick => <lib.infers.nuclick.NuClick object at 0x7f299bb10a60>
[2022-12-28 21:03:21,941] [202303] [MainThread] [INFO] (lib.configs.ss:102) - Using Preload: False; ROI Size: [8192819281920, 8192819281920]
[2022-12-28 21:03:21,941] [202303] [MainThread] [INFO] (main:129) - +++ Adding Inferer:: ss => <lib.infers.segmentation_nuclei.SegmentationNuclei object at 0x7f2990d99ee0>
[2022-12-28 21:03:21,941] [202303] [MainThread] [INFO] (lib.configs.segmentation_nuclei:88) - Using Preload: False; ROI Size: [1024, 1024]
[2022-12-28 21:03:21,941] [202303] [MainThread] [INFO] (main:129) - +++ Adding Inferer:: segmentation_nuclei => <lib.infers.segmentation_nuclei.SegmentationNuclei object at 0x7f29903d6e80>
[2022-12-28 21:03:21,941] [202303] [MainThread] [INFO] (main:153) - +++ Adding Trainer:: classification_nuclei => <lib.trainers.classification_nuclei.ClassificationNuclei object at 0x7f29903d6fa0>
[2022-12-28 21:03:21,942] [202303] [MainThread] [INFO] (main:153) - +++ Adding Trainer:: hovernet_nuclei => <lib.trainers.hovernet_nuclei.HovernetNuclei object at 0x7f29903d6f70>
[2022-12-28 21:03:21,942] [202303] [MainThread] [INFO] (main:153) - +++ Adding Trainer:: nuclick => <lib.trainers.nuclick.NuClick object at 0x7f2990360bb0>
[2022-12-28 21:03:21,942] [202303] [MainThread] [INFO] (main:153) - +++ Adding Trainer:: ss => <lib.trainers.segmentation_nuclei.SegmentationNuclei object at 0x7f2990360eb0>
[2022-12-28 21:03:21,942] [202303] [MainThread] [INFO] (main:153) - +++ Adding Trainer:: segmentation_nuclei => <lib.trainers.segmentation_nuclei.SegmentationNuclei object at 0x7f2990360ee0>
[2022-12-28 21:03:21,942] [202303] [MainThread] [INFO] (main:174) - Active Learning Strategies:: ['wsi_random']
[2022-12-28 21:03:21,942] [202303] [MainThread] [INFO] (monailabel.utils.sessions:51) - Session Path: /root/.cache/monailabel/sessions
[2022-12-28 21:03:21,942] [202303] [MainThread] [INFO] (monailabel.utils.sessions:52) - Session Expiry (max): 3600
[2022-12-28 21:03:21,942] [202303] [MainThread] [INFO] (monailabel.tasks.train.basic_train:432) - Train Request (input): {'model': 'ss', 'train_batch_size': 10, 'val_batch_size': 10, 'gpus': 'all', 'local_rank': 0}
[2022-12-28 21:03:21,943] [202303] [MainThread] [INFO] (monailabel.tasks.train.basic_train:442) - CUDA_VISIBLE_DEVICES: None
[2022-12-28 21:03:21,943] [202303] [MainThread] [INFO] (monailabel.tasks.train.basic_train:605) - Running cleanup...
[2022-12-28 21:03:21,943] [202303] [MainThread] [INFO] (lib.utils:90) - Split data based on tile size: (512, 512); groups: {'CC': 1, 'll': 2, 'hh': 3}
BasicUNet features: (32, 64, 128, 256, 512, 32).
BasicUNet features: (32, 64, 128, 256, 512, 32).
BasicUNet features: (32, 64, 128, 256, 512, 32).
  0%|          | 0/7 [00:00<?, ?it/s][2022-12-28 21:03:21,944] [202303] [MainThread] [INFO] (lib.utils:550) - ++ Using Groups: {'CC': 1, 'll': 2, 'hh': 3}
[2022-12-28 21:03:21,944] [202303] [MainThread] [INFO] (lib.utils:552) - Fetching Image/Label : {'image': '/MONAILabel/monailabel/datasets/pathology/PPPP.png', 'label': '/MONAILabel/monailabel/datasets/pathology/labels/final/PPPP.xml'}
[2022-12-28 21:03:22,129] [202303] [MainThread] [INFO] (lib.utils:560) - Total Points: 18458
[2022-12-28 21:03:22,133] [202303] [MainThread] [INFO] (lib.utils:562) - ID: PPPP => Groups: dict_keys(['CC', 'll', 'hh']); Location: (1990, 350); Size: 3077 x 6109
[2022-12-28 21:03:22,946] [202303] [MainThread] [INFO] (lib.utils:616) - Image => Input: (6864, 5312, 3); Total Patches to save: 154
[2022-12-28 21:03:33,933] [202303] [MainThread] [INFO] (lib.utils:593) - CC => p: 0; c: 1; unique: (array([0], dtype=uint8), array([36461568]))
[2022-12-28 21:03:34,288] [202303] [MainThread] [INFO] (lib.utils:593) - ll => p: 14; c: 2; unique: (array([0, 2], dtype=uint8), array([35428467,  1033101]))
[2022-12-28 21:03:34,636] [202303] [MainThread] [INFO] (lib.utils:593) - hh => p: 0; c: 3; unique: (array([0, 2], dtype=uint8), array([35428467,  1033101]))
[2022-12-28 21:03:34,636] [202303] [MainThread] [INFO] (lib.utils:616) - Label => Input: (6864, 5312); Total Patches to save: 154
 14%|█▍        | 1/7 [00:12<01:17, 12.91s/it][2022-12-28 21:03:34,850] [202303] [MainThread] [INFO] (lib.utils:550) - ++ Using Groups: {'CC': 1, 'll': 2, 'hh': 3}
[2022-12-28 21:03:34,850] [202303] [MainThread] [INFO] (lib.utils:552) - Fetching Image/Label : {'image': '/MONAILabel/monailabel/datasets/pathology/PPPP.png', 'label': '/MONAILabel/monailabel/datasets/pathology/labels/final/PPPP.xml'}
[2022-12-28 21:03:35,376] [202303] [MainThread] [INFO] (lib.utils:560) - Total Points: 85424
[2022-12-28 21:03:35,393] [202303] [MainThread] [INFO] (lib.utils:562) - ID: PPPP => Groups: dict_keys(['CC', 'll', 'hh']); Location: (-1289, -586); Size: 34681 x 16388
[2022-12-28 21:03:35,393] [202303] [MainThread] [WARNING] (lib.utils:565) - Reducing Region to Max-Width; w: 34681; max_w: 10240
[2022-12-28 21:03:35,393] [202303] [MainThread] [WARNING] (lib.utils:568) - Reducing Region to Max-Height; h: 16388; max_h: 10240
 14%|█▍        | 1/7 [00:13<01:20, 13.45s/it]
Traceback (most recent call last):
  File "/miniconda3/envs/p39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/miniconda3/envs/p39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/miniconda3/envs/p39/lib/python3.9/site-packages/monailabel/interfaces/utils/app.py", line 132, in <module>
    run_main()
  File "/miniconda3/envs/p39/lib/python3.9/site-packages/monailabel/interfaces/utils/app.py", line 117, in run_main
    result = a.train(request)
  File "/miniconda3/envs/p39/lib/python3.9/site-packages/monailabel/interfaces/app.py", line 429, in train
    result = task(request, self.datastore())
  File "/miniconda3/envs/p39/lib/python3.9/site-packages/monailabel/tasks/train/basic_train.py", line 444, in __call__
    datalist = self.pre_process(req, datastore)
  File "/MONAILabel/monailabel/apps/pathology/lib/trainers/segmentation_nuclei.py", line 74, in pre_process
    return split_dataset(
  File "/MONAILabel/monailabel/apps/pathology/lib/utils.py", line 99, in split_dataset
    ds_new.extend(split_local_dataset(datastore, d, output_dir, groups, tile_size, max_region))
  File "/MONAILabel/monailabel/apps/pathology/lib/utils.py", line 261, in split_local_dataset
    img = Image.open(d["image"]).convert("RGB")
  File "/miniconda3/envs/p39/lib/python3.9/site-packages/PIL/Image.py", line 3172, in open
    im = _open_core(fp, filename, prefix, formats)
  File "/miniconda3/envs/p39/lib/python3.9/site-packages/PIL/Image.py", line 3159, in _open_core
    _decompression_bomb_check(im.size)
  File "/miniconda3/envs/p39/lib/python3.9/site-packages/PIL/Image.py", line 3068, in _decompression_bomb_check
    raise DecompressionBombError(
PIL.Image.DecompressionBombError: Image size (445833922 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
[2022-12-28 21:03:36,205] [191288] [ThreadPoolExecutor-2_0] [INFO] (monailabel.utils.async_tasks.utils:83) - Return code: 1

---
I would appreciate any help.
Best.

**Comment by SachidanandAlle** [comment]
Some image is too big..

Image size (445833922 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

Rather use smaller ROI as Train input or convert them to tiff or svs

**Comment by SachidanandAlle** [comment]
Basically when it tried to fetch the roof based on bbox it got too big roi.. you can change the limit..

https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/pathology/lib/trainers/nuclick.py#L36

**Comment by BenoitKAO** [comment]
Dear Mr. @SachidanandAlle, 
Thank you very much for your prompt response.

I have modified the python scripts in several sections to adapt the Monai Label to fit the training processing in QuPath.
However, is there a way to modify configurations before importing libraries from 'lib.utils'?

These are my concerns:

---
...
lib.utils:624) - Image => Input: (6864, 5312, 3); Total Patches to save: 154
...
[2022-12-29 14:51:55,949] [4113599] [MainThread] [WARNING] (lib.utils:573) - Reducing Region to Max-Width; w: 34681; max_w: 10240
[2022-12-29 14:51:55,949] [4113599] [MainThread] [WARNING] (lib.utils:576) - Reducing Region to Max-Height; h: 16388; max_h: 10240
[2022-12-29 14:52:05,122] [4113599] [MainThread] [INFO] (lib.utils:624) - Image => Input: (14162, 31481, 3); Total Patches to save: 1736
...

---
The training process is ongoing.
I would greatly appreciate your help.

Thank you very much again.

Best again.

**Comment by SachidanandAlle** [comment]
you can simply create the patches first using the utility which is part of the pathology app.

you can save them as png files (for label since the value is 1 or something.. you may not directly visualize them.. instead you can chose value to be 255 or 128 to see them with bare eyes on filesystem)

may be first change debug=True to save (https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/pathology/lib/utils.py#L573)


Refer (write your main function and call the split_dataset with corresponding arguments): 
https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/pathology/lib/utils.py#L36
https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/pathology/lib/utils.py#L685


but based on your logs, looks like you might have fixed the image (reduced it) but not polygon points for the label.  You may have to offset them to rescale to new image.

https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/pathology/lib/utils.py#L256
https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/pathology/lib/utils.py#L559-L570

**Comment by SachidanandAlle** [comment]
I hope you have the solution/answer for your use-case.  Closing the issue.  Please feel to open/reopen if problem persists
