### ISSUE TITLE
GMM+GraphCut Compilation Error - Windows MSVC

### ISSUE THREAD

**Issue by Thibault-Pelletier** [Project-MONAI/MONAILabel#1249]
First thank you for the great library!

I have encountered a problem when trying to use and build MONAI Label's GMM+GraphCut in a Windows environment.

The JIT compilation ends with an error with the following message : 

`C:\Work\Formation\MONAI\monai_exercises\venv\Lib\site-packages\monai\_extensions\gmm\gmm.h(15): fatal error C1189: #error:  Definition of CHANNEL_COUNT, MIXTURE_COUNT, and MIXTURE_SIZE required`

I have reused the same configuration as the Radiology app.

Here are the associated server logs : 

**Server logs**

```
[2023-01-19 11:00:32,942] [7280] [MainThread] [INFO] (uvicorn.error:45) - Waiting for application startup.
[2023-01-19 11:00:32,943] [7280] [MainThread] [INFO] (monailabel.interfaces.utils.app:38) - Initializing App from: C:\Work\Formation\MONAI\monai_exercises\radiology; studies: C:\Work\Formation\MONAI\monai_exercises\label_data; 
conf: {'models': 'all'}
[2023-01-19 11:00:33,014] [7280] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for MONAILabelApp Found: <class 'main.MyApp'>
[2023-01-19 11:00:33,026] [7280] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.deepedit.DeepEdit'>
[2023-01-19 11:00:33,026] [7280] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.deepgrow_3d.Deepgrow3D'>
[2023-01-19 11:00:33,027] [7280] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation.Segmentation'>
[2023-01-19 11:00:33,027] [7280] [MainThread] [INFO] (main:91) - +++ Adding Model: deepedit => lib.configs.deepedit.DeepEdit
[2023-01-19 11:00:33,574] [7280] [MainThread] [INFO] (lib.configs.deepedit:131) - EPISTEMIC Enabled: False; Samples: 5
[2023-01-19 11:00:33,575] [7280] [MainThread] [INFO] (main:91) - +++ Adding Model: deepgrow_3d => lib.configs.deepgrow_3d.Deepgrow3D
[2023-01-19 11:00:33,668] [7280] [MainThread] [INFO] (main:91) - +++ Adding Model: segmentation => lib.configs.segmentation.Segmentation
[2023-01-19 11:00:33,695] [7280] [MainThread] [INFO] (main:94) - +++ Using Models: ['deepedit', 'deepgrow_3d', 'segmentation']
[2023-01-19 11:00:33,695] [7280] [MainThread] [INFO] (monailabel.interfaces.app:135) - Init Datastore for: C:\Work\Formation\MONAI\monai_exercises\label_data
[2023-01-19 11:00:33,695] [7280] [MainThread] [INFO] (monailabel.datastore.local:129) - Auto Reload: True; Extensions: ['*.nii.gz', '*.nii', '*.nrrd', '*.jpg', '*.png', '*.tif', '*.svs', '*.xml']
[2023-01-19 11:00:33,701] [7280] [MainThread] [INFO] (monailabel.datastore.local:576) - Invalidate count: 0
[2023-01-19 11:00:33,701] [7280] [MainThread] [INFO] (monailabel.datastore.local:150) - Start observing external modifications on datastore (AUTO RELOAD)
[2023-01-19 11:00:33,703] [7280] [MainThread] [INFO] (main:124) - +++ Adding Inferer:: deepedit => <lib.infers.deepedit.DeepEdit object at 0x00000136C31877F0>
[2023-01-19 11:00:33,703] [7280] [MainThread] [INFO] (main:124) - +++ Adding Inferer:: deepedit_seg => <lib.infers.deepedit.DeepEdit object at 0x00000136D7C3D3C0>
[2023-01-19 11:00:33,704] [7280] [MainThread] [INFO] (main:124) - +++ Adding Inferer:: deepgrow_3d => <lib.infers.deepgrow.Deepgrow object at 0x00000136D7C3CBB0>
[2023-01-19 11:00:33,704] [7280] [MainThread] [INFO] (main:124) - +++ Adding Inferer:: segmentation => <lib.infers.segmentation.Segmentation object at 0x00000136D7C3CB80>
[2023-01-19 11:00:33,704] [7280] [MainThread] [INFO] (main:173) - +++ Adding Trainer:: deepedit => <lib.trainers.deepedit.DeepEdit object at 0x00000136D7C3D480>
[2023-01-19 11:00:33,704] [7280] [MainThread] [INFO] (main:173) - +++ Adding Trainer:: deepgrow_3d => <lib.trainers.deepgrow.Deepgrow object at 0x00000136D7C3D450>
[2023-01-19 11:00:33,704] [7280] [MainThread] [INFO] (main:173) - +++ Adding Trainer:: segmentation => <lib.trainers.segmentation.Segmentation object at 0x00000136D7C3D4B0>
[2023-01-19 11:00:33,705] [7280] [MainThread] [INFO] (monailabel.utils.sessions:51) - Session Path: C:\Users\Thibault\.cache\monailabel\sessions
[2023-01-19 11:00:33,705] [7280] [MainThread] [INFO] (monailabel.utils.sessions:52) - Session Expiry (max): 3600
[2023-01-19 11:00:33,705] [7280] [MainThread] [INFO] (monailabel.interfaces.app:475) - App Init - completed
Allow Origins: ['*']
BasicUNet features: (32, 64, 128, 256, 512, 32).
[2023-01-19 11:00:33,705] [timeloop] [INFO] Starting Timeloop..
[2023-01-19 11:00:33,705] [7280] [MainThread] [INFO] (timeloop:60) - Starting Timeloop..
[2023-01-19 11:00:33,706] [timeloop] [INFO] Registered job <function MONAILabelApp.on_init_complete.<locals>.run_scheduler at 0x00000136C31F4670>
[2023-01-19 11:00:33,706] [7280] [MainThread] [INFO] (timeloop:42) - Registered job <function MONAILabelApp.on_init_complete.<locals>.run_scheduler at 0x00000136C31F4670>
[2023-01-19 11:00:33,706] [timeloop] [INFO] Timeloop now started. Jobs will run based on the interval set
[2023-01-19 11:00:33,706] [7280] [MainThread] [INFO] (timeloop:63) - Timeloop now started. Jobs will run based on the interval set
[2023-01-19 11:00:33,706] [7280] [MainThread] [INFO] (uvicorn.error:59) - Application startup complete.
[2023-01-19 11:00:33,707] [7280] [MainThread] [INFO] (uvicorn.error:206) - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
[2023-01-19 11:00:49,076] [7280] [MainThread] [INFO] (monailabel.endpoints.infer:160) - Infer Request: {'model': 'GMM+GraphCut', 'image': 'volume', 'label': 'C:\\Users\\Thibault\\AppData\\Local\\Temp\\tmpbf6uck6n.nii.gz', 
'num_mixtures': 20, 'lamda': 5.0, 'sigma': 0.5, 'device': 'cuda', 'roi': [381, 64, 374, 136, 46, 166], 'label_info': [{'name': 'background', 'id': 1}, {'name': 'liver', 'id': 2}, {'name': 'portal vena', 'id': 3}, {'name': 
'inferior vena cava', 'id': 4}, {'name': 'background_scribbles', 'id': 5}, {'name': 'foreground_scribbles', 'id': 6}], 'selected_label_name': 'liver', 'result_extension': '.nrrd', 'result_dtype': 'uint8', 'client_id': 'user-xyz'}
[2023-01-19 11:00:49,077] [7280] [MainThread] [INFO] (monailabel.tasks.infer.basic_infer:279) - Infer Request (final): {'num_mixtures': 20, 'lamda': 5.0, 'sigma': 0.5, 'device': 'cuda', 'model': 'GMM+GraphCut', 'image': 
'C:\\Work\\Formation\\MONAI\\monai_exercises\\label_data\\volume.nii.gz', 'label': 'C:\\Users\\Thibault\\AppData\\Local\\Temp\\tmpbf6uck6n.nii.gz', 'roi': [381, 64, 374, 136, 46, 166], 'label_info': [{'name': 'background', 'id': 
1}, {'name': 'liver', 'id': 2}, {'name': 'portal vena', 'id': 3}, {'name': 'inferior vena cava', 'id': 4}, {'name': 'background_scribbles', 'id': 5}, {'name': 'foreground_scribbles', 'id': 6}], 'selected_label_name': 'liver', 
'result_extension': '.nrrd', 'result_dtype': 'uint8', 'client_id': 'user-xyz', 'description': 'A post processing step with GMM-based GraphCut for Generic segmentation'}
[2023-01-19 11:00:49,079] [7280] [MainThread] [INFO] (monailabel.interfaces.utils.transform:76) - PRE - Run Transform(s)
[2023-01-19 11:00:49,079] [7280] [MainThread] [INFO] (monailabel.interfaces.utils.transform:77) - PRE - Input Keys: ['num_mixtures', 'lamda', 'sigma', 'device', 'model', 'image', 'label', 'roi', 'label_info', 
'selected_label_name', 'result_extension', 'result_dtype', 'client_id', 'description', 'image_path']
[2023-01-19 11:00:50,691] [7280] [MainThread] [INFO] (monailabel.interfaces.utils.transform:122) - PRE - Transform (LoadImaged): Time: 1.612; image: torch.Size([512, 512, 172])(torch.float32); label: torch.Size([512, 512, 
172])(torch.float32)
[2023-01-19 11:00:50,692] [7280] [MainThread] [INFO] (monailabel.interfaces.utils.transform:122) - PRE - Transform (EnsureChannelFirstd): Time: 0.001; image: torch.Size([1, 512, 512, 172])(torch.float32); label: torch.Size([1, 
512, 512, 172])(torch.float32)
[2023-01-19 11:00:50,692] [7280] [MainThread] [INFO] (root:83) - Loading background scribbles labels from: background_scribbles with index: 5
[2023-01-19 11:00:50,692] [7280] [MainThread] [INFO] (root:88) - Loading foreground scribbles labels from: foreground_scribbles with index: 6
[2023-01-19 11:00:50,719] [7280] [MainThread] [INFO] (monailabel.scribbles.transforms:120) - Scribbles: (1, 512, 512, 172)
[2023-01-19 11:00:50,834] [7280] [MainThread] [INFO] (root:139) - warning: no foreground scribbles received with label 6, adding foreground scribbles to ROI centre
[2023-01-19 11:00:50,874] [7280] [MainThread] [INFO] (monailabel.interfaces.utils.transform:122) - PRE - Transform (AddBackgroundScribblesFromROId): Time: 0.182; image: torch.Size([1, 512, 512, 172])(torch.float32); label: 
torch.Size([1, 512, 512, 172])(torch.float32)
[2023-01-19 11:00:51,243] [7280] [MainThread] [INFO] (monailabel.interfaces.utils.transform:122) - PRE - Transform (Spacingd): Time: 0.369; image: torch.Size([1, 161, 161, 56])(torch.float32); label: torch.Size([1, 161, 161, 
56])(torch.float32)
[2023-01-19 11:00:51,250] [7280] [MainThread] [INFO] (monailabel.interfaces.utils.transform:122) - PRE - Transform (ScaleIntensityRanged): Time: 0.007; image: torch.Size([1, 161, 161, 56])(torch.float32); label: torch.Size([1, 
161, 161, 56])(torch.float32)
[2023-01-19 11:00:51,251] [7280] [MainThread] [INFO] (monailabel.tasks.infer.basic_infer:471) - Inferer:: cuda => Compose => {'transforms': (<monailabel.scribbles.transforms.MakeLikelihoodFromScribblesGMMd object at 
0x00000136D7C88970>,), 'map_items': True, 'unpack_items': False, 'log_stats': False, 'R': RandomState(MT19937) at 0x13691F2A440}
[2023-01-19 11:00:51,251] [7280] [MainThread] [INFO] (monailabel.tasks.infer.basic_infer:420) - Infer model path: None
[2023-01-19 11:00:51,252] [7280] [MainThread] [INFO] (monailabel.interfaces.utils.transform:76) - INF - Run Inferer(s)
[2023-01-19 11:00:51,252] [7280] [MainThread] [INFO] (monailabel.interfaces.utils.transform:77) - INF - Input Keys: ['num_mixtures', 'lamda', 'sigma', 'device', 'model', 'image', 'label', 'roi', 'label_info', 
'selected_label_name', 'result_extension', 'result_dtype', 'client_id', 'description', 'image_path', 'image_meta_dict', 'label_meta_dict', 'latencies']
[2023-01-19 11:00:51,253] [7280] [MainThread] [INFO] (root:83) - Loading background scribbles labels from: background_scribbles with index: 5
[2023-01-19 11:00:51,253] [7280] [MainThread] [INFO] (root:88) - Loading foreground scribbles labels from: foreground_scribbles with index: 6
[2023-01-19 11:00:59,388] [7280] [MainThread] [ERROR] (uvicorn.error:369) - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "C:\Users\Thibault\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\monailabel\endpoints\infer.py", line 179, in api_run_inference
    return run_inference(background_tasks, model, image, session_id, params, file, label, output)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\monailabel\endpoints\infer.py", line 161, in run_inference
    result = instance.infer(request)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\monailabel\interfaces\app.py", line 307, in infer
    result_file_name, result_json = task(request)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\monailabel\tasks\infer\basic_infer.py", line 306, in __call__
    data = self.run_inferer(data, device=device)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\monailabel\tasks\infer\basic_infer.py", line 496, in run_inferer
    data = run_transforms(data, inferer, log_prefix="INF", log_name="Inferer")
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\monailabel\interfaces\utils\transform.py", line 106, in run_transforms
    data = t(data)
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\monailabel\scribbles\transforms.py", line 259, in __call__
    post_proc_label = make_likelihood_image_gmm(
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\monailabel\scribbles\utils.py", line 241, in make_likelihood_image_gmm
    retprob = learn_and_apply_gmm_monai(
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\monailabel\scribbles\utils.py", line 215, in learn_and_apply_gmm_monai
    gmm = GaussianMixtureModel(
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\monai\networks\layers\gmm.py", line 42, in __init__
    self.compiled_extension = load_module(
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\monai\_extensions\loader.py", line 87, in load_module
    module = load(
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1623, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'gmm_1_2_20_Windows_3_10_9_113_11_6': [1/3] cl /showIncludes -DTORCH_EXTENSION_NAME=gmm_1_2_20_Windows_3_10_9_113_11_6 -DTORCH_API_INCLUDE_EXTENSION_H 
-IC:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\torch\include -IC:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\torch\include\torch\csrc\api\include 
-IC:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\torch\include\TH -IC:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing 
Toolkit\CUDA\v11.7\include" -IC:\Users\Thibault\AppData\Local\Programs\Python\Python310\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc "-D CHANNEL_COUNT=1" "-D MIXTURE_COUNT=2" 
"-D MIXTURE_SIZE=20" -c C:\Work\Formation\MONAI\monai_exercises\venv\Lib\site-packages\monai\_extensions\gmm\gmm_cpu.cpp /Fogmm_cpu.o 

FAILED: gmm_cpu.o 

cl /showIncludes -DTORCH_EXTENSION_NAME=gmm_1_2_20_Windows_3_10_9_113_11_6 -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\torch\include 
-IC:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\torch\include\TH 
-IC:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -IC:\Users\Thibault\AppData\Local\Programs\Python\Python310\Include 
-D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc "-D CHANNEL_COUNT=1" "-D MIXTURE_COUNT=2" "-D MIXTURE_SIZE=20" -c 
C:\Work\Formation\MONAI\monai_exercises\venv\Lib\site-packages\monai\_extensions\gmm\gmm_cpu.cpp /Fogmm_cpu.o 
```

Full logs here :  [monai_label_gmm_graphcut_error_logs.txt](https://github.com/Project-MONAI/MONAILabel/files/10455650/monai_label_gmm_graphcut_error_logs.txt)

**To Reproduce**

1. Install monailabel
2. Download radiology app
3. Open PowerShell
4. Add MSVC 2019 x64 to the shell env  `$Env:Path+=";C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\"`
5. Launch server with every model `monailabel start_server --app radiology --studies label_data --conf models all`
6. Open MonaiLabel in Slicer
7. Fetch data
8. Open GMM GraphCut Scribbles tool
9. Trigger Update

**Expected behavior**

JIT compilation of the GMM tools.

**Environment**

```
================================
Printing MONAI config...
================================
MONAI version: 1.1.0
Numpy version: 1.23.5
Pytorch version: 1.13.1+cu116
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: a2ec3752f54bfc3b40e7952234fbeb5452ed63e3
MONAI __file__: C:\Work\Formation\MONAI\monai_exercises\venv\lib\site-packages\monai\__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.10
Nibabel version: 4.0.2
scikit-image version: 0.19.3
Pillow version: 9.4.0
Tensorboard version: 2.11.0
gdown version: 4.6.0
TorchVision version: 0.14.1+cu116
tqdm version: 4.64.1
lmdb version: 1.4.0
psutil version: 5.9.4
pandas version: 1.5.2
einops version: 0.6.0
transformers version: 4.21.3
mlflow version: 2.1.1
pynrrd version: 0.4.3

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Windows
Win32 version: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Win32 edition: Professional
Platform: Windows-10-10.0.19045-SP0
Processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
Machine: AMD64
Python version: 3.10.9
Process name: python.exe
Command: ['C:\\Users\\Thibault\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-c', 'import monai; monai.config.print_debug_info()']
Open files: [popenfile(path='C:\\Program Files\\WindowsApps\\Microsoft.LanguageExperiencePackfr-FR_19041.55.176.0_neutral__8wekyb3d8bbwe\\Windows\\System32\\fr-FR\\KernelBase.dll.mui', fd=-1), popenfile(path='C:\\Program Files\\WindowsApps\\Microsoft.LanguageExperiencePackfr-FR_19041.55.176.0_neutral__8wekyb3d8bbwe\\Windows\\System32\\fr-FR\\tzres.dll.mui', fd=-1), popenfile(path='C:\\Program Files\\WindowsApps\\Microsoft.LanguageExperiencePackfr-FR_19041.55.176.0_neutral__8wekyb3d8bbwe\\Windows\\System32\\fr-FR\\kernel32.dll.mui', fd=-1)]
Num physical CPUs: 8
Num logical CPUs: 16
Num usable CPUs: 16
CPU usage (%): [17.2, 9.4, 8.1, 5.8, 11.7, 13.4, 1.3, 0.9, 21.1, 11.2, 3.1, 2.2, 1.3, 0.9, 8.9, 39.7]
CPU freq. (MHz): 2304
Load avg. in last 1, 5, 15 mins (%): [0.0, 0.0, 0.0]
Disk usage (%): 83.6
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 31.7
Available memory (GB): 11.7
Used memory (GB): 20.0

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 11.6
cuDNN enabled: True
cuDNN version: 8302
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
GPU 0 Name: NVIDIA GeForce RTX 3070 Laptop GPU
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 40
GPU 0 Total memory (GB): 8.0
GPU 0 CUDA capability (maj.min): 8.6
```

Thanks in advance for your help on this!

**Comment by SachidanandAlle** [comment]
I am not sure why are you trying to compile here.. because latest dependent libraries for scribbles come with pre-compiled binaries

**Comment by Thibault-Pelletier** [comment]
@SachidanandAlle Thank you for your reply.

I wasn't trying to do anything manually. I just noticed the code compiling on my server when using the Scribble `GMM+GraphCut` tool.

Since the dependencies come precompiled, are there specific Python versions to use on Windows? (for instance precompiled with Python 3.8, 3.9 but not 3.10) ?

**Comment by SachidanandAlle** [comment]
this is the dependency for scribbles.. https://pypi.org/project/numpymaxflow/

can you share details about your GPU

**Comment by masadcv** [comment]
Hi, 
Apologies for delayed response. 
Using `GMM+GraphCut` results in utilizing GMM from MONAI (see: https://github.com/Project-MONAI/MONAILabel/blob/d182253976d653537d236a0f4fb6539690b826b2/monailabel/scribbles/utils.py#L17 and https://github.com/Project-MONAI/MONAILabel/blob/d182253976d653537d236a0f4fb6539690b826b2/monailabel/scribbles/utils.py#L215)

As it is currently done in MONAI, this would result in compilation at runtime of the relevant GMM code in MONAI (primarily using this extension loader: https://github.com/Project-MONAI/MONAI/blob/dev/monai/_extensions/loader.py). It is maybe more relevant to open an issue in MONAI core for this as the error is coming from there.

**Comment by Thibault-Pelletier** [comment]
@masadcv and @SachidanandAlle thanks for your answers!
I will retest on my end and open up a new issue on MONAI Core with this then
