### ISSUE TITLE
Problem with early stopping in version 0.6

### ISSUE THREAD

**Issue by Jpvmello** [Project-MONAI/MONAILabel#1270]
**Describe the bug**
With version 0.5, I was able to use the MONAI Label's early stopping resource in 3D Slicer with no issues. Now, in version 0.6, it seems to have stopped working properly in the last version. In the end I propose a fix. I did not submit a pull request because the pre-commit check resulted in error for me.

**Server logs**
```
Traceback (most recent call last):
  File "/scratch/app/python/3.9.6/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/scratch/app/python/3.9.6/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "<virtualenv-path>/lib/python3.9/site-packages/monailabel/interfaces/utils/app.py", line 132, i
n <module>
    run_main()
  File "<virtualenv-path>/lib/python3.9/site-packages/monailabel/interfaces/utils/app.py", line 117, i
n run_main
    result = a.train(request)
  File "<virtualenv-path>/lib/python3.9/site-packages/monailabel/interfaces/app.py", line 429, in trai
n
    result = task(request, self.datastore())
  File "<virtualenv-path>/lib/python3.9/site-packages/monailabel/tasks/train/basic_train.py", line 459
, in __call__
    torch.multiprocessing.spawn(main_worker, nprocs=world_size, args=(world_size, req, datalist, self))
  File "<virtualenv-path>/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in sp
awn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "<virtualenv-path>/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in st
art_processes
    while not context.join():
  File "<virtualenv-path>/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in jo
in
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "<virtualenv-path>/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "<virtualenv-path>/lib/python3.9/site-packages/monailabel/tasks/train/basic_train.py", line 728, in main_worker
    task.train(rank, world_size, request, datalist)
  File "<virtualenv-path>/lib/python3.9/site-packages/monailabel/tasks/train/basic_train.py", line 544, in train
    self.finalize(context)
  File "<virtualenv-path>/lib/python3.9/site-packages/monailabel/tasks/train/basic_train.py", line 585, in finalize
    metric_name = kw.keys()[0] if kw else None
TypeError: 'dict_keys' object is not subscriptable
```

**To Reproduce**
1. Start monailabel server with any app and study: `monailabel start_server --app your_app --studies /your/studies/path/ --conf models deepedit`
2. Go to "Application Settings" in Slicer;
3. Click on "MONAI Label"
4. Check the option "Developer Mode";
5. Restart Slicer;
6. Now, MONAI Label's interface will have a "Options" tab.  In "Section" select "train" and in "early_stop_patience" insert a positive value;
7. Start training.

**Expected behavior**
The training was supposed to start properly (and it does when early stopping is not used (set to -1)).

**Environment**
```
================================
Printing MONAI config...
================================
MONAI version: 1.1.0
Numpy version: 1.23.5
Pytorch version: 1.13.0+cu117
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: a2ec3752f54bfc3b40e7952234fbeb5452ed63e3
MONAI __file__: <virtualenv-path>/lib/python3.9/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.10
Nibabel version: 4.0.2
scikit-image version: 0.19.3
Pillow version: 9.2.0
Tensorboard version: 2.11.0
gdown version: 4.5.4
TorchVision version: 0.14.0+cu117
tqdm version: 4.64.1
lmdb version: 1.3.0
psutil version: 5.9.4
pandas version: 1.5.1
einops version: 0.6.0
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: 2.1.1
pynrrd version: 0.4.3

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Linux
Linux version: Red Hat Enterprise Linux ComputeNode 7.9 (Maipo)
Platform: Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.17
Processor: x86_64
Machine: x86_64
Python version: 3.9.6
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: []
Num physical CPUs: 48
Num logical CPUs: 48
Num usable CPUs: 48
CPU usage (%): [8.1, 12.3, 2.6, 2.3, 47.2, 2.3, 100.0, 100.0, 2.3, 2.4, 2.4, 2.1, 2.4, 2.3, 2.1, 2.3, 2.3, 2.1, 2.3, 2.4, 100.0, 2.3, 2.6, 2.3, 46.4, 89.9, 2.3, 2.6, 56.1, 3.5, 3.3, 3.0, 3.1, 100.0, 36.2, 2.6, 2.8, 2.8, 2.3, 2.4, 2.4, 2.3, 2.6, 2.4, 2.3, 2.1, 2.3, 2.3]
CPU freq. (MHz): 2101
Load avg. in last 1, 5, 15 mins (%): [12.6, 12.6, 12.6]
Disk usage (%): 25.9
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 376.5
Available memory (GB): 359.3
Used memory (GB): 12.0

================================
Printing GPU config...
================================
Num GPUs: 4
Has CUDA: True
CUDA version: 11.7
cuDNN enabled: True
cuDNN version: 8500
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']
GPU 0 Name: Tesla V100-SXM2-32GB
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 80
GPU 0 Total memory (GB): 31.7
GPU 0 CUDA capability (maj.min): 7.0
GPU 1 Name: Tesla V100-SXM2-32GB
GPU 1 Is integrated: False
GPU 1 Is multi GPU board: False
GPU 1 Multi processor count: 80
GPU 1 Total memory (GB): 31.7
GPU 1 CUDA capability (maj.min): 7.0
GPU 2 Name: Tesla V100-SXM2-32GB
GPU 2 Is integrated: False
GPU 2 Is multi GPU board: False
GPU 2 Multi processor count: 80
GPU 2 Total memory (GB): 31.7
GPU 2 CUDA capability (maj.min): 7.0
GPU 3 Name: Tesla V100-SXM2-32GB
GPU 3 Is integrated: False
GPU 3 Is multi GPU board: False
GPU 3 Multi processor count: 80
GPU 3 Total memory (GB): 31.7
GPU 3 CUDA capability (maj.min): 7.0
```

**Proposed solution**
Not sure if it is a real fix or a workaround, but it started to work for me when I edited the line 585 from `monailabel/tasks/train/basic_train.py` as follows:

```metric_name = kw.keys()[0] if kw else None``` --> ```metric_name = list(kw.keys())[0] if kw else None```

**Comment by SachidanandAlle** [comment]
Can you please raise a PR if the fix makes sense..

**Comment by Jpvmello** [comment]
I tried, but the collaboration guidelines states that the pre-commit checks must pass, and they throw error for me. I can raise it directly, if there is no problem.

**Comment by SachidanandAlle** [comment]
I believe it's done.. thanks for the PR.. closing it for now
