### ISSUE TITLE
When installing MonaiLabel for Slicer, ImageDataStatistics.py is not found

### ISSUE THREAD

**Issue by w1ebr** [Project-MONAI/MONAILabel#1334]
**Describe the bug**
When installing MonaiLabel for Slicer, ImageDataStatistics.py is not found

**Server logs**
If applicable attach 100+ lines of monailabel server logs which covers the error trace etc...

**To Reproduce**
Install the MONAI plugin for slicer and then restart slicer

**Expected behavior**

**Screenshots**

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```

**Additional context**

**Comment by jamesobutler** [comment]
Hi @w1ebr, I've just tried installing the MonaiLabel Slicer extension using Slicer 5.2.2 and latest Slicer Preview 5.3.0-2023-03-07 and did not observe this issue upon restarting Slicer. This was on my Windows machine.

What version of Slicer are you using? 
What operating system are you using?
Have you tried using Slicer 5.2.2 or latest Slicer Preview 5.3.0-2023-03-07?

**Comment by w1ebr** [comment]
Hi @jamesobutler , I am using 5.3.0-2023-01-07 on Windows 10 Pro. 
This is what I get in the Python Console:

_Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Gene\AppData\Local\NA-MIC\Slicer 5.3.0-2023-01-27\lib\Python\Lib\imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:/Users/Gene/AppData/Local/NA-MIC/Slicer 5.3.0-2023-01-27/NA-MIC/Extensions-31549/MONAILabel/lib/Slicer-5.3/qt-scripted-modules/MONAILabelReviewer.py", line 23, in <module>
    from MONAILabelReviewerLib.ImageData import ImageData
  File "C:\Users\Gene\AppData\Local\NA-MIC\Slicer 5.3.0-2023-01-27\NA-MIC\Extensions-31549\MONAILabel\lib\Slicer-5.3\qt-scripted-modules\MONAILabelReviewerLib\__init__.py", line 14, in <module>
    from .ImageDataController import ImageDataController
  File "C:\Users\Gene\AppData\Local\NA-MIC\Slicer 5.3.0-2023-01-27\NA-MIC\Extensions-31549\MONAILabel\lib\Slicer-5.3\qt-scripted-modules\MONAILabelReviewerLib\ImageDataController.py", line 19, in <module>
    from MONAILabelReviewerLib.ImageDataStatistics import ImageDataStatistics
ImportError: cannot import name 'ImageDataStatistics' from 'MONAILabelReviewerLib.ImageDataStatistics' (C:\Users\Gene\AppData\Local\NA-MIC\Slicer 5.3.0-2023-01-27\NA-MIC\Extensions-31549\MONAILabel\lib\Slicer-5.3\qt-scripted-modules\MONAILabelReviewerLib\ImageDataStatistics.py)
[Qt] loadSourceAsModule - Failed to load file "C:/Users/Gene/AppData/Local/NA-MIC/Slicer 5.3.0-2023-01-27/NA-MIC/Extensions-31549/MONAILabel/lib/Slicer-5.3/qt-scripted-modules/MONAILabelReviewer.py"  as module "MONAILabelReviewer" !
[Qt] Fail to instantiate module  "MONAILabelReviewer"
[Qt] The following modules failed to be instantiated:
[Qt]    MONAILabelReviewer_

I think adding the file to the folder would probably solve the problem. I don't know how extensions are installed so I haven't looked at the source to see if the ImageDataStatistics.py file is there, or is in another version of the extention.

**Comment by w1ebr** [comment]
Hello @jamesobutler ,

I am running Slicer 5.3.0-2023-01-27 on Windows 10 Pro. This is what I get in the Python Console when starting Slicer:

_Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Gene\AppData\Local\NA-MIC\Slicer 5.3.0-2023-01-27\lib\Python\Lib\imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:/Users/Gene/AppData/Local/NA-MIC/Slicer 5.3.0-2023-01-27/NA-MIC/Extensions-31549/MONAILabel/lib/Slicer-5.3/qt-scripted-modules/MONAILabelReviewer.py", line 23, in <module>
    from MONAILabelReviewerLib.ImageData import ImageData
  File "C:\Users\Gene\AppData\Local\NA-MIC\Slicer 5.3.0-2023-01-27\NA-MIC\Extensions-31549\MONAILabel\lib\Slicer-5.3\qt-scripted-modules\MONAILabelReviewerLib\__init__.py", line 14, in <module>
    from .ImageDataController import ImageDataController
  File "C:\Users\Gene\AppData\Local\NA-MIC\Slicer 5.3.0-2023-01-27\NA-MIC\Extensions-31549\MONAILabel\lib\Slicer-5.3\qt-scripted-modules\MONAILabelReviewerLib\ImageDataController.py", line 19, in <module>
    from MONAILabelReviewerLib.ImageDataStatistics import ImageDataStatistics
ModuleNotFoundError: No module named 'MONAILabelReviewerLib.ImageDataStatistics'
[Qt] loadSourceAsModule - Failed to load file "C:/Users/Gene/AppData/Local/NA-MIC/Slicer 5.3.0-2023-01-27/NA-MIC/Extensions-31549/MONAILabel/lib/Slicer-5.3/qt-scripted-modules/MONAILabelReviewer.py"  as module "MONAILabelReviewer" !
[Qt] Fail to instantiate module  "MONAILabelReviewer"
[Qt] The following modules failed to be instantiated:
[Qt]    MONAILabelReviewer_

I haven't tried to figure out whether the source of the extension has the file because I am new at this.
Thanks for the help!

Gene

**Comment by jamesobutler** [comment]
There was issues with MONAILabelReviewer back in January that have since been resolved. To guarantee things work for you appropriately please download latest Slicer stable 5.2.2 or latest Slicer Preview. https://download.slicer.org/

**Comment by jamesobutler** [comment]
@SachidanandAlle This issue can likely be closed as completed.
