### ISSUE TITLE
Failed to save Label to MONAI Label server

### ISSUE THREAD

**Issue by nikgiannotti** [Project-MONAI/MONAILabel#1368]
Hello everyone,

After segmentation I keep receiving the following message (and I cannot submit the labels to the server):

Traceback (most recent call last):
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/NA-MIC/Extensions-31382/MONAILabel/lib/Slicer-5.2/qt-scripted-modules/MONAILabel.py", line 1465, in onSaveLabel
    result = self.logic.save_label(self.current_sample["id"], label_in, {"label_info": label_info})
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/NA-MIC/Extensions-31382/MONAILabel/lib/Slicer-5.2/qt-scripted-modules/MONAILabel.py", line 2285, in save_label
    return self._client().save_label(image_in, label_in, params=params)
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/NA-MIC/Extensions-31382/MONAILabel/lib/Slicer-5.2/qt-scripted-modules/MONAILabel.py", line 2237, in _client
    if mc.auth_enabled():
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/NA-MIC/Extensions-31382/MONAILabel/lib/Slicer-5.2/qt-scripted-modules/MONAILabelLib/client.py", line 83, in auth_enabled
    status, response, _, _ = MONAILabelUtils.http_method("GET", self._server_url, selector)
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/NA-MIC/Extensions-31382/MONAILabel/lib/Slicer-5.2/qt-scripted-modules/MONAILabelLib/client.py", line 521, in http_method
    conn.request(method, selector, body=body, headers=headers)
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/http/client.py", line 946, in connect
    self.sock = self._create_connection(
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

Can anyone help me out? Thank you!

**Comment by tangy5** [comment]
This error typically means 
host and port are not avialble or open on the server side at the time you tried to connect. Therefore the HTTP functions (request failed)

Are you using MONAI Label server and 3D Slicer in the same machine? 
You could check the connection side, whether IP host is changed and double check the port/host are open.

**Comment by nikgiannotti** [comment]
MONAI server runs in the docker, 3D Slicer in the virtual machine. Even the button "next sample" stopped working. Is it because I did not use monai and the virtual machine for long (I was attending a meeting)?

**Comment by tangy5** [comment]
yes, I feel your 3D slicer can't access to the MONAI Label server anymore, causing all communications stop. 
If you get it working at the beginning, can you use 3D Slicer's tool interface to export/save your work first (in case of effort lost), and restart everything?

**Comment by SachidanandAlle** [comment]
Looks like server was down when you submitted the label.  Check the server status.
Closing this issue for now.  If you are still having issues, feel free to reopen it with more logs and details from the server side
