### ISSUE TITLE
Error downloading CT image with MONAILabel in 3D slicer

### ISSUE THREAD

**Issue by hyeonLIB** [Project-MONAI/MONAILabel#1391]
**Describe the bug**
We have a MONAI Label server running on Ubuntu 18.04, which provides CT data and segmentation functionality to remote computers via 3D Slicer. Although we use an external IP and have set up port forwarding and allowed the firewall, only one of the four remote computers is unable to fetch datasets from the server. Despite the successful connection, fetching datasets fails on this particular computer. Only this computer shows the error. 

> File "C:/Users/user/AppData/Local/NA-MIC/Slicer 5.2.2/NA-MIC/Extensions-31382/MONAILabel/lib/Slicer-5.2/qt-scripted-modules/MONAILabel.py", line 1266, in onNextSampleButton
>     self._volumeNode = sampleDataLogic.downloadFromURL(
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Slicer-5.2\qt-scripted-modules\SampleData.py", line 768, in downloadFromURL
>     return self.downloadFromSource(SampleDataSource(
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Slicer-5.2\qt-scripted-modules\SampleData.py", line 672, in downloadFromSource
>     filePath = self.downloadFileIntoCache(uri, fileName, checksum)
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Slicer-5.2\qt-scripted-modules\SampleData.py", line 631, in downloadFileIntoCache
>     return self.downloadFile(uri, destFolderPath, name, checksum)
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Slicer-5.2\qt-scripted-modules\SampleData.py", line 862, in downloadFile
>     urllib.request.urlretrieve(uri, filePath, self.reportHook)
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\urllib\request.py", line 239, in urlretrieve
>     with contextlib.closing(urlopen(url, data)) as fp:
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\urllib\request.py", line 214, in urlopen
>     return opener.open(url, data, timeout)
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\urllib\request.py", line 517, in open
>     response = self._open(req, data)
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\urllib\request.py", line 534, in _open
>     result = self._call_chain(self.handle_open, protocol, protocol +
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\urllib\request.py", line 494, in _call_chain
>     result = func(*args)
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\urllib\request.py", line 1375, in http_open
>     return self.do_open(http.client.HTTPConnection, req)
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\urllib\request.py", line 1346, in do_open
>     h.request(req.get_method(), req.selector, req.data, headers,
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\http\client.py", line 1285, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\http\client.py", line 1296, in _send_request
>     self.putrequest(method, url, **skips)
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\http\client.py", line 1130, in putrequest
>     self._validate_path(url)
>   File "C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\http\client.py", line 1230, in _validate_path
>     raise InvalidURL(f"URL can't contain control characters. {url!r} "
> http.client.InvalidURL: URL can't contain control characters. '/\n/datastore/image?image=CT.2014_ax' (found at least '\n')"

**Expected behavior**
We have a MONAI Label server running on Ubuntu 18.04, which provides CT data and segmentation functionality to remote computers via 3D Slicer. Although we use an external IP and have set up port forwarding and allowed the firewall, only one of the four remote computers is unable to fetch datasets from the server. Despite the successful connection, fetching datasets fails on this particular computer.

**Screenshots**
![KakaoTalk_20230405_160044482](https://user-images.githubusercontent.com/89136078/230853703-d3a6261a-e58a-48d6-bf91-90e1e5735b09.jpg)

**Environment**
MONAI Label Server : Ubuntu 18.04

User : windows 11 pro

**Additional context**
Except this computer, the others work good. If there are any steps I could take to resolve this issue, please let me know. Thank you for your help.

**Comment by SachidanandAlle** [comment]
May be you can share the logs from slicer..

Also share the console logs when open python interpreter in view/edit menu

**Comment by hyeonLIB** [comment]
Thank you for your helping.

The one who I work with is already off the work so I will ask the process.

Before sharing the console logs, this is the server side logs when the fetching datasets was failed if it might be help.

> [2023-04-10 08:13:54,520] [374] [MainThread] [WARNING] (uvicorn.error:132) - Invalid HTTP request received.
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 129, in handle_events
>     event = self.conn.next_event()
>   File "/opt/conda/lib/python3.8/site-packages/h11/_connection.py", line 443, in next_event
>     exc._reraise_as_remote_protocol_error()
>   File "/opt/conda/lib/python3.8/site-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
>     raise self
>   File "/opt/conda/lib/python3.8/site-packages/h11/_connection.py", line 425, in next_event
>     event = self._extract_next_receive_event()
>   File "/opt/conda/lib/python3.8/site-packages/h11/_connection.py", line 367, in _extract_next_receive_event
>     event = self._reader(self._receive_buffer)
>   File "/opt/conda/lib/python3.8/site-packages/h11/_readers.py", line 68, in maybe_read_from_IDLE_client
>     raise LocalProtocolError("illegal request line")
> h11._util.RemoteProtocolError: illegal request line

**Comment by hyeonLIB** [comment]
I appreciate your assistance. Could you please suggest any additional steps that I could take?

**Comment by hyeonLIB** [comment]
Hi @diazandr3s 

Thank you for your help.

Yes, I have started one MONAI Label server and connected four 3D slicer viewer to the server. As I mentioned above, one of those has still failed.

There are the logs from the server side logs when I have started the server and problematic account has connected but not tried fetching yet.

```
root@orthopedics:/opt/monai# monailabel start_server -p 8881 --app apps/radiology --studies ./datasets/gnuh/normal/2019 --conf models segmentation
Using PYTHONPATH=/opt:

2023-04-14 02:02:00,526 - USING:: version = False
2023-04-14 02:02:00,526 - USING:: app = /opt/monai/apps/radiology
2023-04-14 02:02:00,526 - USING:: studies = /opt/monai/datasets/gnuh/normal/2019
2023-04-14 02:02:00,526 - USING:: verbose = INFO
2023-04-14 02:02:00,526 - USING:: conf = [['models', 'segmentation']]
2023-04-14 02:02:00,526 - USING:: host = 0.0.0.0
2023-04-14 02:02:00,526 - USING:: port = 8881
2023-04-14 02:02:00,526 - USING:: uvicorn_app = monailabel.app:app
2023-04-14 02:02:00,526 - USING:: ssl_keyfile = None
2023-04-14 02:02:00,526 - USING:: ssl_certfile = None
2023-04-14 02:02:00,526 - USING:: ssl_keyfile_password = None
2023-04-14 02:02:00,526 - USING:: ssl_ca_certs = None
2023-04-14 02:02:00,526 - USING:: workers = None
2023-04-14 02:02:00,526 - USING:: limit_concurrency = None
2023-04-14 02:02:00,526 - USING:: access_log = False
2023-04-14 02:02:00,526 - USING:: log_config = None
2023-04-14 02:02:00,526 - USING:: dryrun = False
2023-04-14 02:02:00,526 - USING:: action = start_server
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_API_STR = 
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_PROJECT_NAME = MONAILabel
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_APP_DIR = 
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_STUDIES = 
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_AUTH_ENABLE = False
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_AUTH_DB = 
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_APP_CONF = '{}'
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_TASKS_TRAIN = True
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_TASKS_STRATEGY = True
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_TASKS_SCORING = True
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_TASKS_BATCH_INFER = True
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_DATASTORE = 
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_URL = 
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_USERNAME = 
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_PASSWORD = 
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_API_KEY = 
2023-04-14 02:02:00,526 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_CACHE_PATH = 
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_PROJECT = 
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_ASSET_PATH = 
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_DSA_ANNOTATION_GROUPS = 
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_USERNAME = 
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_PASSWORD = 
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CACHE_PATH = 
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_QIDO_PREFIX = None
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_WADO_PREFIX = None
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_STOW_PREFIX = None
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_FETCH_BY_FRAME = False
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CONVERT_TO_NIFTI = True
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_SEARCH_FILTER = '{"Modality": "CT"}'
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CACHE_EXPIRY = 180
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_PROXY_TIMEOUT = 30.0
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_READ_TIMEOUT = 5.0
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_AUTO_RELOAD = True
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_READ_ONLY = False
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_FILE_EXT = '["*.nii.gz", "*.nii", "*.nrrd", "*.jpg", "*.png", "*.tif", "*.svs", "*.xml"]'
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_SERVER_PORT = 8000
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_CORS_ORIGINS = '[]'
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_SESSIONS = True
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_SESSION_PATH = 
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_SESSION_EXPIRY = 3600
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_INFER_CONCURRENCY = -1
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_INFER_TIMEOUT = 600
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_TRACKING_ENABLED = True
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_TRACKING_URI = 
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_ZOO_SOURCE = github
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_ZOO_REPO = Project-MONAI/model-zoo/hosting_storage_v1
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_ZOO_AUTH_TOKEN = 
2023-04-14 02:02:00,527 - ENV SETTINGS:: MONAI_LABEL_AUTO_UPDATE_SCORING = True
2023-04-14 02:02:00,527 - 
Allow Origins: ['*']
[2023-04-14 02:02:00,922] [669] [MainThread] [INFO] (uvicorn.error:75) - Started server process [669]
[2023-04-14 02:02:00,923] [669] [MainThread] [INFO] (uvicorn.error:45) - Waiting for application startup.
[2023-04-14 02:02:00,923] [669] [MainThread] [INFO] (monailabel.interfaces.utils.app:38) - Initializing App from: /opt/monai/apps/radiology; studies: /opt/monai/datasets/gnuh/normal/2019; conf: {'models': 'segmentation'}
[2023-04-14 02:02:01,071] [669] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for MONAILabelApp Found: <class 'main.MyApp'>
[2023-04-14 02:02:01,079] [669] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.deepedit.DeepEdit'>
[2023-04-14 02:02:01,079] [669] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation_vertebra.SegmentationVertebra'>
[2023-04-14 02:02:01,080] [669] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation.Segmentation'>
[2023-04-14 02:02:01,080] [669] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.localization_vertebra.LocalizationVertebra'>
[2023-04-14 02:02:01,080] [669] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation_spleen.SegmentationSpleen'>
[2023-04-14 02:02:01,081] [669] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.deepgrow_2d.Deepgrow2D'>
[2023-04-14 02:02:01,081] [669] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.deepgrow_3d.Deepgrow3D'>
[2023-04-14 02:02:01,082] [669] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.localization_spine.LocalizationSpine'>
[2023-04-14 02:02:01,082] [669] [MainThread] [INFO] (main:93) - +++ Adding Model: segmentation => lib.configs.segmentation.Segmentation
[2023-04-14 02:02:01,207] [669] [MainThread] [INFO] (main:96) - +++ Using Models: ['segmentation']
[2023-04-14 02:02:01,208] [669] [MainThread] [INFO] (monailabel.interfaces.app:135) - Init Datastore for: /opt/monai/datasets/gnuh/normal/2019
[2023-04-14 02:02:01,208] [669] [MainThread] [INFO] (monailabel.datastore.local:129) - Auto Reload: True; Extensions: ['*.nii.gz', '*.nii', '*.nrrd', '*.jpg', '*.png', '*.tif', '*.svs', '*.xml']
[2023-04-14 02:02:01,224] [669] [MainThread] [INFO] (monailabel.datastore.local:576) - Invalidate count: 0
[2023-04-14 02:02:01,224] [669] [MainThread] [INFO] (monailabel.datastore.local:150) - Start observing external modifications on datastore (AUTO RELOAD)
[2023-04-14 02:02:01,226] [669] [MainThread] [INFO] (main:126) - +++ Adding Inferer:: segmentation => <lib.infers.segmentation.Segmentation object at 0x7f7b12e60940>
[2023-04-14 02:02:01,226] [669] [MainThread] [INFO] (main:191) - {'segmentation': <lib.infers.segmentation.Segmentation object at 0x7f7b12e60940>, 'Histogram+GraphCut': <monailabel.scribbles.infer.HistogramBasedGraphCut object at 0x7f7b0c095940>, 'GMM+GraphCut': <monailabel.scribbles.infer.GMMBasedGraphCut object at 0x7f7b0c095910>}
[2023-04-14 02:02:01,227] [669] [MainThread] [INFO] (main:206) - +++ Adding Trainer:: segmentation => <lib.trainers.segmentation.Segmentation object at 0x7f7b0c04edf0>
[2023-04-14 02:02:01,227] [669] [MainThread] [INFO] (monailabel.utils.sessions:51) - Session Path: /root/.cache/monailabel/sessions
[2023-04-14 02:02:01,227] [669] [MainThread] [INFO] (monailabel.utils.sessions:52) - Session Expiry (max): 3600
[2023-04-14 02:02:01,227] [669] [MainThread] [INFO] (monailabel.interfaces.app:475) - App Init - completed
[2023-04-14 02:02:01,228] [timeloop] [INFO] Starting Timeloop..
[2023-04-14 02:02:01,228] [669] [MainThread] [INFO] (timeloop:60) - Starting Timeloop..
[2023-04-14 02:02:01,229] [timeloop] [INFO] Registered job <function MONAILabelApp.on_init_complete.<locals>.run_scheduler at 0x7f7b0c139280>
[2023-04-14 02:02:01,229] [669] [MainThread] [INFO] (timeloop:42) - Registered job <function MONAILabelApp.on_init_complete.<locals>.run_scheduler at 0x7f7b0c139280>
[2023-04-14 02:02:01,229] [timeloop] [INFO] Timeloop now started. Jobs will run based on the interval set
[2023-04-14 02:02:01,229] [669] [MainThread] [INFO] (timeloop:63) - Timeloop now started. Jobs will run based on the interval set
[2023-04-14 02:02:01,229] [669] [MainThread] [INFO] (uvicorn.error:59) - Application startup complete.
[2023-04-14 02:02:01,230] [669] [MainThread] [INFO] (uvicorn.error:206) - Uvicorn running on http://0.0.0.0:8881 (Press CTRL+C to quit)
[2023-04-14 02:02:35,445] [669] [MainThread] [INFO] (monailabel.endpoints.activelearning:43) - Active Learning Request: {'strategy': 'random', 'client_id': 'user-xyz'}
[2023-04-14 02:02:35,448] [669] [MainThread] [INFO] (monailabel.tasks.activelearning.random:47) - Random: Selected Image: CT.20191127.20220822160308.053.4225202_ax; Weight: 758889
[2023-04-14 02:02:35,455] [669] [MainThread] [INFO] (monailabel.endpoints.activelearning:59) - Next sample: {'id': 'CT.20191127.20220822160308.053.4225202_ax', 'weight': 758889, 'path': '/opt/monai/datasets/gnuh/normal/2019/CT.20191127.20220822160308.053.4225202_ax.nii.gz', 'ts': 1680657740, 'name': 'CT.20191127.20220822160308.053.4225202_ax.nii.gz', 'strategy': {'random': {'ts': 1681437755, 'client_id': 'user-xyz'}}}

```

**Comment by SachidanandAlle** [comment]
You check on 3D slicer as one of them is failing.. logs on my 3d slicer.. also you can paste full stack trace from error window.. snapshot is not showing full trace..

Also open python console on my 3d slicer and see what's getting printed.. some debug and developer info are printed.. u can share them too

**Comment by hyeonLIB** [comment]
@SachidanandAlle 

I appreciate your help. 

If I understand correctly, when I attempted to retrieve data from the Monai server, "the full stack trace from error window" refers to the error window in Slicer. I have included the details(traceback) of the Slicer error in the first comment.

Additionally, I have pasted the Python console on my 3D Slicer in the third comment, assuming that is what you were referring to.


> > May be you can share the logs from slicer..
> > Also share the console logs when open python interpreter in view/edit menu
> 
> Okay so, here are the console logs in Python interpreter in view/edit menu
> 
> > Python 3.9.10 (main, Feb 22 2023, 01:07:37) [MSC v.1930 64 bit (AMD64)] on win32
> > > > >
> > 
> > 
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/b/bc/BaselineFollowupSCANRegisteredCMFreg2.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://wiki.slicer.org/slicerWiki/images/2/2a/CarreraSliceEffect.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/b/b9/ChangeTracker_logo.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/b/b7/CurveMakerIcon.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://slicer.org/slicerWiki/images/9/92/DSC_logo_Resized.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/a/ac/ErodeDilateLabelIcon.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/1/16/FilmDosimetry_Logo_128x128.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/f/f1/GelDosimetry_Logo_128x128.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/a/a7/GyroGuide.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/e/e5/QuickToolsLogo.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://wiki.slicer.org/slicerWiki/images/f/f6/IntensitySegmenterIcon.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/e/e8/MatlabBridgeLogo.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://slicer.org/slicerWiki/images/4/43/Slicer4ExtensionModelToModelDistance.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/a/ac/PAAlogo-small.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/2/21/PerkTutorLogo.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/b/b1/DPetBrainQuantification.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://wiki.slicer.org/slicerWiki/images/3/34/PkModeling.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/a/a7/Portplacement_icon.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://wiki.slicer.org/slicerWiki/images/d/d6/ResectionPlannerLogo.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/b/ba/SegAidedRegSquareFocus128.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/f/f2/SkullStripper.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://raw.githubusercontent.com/SlicerDMRI/slicerdmri.github.io/master/images/DMRI_3D_SLICER-icon.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://raw.githubusercontent.com/QIICR/SlicerDevelopmentToolbox/master/Resources/Icons/SlicerDevelopmentToolbox.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/2/2b/SlicerIGTLogo.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://wiki.slicer.org/slicerWiki/images/8/87/SlicerProstate_Logo_1.0_128x128.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/2/29/SlicerRT_Logo_3.0_128x128.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/6/64/SlicerToKiwiExporterLogo.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.nitrc.org/project/screenshot.php?group_id=196&screenshot_id=269'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://slicer.org/slicerWiki/images/3/32/T1_Mapping_Logo_Resized.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://wiki.slicer.org/slicerWiki/images/9/92/TCIABrowser_logo.png'. This content should also be served over HTTPS.
> > [Qt] Mixed Content: The page at 'https://extensions.slicer.org/catalog/All/31382/win' was loaded over HTTPS, but requested an insecure image 'http://www.slicer.org/slicerWiki/images/c/c2/VolumeClipLogo.png'. This content should also be served over HTTPS.
> > [Qt] A cookie associated with a cross-site resource at http://www.nitrc.org/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
> > [Python] Failed to fetch Sample from MONAI Label Server.
> > [Python] Failed to fetch Sample from MONAI Label Server.
> > [Python] Failed to fetch Sample from MONAI Label Server.
> > [Python] Failed to fetch Sample from MONAI Label Server.
> > [Python] Failed to fetch Sample from MONAI Label Server.
> > [Python] Failed to fetch Sample from MONAI Label Server.
> > [Python] Failed to fetch Sample from MONAI Label Server.
> > [Python] Failed to fetch Sample from MONAI Label Server.
> > [Python] Failed to fetch Sample from MONAI Label Server.
> > [Python] Failed to fetch Sample from MONAI Label Server.
> > [Python] Failed to fetch Sample from MONAI Label Server.
> > C:\Users\user\AppData\Local\NA-MIC\Slicer 5.2.2\bin\Python\slicer\util.py:2527: UserWarning: does not have observer
> > warn('does not have observer')

**Comment by SachidanandAlle** [comment]
Can you list the file names.. there is some url encoding issue.. may be try to rename to simple and see..

I see this in the error..
n/datastore/image?image=CT.2014_ax

**Comment by hyeonLIB** [comment]
My coworker removed the patient number on the logs so I asked the raw logs.

```
raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/\n/datastore/image?image=CT.20191213.20220822160323.071.5618202_ax' (found at least '\n')

```

CT.20190105.20220822160339.444.6657404_ax.nii.gz
CT.20190106.20220822160201.408.6202_ax.nii.gz
CT.20190117.20220822161423.429.75944_pct_ax_3mm.nii.gz
CT.20190826.20220822160233.185.2235302_ax.nii.gz
CT.20190829.20220822161317.416.14173_pct_ax_3mm.nii.gz
CT.20190917.20220822161410.466.6286206_ax.nii.gz
CT.20191013.20220822161517.696.11191204_ax.nii.gz
CT.20191127.20220822160308.053.4225202_ax.nii.gz
CT.20191213.20220822160323.071.5618202_ax.nii.gz
CT.20191215.20220822161322.713.1931202_ax.nii.gz
CT.20191217.20220822160330.087.6124202_ax.nii.gz
CT.20191221.20220822161329.531.2394204_ax.nii.gz
CT.20191223.20220822160224.569.1583202_ax.nii.gz
datastore_v2.json
labels

**Comment by SachidanandAlle** [comment]
Some of the files have new line characters..

**Comment by hyeonLIB** [comment]
Could the issue possibly lie in the files name? It is strange how other viewers could access the data... They all are in same OS which is win10 pro.

Could you suggest where I should concentrate my troubleshot efforts whether it's on the server side or client side?

**Comment by diazandr3s** [comment]
Hi @hyeonLIB,

As @SachidanandAlle suggested, try renaming the images simpler (i.e. img001.nii.gz, img000.nii.gz, etc) and see if you still get the same error.

Please let us know how that goes

**Comment by SachidanandAlle** [comment]
only simple names are supported for images/labels.. please remove any control characters from the image names
`raise InvalidURL(f"URL can't contain control characters. {url!r}`
