### ISSUE TITLE
Application startup failed:  No module named 'monailabel.tasks.activelearning.tta'

### ISSUE THREAD

**Issue by Isabelle-Liu** [Project-MONAI/MONAILabel#1409]
When trying to start up the application met the error message: 
```
Using PYTHONPATH=/Users/isabelleliu/MONAILabel:

[2023-04-19 20:27:43,282] [40175] [MainThread] [INFO] (__main__:285) - USING:: version = False
[2023-04-19 20:27:43,282] [40175] [MainThread] [INFO] (__main__:285) - USING:: app = /Users/isabelleliu/apps/radiology
[2023-04-19 20:27:43,282] [40175] [MainThread] [INFO] (__main__:285) - USING:: studies = /Users/isabelleliu/Velar_dataset
[2023-04-19 20:27:43,282] [40175] [MainThread] [INFO] (__main__:285) - USING:: verbose = INFO
[2023-04-19 20:27:43,282] [40175] [MainThread] [INFO] (__main__:285) - USING:: conf = [['models', 'deepedit']]
[2023-04-19 20:27:43,282] [40175] [MainThread] [INFO] (__main__:285) - USING:: host = 0.0.0.0
[2023-04-19 20:27:43,282] [40175] [MainThread] [INFO] (__main__:285) - USING:: port = 8000
[2023-04-19 20:27:43,282] [40175] [MainThread] [INFO] (__main__:285) - USING:: uvicorn_app = monailabel.app:app
[2023-04-19 20:27:43,282] [40175] [MainThread] [INFO] (__main__:285) - USING:: ssl_keyfile = None
[2023-04-19 20:27:43,282] [40175] [MainThread] [INFO] (__main__:285) - USING:: ssl_certfile = None
[2023-04-19 20:27:43,282] [40175] [MainThread] [INFO] (__main__:285) - USING:: ssl_keyfile_password = None
[2023-04-19 20:27:43,283] [40175] [MainThread] [INFO] (__main__:285) - USING:: ssl_ca_certs = None
[2023-04-19 20:27:43,283] [40175] [MainThread] [INFO] (__main__:285) - USING:: workers = None
[2023-04-19 20:27:43,283] [40175] [MainThread] [INFO] (__main__:285) - USING:: limit_concurrency = None
[2023-04-19 20:27:43,283] [40175] [MainThread] [INFO] (__main__:285) - USING:: access_log = False
[2023-04-19 20:27:43,283] [40175] [MainThread] [INFO] (__main__:285) - USING:: root_path = /
[2023-04-19 20:27:43,283] [40175] [MainThread] [INFO] (__main__:285) - USING:: log_level = info
[2023-04-19 20:27:43,283] [40175] [MainThread] [INFO] (__main__:285) - USING:: log_config = None
[2023-04-19 20:27:43,283] [40175] [MainThread] [INFO] (__main__:285) - USING:: dryrun = False
[2023-04-19 20:27:43,283] [40175] [MainThread] [INFO] (__main__:285) - USING:: action = start_server
[2023-04-19 20:27:43,283] [40175] [MainThread] [INFO] (__main__:296) - 
Allow Origins: ['*']
[2023-04-19 20:27:43,942] [40175] [MainThread] [INFO] (uvicorn.error:74) - Started server process [40175]
[2023-04-19 20:27:43,943] [40175] [MainThread] [INFO] (uvicorn.error:48) - Waiting for application startup.
[2023-04-19 20:27:43,943] [40175] [MainThread] [INFO] (monailabel.interfaces.utils.app:37) - Initializing App from: /Users/isabelleliu/apps/radiology; studies: /Users/isabelleliu/Velar_dataset; conf: {'models': 'deepedit'}
[2023-04-19 20:27:44,131] [40175] [MainThread] [INFO] (monailabel.utils.others.class_utils:57) - Subclass for MONAILabelApp Found: <class 'main.MyApp'>
[2023-04-19 20:27:44,139] [40175] [MainThread] [ERROR] (uvicorn.error:123) - Traceback (most recent call last):
  File "/opt/anaconda3/envs/monailabel_env/lib/python3.8/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/opt/anaconda3/envs/monailabel_env/lib/python3.8/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/opt/anaconda3/envs/monailabel_env/lib/python3.8/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/Users/isabelleliu/MONAILabel/monailabel/app.py", line 108, in startup_event
    instance = app_instance()
  File "/Users/isabelleliu/MONAILabel/monailabel/interfaces/utils/app.py", line 50, in app_instance
    app = c(app_dir=app_dir, studies=studies, conf=conf)
  File "/Users/isabelleliu/apps/radiology/main.py", line 45, in __init__
    for c in get_class_names(lib.configs, "TaskConfig"):
  File "/Users/isabelleliu/MONAILabel/monailabel/utils/others/class_utils.py", line 164, in get_class_names
    module = importlib.import_module("." + name, package=current_module_name)
  File "/opt/anaconda3/envs/monailabel_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/isabelleliu/apps/radiology/lib/configs/deepedit.py", line 26, in <module>
    from monailabel.tasks.activelearning.tta import TTA
ModuleNotFoundError: No module named 'monailabel.tasks.activelearning.tta'

[2023-04-19 20:27:44,140] [40175] [MainThread] [ERROR] (uvicorn.error:59) - Application startup failed. Exiting.
```

Can anyone help me solve this issue?

**Comment by SachidanandAlle** [comment]
Looks like an installation issue.. can u uninstall everything.. and try the latest RC version

https://pypi.org/project/monailabel/0.7.0rc5/

Also you can share the full command you tried to run..

**Comment by Isabelle-Liu** [comment]
> Looks like an installation issue.. can u uninstall everything.. and try the latest RC version
> 
> https://pypi.org/project/monailabel/0.7.0rc5/
> 
> Also you can share the full command you tried to run..

Thanks for your reply. I have uninstalled and reinstalled monailabel several times with both the latest RC version and the stable PyPI release version 
I am trying to start-up using "monailabel start_server --app app/radiology --studies Velar_dataset --conf models deepedit". I will try to reinstall it one more time now.

**Comment by Isabelle-Liu** [comment]
By the way, I've been using it for a while, and this problem just popped up today.

**Comment by SachidanandAlle** [comment]
If still not working.. then check where is monailabel installed and add the
corresponding module into PYTHONPATH

**Comment by Isabelle-Liu** [comment]
Thank you .add the corresponding module into PYTHONPATH works
