### ISSUE TITLE
Hovernet Training Error 

### ISSUE THREAD

**Issue by OmarAshkar** [Project-MONAI/MONAILabel#1421]
**Describe the bug**
I am trying annotate and train WSI using HoverNet from the QuPath plugin. Currently, I am playing with the demos to see if it will work for me. The annotation buttons and submition is working as expected. However, training using HoverNet Nuclei gives the following error:

**Server logs**
```
 {'image': '/workspace/apps/pathology/model/pathology_nuclei_segmentation_classification/cache/train_ds/nuclei_hovernet/JP2K-33003-1%20-%20Copy-patch-2306_8811_1024_1024_179_22_1024_1024_0x0_048_image.npy',
  'label_inst': '/workspace/apps/pathology/model/pathology_nuclei_segmentation_classification/cache/train_ds/nuclei_hovernet/JP2K-33003-1%20-%20Copy-patch-2306_8811_1024_1024_179_22_1024_1024_0x0_048_inst_map.npy',
  'label_type': '/workspace/apps/pathology/model/pathology_nuclei_segmentation_classification/cache/train_ds/nuclei_hovernet/JP2K-33003-1%20-%20Copy-patch-2306_8811_1024_1024_179_22_1024_1024_0x0_048_type_map.npy'}]
2023-04-28 14:37:58,326 - INFO - > stage: 0
2023-04-28 14:37:58,326 - INFO - > network_def#freeze_encoder: True
2023-04-28 14:37:58,326 - INFO - > network_def#pretrained_url: 'file:///workspace/apps/pathology/model/pathology_nuclei_segmentation_classification/models/stage0/model.pt'
2023-04-28 14:37:58,326 - INFO - ---
Traceback (most recent call last):
  File "/opt/monai/monai/bundle/reference_resolver.py", line 122, in _resolve_one_item
    item = look_up_option(id, self.items, print_all_options=False, default=kwargs.get("default", "no_default"))
  File "/opt/monai/monai/utils/module.py", line 128, in look_up_option
    raise ValueError(
ValueError: By 'training', did you mean 'train'?
'training' is not a valid value.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/monailabel/interfaces/utils/app.py", line 132, in <module>
    run_main()
  File "/opt/conda/lib/python3.8/site-packages/monailabel/interfaces/utils/app.py", line 117, in run_main
    result = a.train(request)
  File "/opt/conda/lib/python3.8/site-packages/monailabel/interfaces/app.py", line 429, in train
    result = task(request, self.datastore())
  File "/opt/conda/lib/python3.8/site-packages/monailabel/tasks/train/bundle.py", line 296, in __call__
    self.run_single_gpu(request, overrides)
  File "/workspace/apps/pathology/lib/trainers/hovernet_nuclei.py", line 116, in run_single_gpu
    super().run_single_gpu(request, overrides)
  File "/opt/conda/lib/python3.8/site-packages/monailabel/tasks/train/bundle.py", line 302, in run_single_gpu
    monai.bundle.run(
  File "/opt/monai/monai/bundle/scripts.py", line 742, in run
    return [parser.get_parsed_content(i, lazy=True, eval_expr=True, instantiate=True) for i in ensure_tuple(runner_id_)]
  File "/opt/monai/monai/bundle/scripts.py", line 742, in <listcomp>
    return [parser.get_parsed_content(i, lazy=True, eval_expr=True, instantiate=True) for i in ensure_tuple(runner_id_)]
  File "/opt/monai/monai/bundle/config_parser.py", line 271, in get_parsed_content
    return self.ref_resolver.get_resolved_content(id=id, **kwargs)
  File "/opt/monai/monai/bundle/reference_resolver.py", line 185, in get_resolved_content
    return self._resolve_one_item(id=id, **kwargs)
  File "/opt/monai/monai/bundle/reference_resolver.py", line 124, in _resolve_one_item
    raise KeyError(f"id='{id}' is not found in the config resolver.") from err
KeyError: "id='training' is not found in the config resolver."
[2023-04-28 14:37:59,287] [19941] [ThreadPoolExecutor-2_0] [INFO] (monailabel.utils.async_tasks.utils:83) - Return code: 1


**To Reproduce**
Steps to reproduce the behavior:
1. Install Monailabel docker image
2. download the app and sample data in container
3. Lunch QuPath and install the plugin
4. Start pulling the sample
5. Run "Active Learning"  to get a patch
6. Press Annotate and select hovernet
7. Refine labels and click submit
8. Click training > select "hovernet nuclei"
```
**Expected behavior**
I expected the training will run and new model will be created.

**Environment**
I am running Monai Label docker 0.6

**Additional context**
Nuclei segmentation method do work. Also, I would appreciate if you can give me a context on how to change the classes of HoverNet. How to change the mapping coming from the model from let's say `0: inflammatory` to a custom classes? 

Best Regards,
Omar

**Comment by SachidanandAlle** [comment]
there is some issue/changes with latest bundle.. please update the monailabel to latest rc candidate
https://pypi.org/project/monailabel/0.7.0rc6/

**Comment by SachidanandAlle** [comment]
Do we need to release a RC candidate to fix this one more time?

**Comment by tangy5** [comment]
Hi @SachidanandAlle @OmarAshkar , thanks, the 0.7 RC version should work. 
Can you try "pip uninstall monailabel" and then "pip install monailabel==0.7.0rc5"?

The bundle API is updated, the key is changed. And lastest bundle with an older version of MONAI Label is not a compatible case. 
We support the latest MONAI Label with older version bundles well.
