### ISSUE TITLE
qMRMLSegmentEditorWidget has no attribute named 'setSourceVolumeNode'

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAILabel#1440]
**Describe the bug**
with slicer 5.0.2:
```
Traceback (most recent call last):
  File "/Users/Documents/MONAILabel/plugins/slicer/MONAILabel/MONAILabel.py", line 1292, in onNextSampleButton
  File "/Users/Documents/MONAILabel/plugins/slicer/MONAILabel/MONAILabel.py", line 1315, in initSample
    self.ui.embeddedSegmentEditorWidget.setSegmentationNode(self._segmentNode)
AttributeError: qMRMLSegmentEditorWidget has no attribute named 'setSourceVolumeNode'

```

It seems `setSourceVolumeNode` is introduced since slicer 5.2 https://github.com/Slicer/Slicer/commit/5dfb6fb6945d3fb56320c2920571f3ffcc5b48fb

Upgrading slicer to version 5.2.2 addressed the issue.
Would be great to clarify the version requirements

**Comment by lassoan** [comment]
We usually deal with this in two 3 phases:

1. Until the extension remain fully compatible with the previous Slicer version then we keep using the main branch of the extension with the previous and current Slicer versions.
2. If small API changes occur in Slicer we make changes in the extension so that it remains compatible with both previous and current Slicer versions (e.g., check Slicer version and use method name corresponding to that version). 
3. If maintaining compatibility with various Slicer versions becomes too complex then we create a branch in the extension repository (e.g., `Slicer-5.0`) and put that branch name in the extension description in https://github.com/Slicer/ExtensionsIndex

You don't need to maintain a list of branches/versions in this repository that describes which MONAILabel extension versions/branches are compatible with which Slicer version, but instead you can describe how users can get that information from the ExtensionsIndex repository (or just use the Extensions Manager in Slicer to install extensions). 

To fix the current incompatibility issue, you can update the https://github.com/Slicer/ExtensionsIndex/blob/5.0/MONAILabel.s4ext file (replace `main` with a git hash or branch name that is compatible with Slicer-5.0). If the extension catalog contains a broken MONAILabel extension for Slicer-5.0 then you can ask @jcfr to remove it to avoid any confusion. You could make the current extension compatible with Slicer-5.0 and then create a new extension package, but it would probably not worth the effort, as we don't recommend people to use Slicer-5.0 anyway (but they should use the latest Slicer Stable Release, which is now 5.2.x).
