### ISSUE TITLE
Keep getting  "403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Project-MONAI/model-zoo/releases" error

### ISSUE THREAD

**Issue by Rajeshtims** [Project-MONAI/MONAILabel#1451]
I am trying to start the server and I keep getting the  403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Project-MONAI/model-zoo/releases error.

I am using it on a conda environment. I tried with setting concurrency from 2-20, still no luck.

**### Here is the command I used to start the server:**

monailabel start_server --app C:/Users/raj/apps/pathology --studies C:/Users/raj/datasets/ --conf models hovernet_nuclei --limit_concurrency 2

**Here is the full error:**

(monai_conda) C:\Users\raj>monailabel start_server --app C:/Users/raj/apps/pathology --studies C:/Users/raj/datasets/ --conf models hovernet_nuclei --limit_concurrency 2
Using PYTHONPATH=C:\Users\raj\Anaconda3\envs;C:\Users\raj\Anaconda3\envs;C:\Users\raj\Anaconda3
""
2023-05-25 09:05:51,983 - USING:: version = False
2023-05-25 09:05:51,983 - USING:: app = C:\Users\raj\apps\pathology
2023-05-25 09:05:51,987 - USING:: studies = C:\Users\raj\datasets
2023-05-25 09:05:51,995 - USING:: verbose = INFO
2023-05-25 09:05:51,995 - USING:: conf = [['models', 'hovernet_nuclei']]
2023-05-25 09:05:51,996 - USING:: host = 0.0.0.0
2023-05-25 09:05:51,997 - USING:: port = 8000
2023-05-25 09:05:51,997 - USING:: uvicorn_app = monailabel.app:app
2023-05-25 09:05:51,999 - USING:: ssl_keyfile = None
2023-05-25 09:05:51,999 - USING:: ssl_certfile = None
2023-05-25 09:05:52,001 - USING:: ssl_keyfile_password = None
2023-05-25 09:05:52,001 - USING:: ssl_ca_certs = None
2023-05-25 09:05:52,002 - USING:: workers = None
2023-05-25 09:05:52,003 - USING:: limit_concurrency = 2
2023-05-25 09:05:52,004 - USING:: access_log = False
2023-05-25 09:05:52,004 - USING:: log_config = None
2023-05-25 09:05:52,005 - USING:: dryrun = False
2023-05-25 09:05:52,006 - USING:: action = start_server
2023-05-25 09:05:52,007 - ENV SETTINGS:: MONAI_LABEL_API_STR =
2023-05-25 09:05:52,012 - ENV SETTINGS:: MONAI_LABEL_PROJECT_NAME = MONAILabel
2023-05-25 09:05:52,012 - ENV SETTINGS:: MONAI_LABEL_APP_DIR =
2023-05-25 09:05:52,015 - ENV SETTINGS:: MONAI_LABEL_STUDIES =
2023-05-25 09:05:52,017 - ENV SETTINGS:: MONAI_LABEL_AUTH_ENABLE = False
2023-05-25 09:05:52,020 - ENV SETTINGS:: MONAI_LABEL_AUTH_DB =
2023-05-25 09:05:52,020 - ENV SETTINGS:: MONAI_LABEL_APP_CONF = '{}'
2023-05-25 09:05:52,025 - ENV SETTINGS:: MONAI_LABEL_TASKS_TRAIN = True
2023-05-25 09:05:52,026 - ENV SETTINGS:: MONAI_LABEL_TASKS_STRATEGY = True
2023-05-25 09:05:52,027 - ENV SETTINGS:: MONAI_LABEL_TASKS_SCORING = True
2023-05-25 09:05:52,028 - ENV SETTINGS:: MONAI_LABEL_TASKS_BATCH_INFER = True
2023-05-25 09:05:52,028 - ENV SETTINGS:: MONAI_LABEL_DATASTORE =
2023-05-25 09:05:52,029 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_URL =
2023-05-25 09:05:52,030 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_USERNAME =
2023-05-25 09:05:52,030 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_PASSWORD =
2023-05-25 09:05:52,031 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_API_KEY =
2023-05-25 09:05:52,031 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_CACHE_PATH =
2023-05-25 09:05:52,033 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_PROJECT =
2023-05-25 09:05:52,034 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_ASSET_PATH =
2023-05-25 09:05:52,034 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_DSA_ANNOTATION_GROUPS =
2023-05-25 09:05:52,035 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_USERNAME =
2023-05-25 09:05:52,036 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_PASSWORD =
2023-05-25 09:05:52,036 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CACHE_PATH =
2023-05-25 09:05:52,042 - ENV SETTINGS:: MONAI_LABEL_QIDO_PREFIX = None
2023-05-25 09:05:52,042 - ENV SETTINGS:: MONAI_LABEL_WADO_PREFIX = None
2023-05-25 09:05:52,046 - ENV SETTINGS:: MONAI_LABEL_STOW_PREFIX = None
2023-05-25 09:05:52,047 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_FETCH_BY_FRAME = False
2023-05-25 09:05:52,050 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CONVERT_TO_NIFTI = True
2023-05-25 09:05:52,051 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_SEARCH_FILTER = '{"Modality": "CT"}'
2023-05-25 09:05:52,055 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CACHE_EXPIRY = 180
2023-05-25 09:05:52,056 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_PROXY_TIMEOUT = 30.0
2023-05-25 09:05:52,057 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_READ_TIMEOUT = 5.0
2023-05-25 09:05:52,059 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_AUTO_RELOAD = True
2023-05-25 09:05:52,059 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_READ_ONLY = False
2023-05-25 09:05:52,060 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_FILE_EXT = '["*.nii.gz", "*.nii", "*.nrrd", "*.jpg", "*.png", "*.tif", "*.svs", "*.xml"]'
2023-05-25 09:05:52,060 - ENV SETTINGS:: MONAI_LABEL_SERVER_PORT = 8000
2023-05-25 09:05:52,061 - ENV SETTINGS:: MONAI_LABEL_CORS_ORIGINS = '[]'
2023-05-25 09:05:52,062 - ENV SETTINGS:: MONAI_LABEL_SESSIONS = True
2023-05-25 09:05:52,063 - ENV SETTINGS:: MONAI_LABEL_SESSION_PATH =
2023-05-25 09:05:52,063 - ENV SETTINGS:: MONAI_LABEL_SESSION_EXPIRY = 3600
2023-05-25 09:05:52,064 - ENV SETTINGS:: MONAI_LABEL_INFER_CONCURRENCY = -1
2023-05-25 09:05:52,065 - ENV SETTINGS:: MONAI_LABEL_INFER_TIMEOUT = 600
2023-05-25 09:05:52,067 - ENV SETTINGS:: MONAI_LABEL_TRACKING_ENABLED = True
2023-05-25 09:05:52,067 - ENV SETTINGS:: MONAI_LABEL_TRACKING_URI =
2023-05-25 09:05:52,073 - ENV SETTINGS:: MONAI_ZOO_SOURCE = github
2023-05-25 09:05:52,074 - ENV SETTINGS:: MONAI_ZOO_REPO = Project-MONAI/model-zoo/hosting_storage_v1
2023-05-25 09:05:52,077 - ENV SETTINGS:: MONAI_ZOO_AUTH_TOKEN =
2023-05-25 09:05:52,078 - ENV SETTINGS:: MONAI_LABEL_AUTO_UPDATE_SCORING = True
2023-05-25 09:05:52,078 -
Allow Origins: ['*']
[2023-05-25 09:05:52,829] [20476] [MainThread] [INFO] (uvicorn.error:75) - Started server process [20476]
[2023-05-25 09:05:52,830] [20476] [MainThread] [INFO] (uvicorn.error:45) - Waiting for application startup.
[2023-05-25 09:05:52,833] [20476] [MainThread] [INFO] (monailabel.interfaces.utils.app:39) - Initializing App from: C:\Users\raj\apps\pathology; studies: C:\Users\raj\datasets; conf: {'models': 'hovernet_nuclei'}
[2023-05-25 09:05:52,885] [20476] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for MONAILabelApp Found: <class 'main.MyApp'>
[2023-05-25 09:05:52,893] [20476] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.classification_nuclei.ClassificationNuclei'>
[2023-05-25 09:05:52,894] [20476] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.hovernet_nuclei.HovernetNuclei'>
[2023-05-25 09:05:52,895] [20476] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.nuclick.NuClick'>
[2023-05-25 09:05:52,896] [20476] [MainThread] [INFO] (monailabel.utils.others.class_utils:37) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation_nuclei.SegmentationNuclei'>
[2023-05-25 09:05:52,897] [20476] [MainThread] [INFO] (main:83) - +++ Adding Model: hovernet_nuclei => lib.configs.hovernet_nuclei.HovernetNuclei
[2023-05-25 09:05:53,127] [20476] [MainThread] [ERROR] (uvicorn.error:119) - Traceback (most recent call last):
  File "C:\Users\raj\Anaconda3\envs\monai_conda\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\raj\Anaconda3\envs\monai_conda\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\raj\Anaconda3\envs\monai_conda\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "C:\Users\raj\Anaconda3\envs\monai_conda\lib\site-packages\monailabel\app.py", line 106, in startup_event
    instance = app_instance()
  File "C:\Users\raj\Anaconda3\envs\monai_conda\lib\site-packages\monailabel\interfaces\utils\app.py", line 52, in app_instance
    app = c(app_dir=app_dir, studies=studies, conf=conf)
  File "C:\Users\raj\apps\pathology\main.py", line 85, in __init__
    self.models[k].init(k, self.model_dir, conf, None)
  File "C:\Users\raj\apps\pathology\lib\configs\hovernet_nuclei.py", line 33, in init
    bundle_version = get_bundle_versions(bundle_name, repo=f"{repo_owner}/{repo_name}", tag=tag_name)[
  File "C:\Users\raj\Anaconda3\envs\monai_conda\lib\site-packages\monai\bundle\scripts.py", line 520, in get_bundle_versions
    bundles_info = _get_all_bundles_info(repo=repo, tag=tag, auth_token=auth_token)
  File "C:\Users\raj\Anaconda3\envs\monai_conda\lib\site-packages\monai\bundle\scripts.py", line 434, in _get_all_bundles_info
    resp.raise_for_status()
  File "C:\Users\raj\Anaconda3\envs\monai_conda\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Project-MONAI/model-zoo/releases

[2023-05-25 09:05:53,129] [20476] [MainThread] [ERROR] (uvicorn.error:56) - Application startup failed. Exiting.

------------------------------------------------------------------------------------------------

**Here is the output of:
python -c 'import monai; monai.config.print_debug_info()'**

================================
Printing MONAI config...
================================
MONAI version: 1.1.0
Numpy version: 1.24.3
Pytorch version: 2.0.0
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: a2ec3752f54bfc3b40e7952234fbeb5452ed63e3
MONAI __file__: C:\Users\generics\Anaconda3\envs\monai_conda\lib\site-packages\monai\__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.10
Nibabel version: 5.1.0
scikit-image version: 0.20.0
Pillow version: 9.4.0
Tensorboard version: 2.13.0
gdown version: 4.7.1
TorchVision version: 0.14.1+cpu
tqdm version: 4.65.0
lmdb version: 1.4.1
psutil version: 5.9.5
pandas version: 2.0.1
einops version: 0.6.1
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: 2.3.2
pynrrd version: 0.4.3

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

================================
Printing system config...
================================
System: Windows
Win32 version: ('10', '10.0.17763', 'SP0', 'Multiprocessor Free')
Win32 edition: EnterpriseS
Platform: Windows-10-10.0.17763-SP0
Processor: Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
Machine: AMD64
Python version: 3.10.11
Process name: python.exe
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: [popenfile(path='C:\\Windows\\System32\\en-US\\KernelBase.dll.mui', fd=-1), popenfile(path='C:\\Windows\\System32\\en-US\\kernel32.dll.mui', fd=-1), popenfile(path='C:\\Windows\\System32\\en-US\\tzres.dll.mui', fd=-1)]
Num physical CPUs: 8
Num logical CPUs: 16
Num usable CPUs: 16
CPU usage (%): [7.2, 2.5, 8.2, 1.1, 1.7, 0.3, 1.7, 2.3, 4.3, 0.6, 1.1, 1.1, 4.0, 0.3, 1.1, 53.1]
CPU freq. (MHz): 3592
Load avg. in last 1, 5, 15 mins (%): [0.0, 0.0, 0.0]
Disk usage (%): 65.1
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 63.7
Available memory (GB): 48.7
Used memory (GB): 15.0

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 11.8
cuDNN enabled: True
cuDNN version: 8700
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'sm_90', 'compute_37']
GPU 0 Name: NVIDIA GeForce RTX 2080 Ti
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 68
GPU 0 Total memory (GB): 11.0
GPU 0 CUDA capability (maj.min): 7.5

*************************************************************************************************

**I have the following packages installed:**

#
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
alembic                   1.11.1                   pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
asgiref                   3.6.0                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
bcrypt                    3.2.2                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
blas                      1.0                         mkl
blinker                   1.6.2                    pypi_0    pypi
brotlipy                  0.7.0           py310h2bbff1b_1002
bzip2                     1.0.8                he774522_0
ca-certificates           2023.01.10           haa95532_0
cachetools                5.2.0                    pypi_0    pypi
certifi                   2023.5.7        py310haa95532_0
cffi                      1.15.1          py310h2bbff1b_3
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cryptography              39.0.1          py310h21b164f_0
cuda-cccl                 12.1.109                      0    nvidia
cuda-cudart               11.8.89                       0    nvidia
cuda-cudart-dev           11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-libraries-dev        11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvrtc-dev            11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-profiler-api         12.1.105                      0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cycler                    0.11.0                   pypi_0    pypi
databricks-cli            0.17.7                   pypi_0    pypi
dicomweb-client           0.56.2                   pypi_0    pypi
diskcache                 5.6.1                    pypi_0    pypi
docker                    6.1.2                    pypi_0    pypi
ecdsa                     0.18.0                   pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
expiring-dict             1.1.0                    pypi_0    pypi
expiringdict              1.2.1                    pypi_0    pypi
fastapi                   0.78.0                   pypi_0    pypi
filelock                  3.7.1                    pypi_0    pypi
fire                      0.5.0                    pypi_0    pypi
flask                     2.3.2                    pypi_0    pypi
fonttools                 4.39.4                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0
gdown                     4.7.1                    pypi_0    pypi
giflib                    5.2.1                h8cc25b3_3
girder-client             3.1.14                   pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
google-auth               2.18.1                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
greenlet                  2.0.2                    pypi_0    pypi
grpcio                    1.54.2                   pypi_0    pypi
h11                       0.12.0                   pypi_0    pypi
httpcore                  0.15.0                   pypi_0    pypi
httpx                     0.23.0                   pypi_0    pypi
idna                      3.4             py310haa95532_0
imageio                   2.28.1                   pypi_0    pypi
importlib-metadata        6.6.0                    pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46319
itk                       5.3.0                    pypi_0    pypi
itk-core                  5.3.0                    pypi_0    pypi
itk-filtering             5.3.0                    pypi_0    pypi
itk-io                    5.3.0                    pypi_0    pypi
itk-numerics              5.3.0                    pypi_0    pypi
itk-registration          5.3.0                    pypi_0    pypi
itk-segmentation          5.3.0                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jinja2                    3.1.2           py310haa95532_0
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h2bbff1b_1
jsonschema                3.2.0                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lazy-loader               0.2                      pypi_0    pypi
lerc                      3.0                  hd77b12b_0
libcublas                 11.11.3.6                     0    nvidia
libcublas-dev             11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufft-dev              10.9.0.58                     0    nvidia
libcurand                 10.3.2.106                    0    nvidia
libcurand-dev             10.3.2.106                    0    nvidia
libcusolver               11.4.1.48                     0    nvidia
libcusolver-dev           11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libcusparse-dev           11.7.5.86                     0    nvidia
libdeflate                1.17                 h2bbff1b_0
libffi                    3.4.4                hd77b12b_0
libnpp                    11.8.0.86                     0    nvidia
libnpp-dev                11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libnvjpeg-dev             11.9.0.86                     0    nvidia
libpng                    1.6.39               h8cc25b3_0
libtiff                   4.5.0                h6c2663c_2
libuv                     1.44.2               h2bbff1b_0
libwebp                   1.2.4                hbc33d0d_1
libwebp-base              1.2.4                h2bbff1b_1
lmdb                      1.4.1                    pypi_0    pypi
lz4-c                     1.9.4                h2bbff1b_0
mako                      1.2.4                    pypi_0    pypi
markdown                  3.4.3                    pypi_0    pypi
markupsafe                2.1.1           py310h2bbff1b_0
matplotlib                3.7.1                    pypi_0    pypi
mkl                       2023.1.0         h8bd8f75_46356
mkl-service               2.4.0           py310h2bbff1b_1
mkl_fft                   1.3.6           py310h4ed8f06_1
mkl_random                1.2.2           py310h4ed8f06_1
mlflow                    2.3.2                    pypi_0    pypi
monai                     1.1.0                    pypi_0    pypi
monailabel                0.6.0                    pypi_0    pypi
mpmath                    1.2.1           py310haa95532_0
networkx                  2.8.4           py310haa95532_1
nibabel                   5.1.0                    pypi_0    pypi
ninja                     1.10.2.3                 pypi_0    pypi
numpy                     1.24.3          py310h055cbcc_1
numpy-base                1.24.3          py310h65a83cf_1
numpymaxflow              0.0.5                    pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python-headless    4.5.5.64                 pypi_0    pypi
openslide-python          1.1.2                    pypi_0    pypi
openssl                   1.1.1t               h2bbff1b_0
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.1                    pypi_0    pypi
passlib                   1.7.4                    pypi_0    pypi
pillow                    9.4.0           py310hd77b12b_0
pip                       23.0.1          py310haa95532_0
protobuf                  4.23.1                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pyarrow                   11.0.0                   pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pydantic                  1.10.7                   pypi_0    pypi
pydicom                   2.3.0                    pypi_0    pypi
pydicom-seg               0.4.0                    pypi_0    pypi
pyjwt                     2.7.0                    pypi_0    pypi
pynetdicom                2.0.2                    pypi_0    pypi
pynrrd                    0.4.3                    pypi_0    pypi
pyopenssl                 23.0.0          py310haa95532_0
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pysocks                   1.7.1           py310haa95532_0
python                    3.10.11              h966fe2a_2
python-dateutil           2.8.2                    pypi_0    pypi
python-dotenv             0.20.0                   pypi_0    pypi
python-jose               3.3.0                    pypi_0    pypi
python-multipart          0.0.5                    pypi_0    pypi
pytorch                   2.0.0           py3.10_cuda11.8_cudnn8_0    pytorch
pytorch-cuda              11.8                 h24eeafa_5    pytorch
pytorch-ignite            0.4.10                   pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
querystring-parser        1.2.4                    pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
requests-toolbelt         0.9.1                    pypi_0    pypi
retrying                  1.3.4                    pypi_0    pypi
rfc3986                   1.5.0                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
schedule                  1.1.0                    pypi_0    pypi
scikit-image              0.20.0                   pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                66.0.0          py310haa95532_0
shapely                   1.8.2                    pypi_0    pypi
simpleitk                 2.2.1                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlalchemy                2.0.13                   pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
sqlparse                  0.4.4                    pypi_0    pypi
starlette                 0.19.1                   pypi_0    pypi
sympy                     1.11.1          py310haa95532_0
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0
tensorboard               2.13.0                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2023.4.12                pypi_0    pypi
timeloop                  1.0.2                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
torch                     1.13.1                   pypi_0    pypi
torchaudio                2.0.0                    pypi_0    pypi
torchvision               0.14.1                   pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
typing_extensions         4.5.0           py310haa95532_0
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.15         py310haa95532_0
uvicorn                   0.17.6                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
waitress                  2.1.2                    pypi_0    pypi
watchdog                  2.1.8                    pypi_0    pypi
websocket-client          1.5.1                    pypi_0    pypi
werkzeug                  2.3.4                    pypi_0    pypi
wheel                     0.38.4          py310haa95532_0
win_inet_pton             1.1.0           py310haa95532_0
xz                        5.4.2                h8cc25b3_0
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.5                hd43e919_0

**Comment by tangy5** [comment]
Hi @Rajeshtims , there is a rate limited for accessing the MONAI Model Zoo, from MONAI Label side, now we have updated the logic. 
If you can upgrade MONAI Label to 0.7.0rc versions, it allows access for several time in a short time without a requirement of providing a Github auth token. pip install monailabel==0.7.0rc7

Another option is you can provide your own Github auth token when staring monailabel server to get unlimited access:
monailabel start_server --app <> --studies <> --conf models <> --conf auth_token <YOUR GITHUB AUTH TOKEN>

Thanks.

**Comment by Rajeshtims** [comment]
Thank you very much !!!
