### ISSUE TITLE
Monailabel Gui/App not starting at all

### ISSUE THREAD

**Issue by raghavzns** [Project-MONAI/MONAILabel#1513]
**Describe the bug**
When i try to start the monailabel I cant see any gui at all, all i see is a page with 

**Server logs**
Using PYTHONPATH=/home/monai/.conda/envs:

2023-08-01 14:52:40,075 - USING:: version = False
2023-08-01 14:52:40,075 - USING:: app = /home/monai/radiology
2023-08-01 14:52:40,075 - USING:: studies = http://127.0.0.1:8042/dicom-web
2023-08-01 14:52:40,075 - USING:: verbose = INFO
2023-08-01 14:52:40,075 - USING:: conf = [['models', 'segmentation']]
2023-08-01 14:52:40,075 - USING:: host = 0.0.0.0
2023-08-01 14:52:40,075 - USING:: port = 8000
2023-08-01 14:52:40,075 - USING:: uvicorn_app = monailabel.app:app
2023-08-01 14:52:40,076 - USING:: ssl_keyfile = None
2023-08-01 14:52:40,076 - USING:: ssl_certfile = None
2023-08-01 14:52:40,076 - USING:: ssl_keyfile_password = None
2023-08-01 14:52:40,076 - USING:: ssl_ca_certs = None
2023-08-01 14:52:40,076 - USING:: workers = None
2023-08-01 14:52:40,076 - USING:: limit_concurrency = None
2023-08-01 14:52:40,076 - USING:: access_log = False
2023-08-01 14:52:40,076 - USING:: log_config = None
2023-08-01 14:52:40,076 - USING:: dryrun = False
2023-08-01 14:52:40,076 - USING:: action = start_server
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_API_STR = 
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_PROJECT_NAME = MONAILabel
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_APP_DIR = 
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_STUDIES = 
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_APP_CONF = '{}'
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_AUTH_ENABLE = False
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_AUTH_REALM_URI = http://localhost:8080/realms/monailabel
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_AUTH_TIMEOUT = 10
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_AUTH_TOKEN_USERNAME = preferred_username
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_AUTH_TOKEN_EMAIL = email
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_AUTH_TOKEN_NAME = name
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_AUTH_TOKEN_ROLES = realm_access#roles
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_AUTH_ROLE_ADMIN = monailabel-admin
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_AUTH_ROLE_RESEARCHER = monailabel-researcher
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_AUTH_ROLE_REVIEWER = monailabel-reviewer
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_AUTH_ROLE_ANNOTATOR = monailabel-annotator
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_AUTH_ROLE_USER = monailabel-user
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_TASKS_TRAIN = True
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_TASKS_STRATEGY = True
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_TASKS_SCORING = True
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_TASKS_BATCH_INFER = True
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DATASTORE = 
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_URL = 
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_USERNAME = 
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_PASSWORD = 
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_API_KEY = 
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_CACHE_PATH = 
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_PROJECT = 
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_ASSET_PATH = 
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_DSA_ANNOTATION_GROUPS = 
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_USERNAME = orthanc
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_PASSWORD = *******
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CACHE_PATH = 
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_QIDO_PREFIX = None
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_WADO_PREFIX = None
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_STOW_PREFIX = None
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_FETCH_BY_FRAME = False
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CONVERT_TO_NIFTI = True
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_SEARCH_FILTER = '{"Modality": "CT"}'
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CACHE_EXPIRY = 180
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_PROXY_TIMEOUT = 30.0
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_READ_TIMEOUT = 5.0
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_AUTO_RELOAD = True
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_READ_ONLY = False
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_DATASTORE_FILE_EXT = '["*.nii.gz", "*.nii", "*.nrrd", "*.jpg", "*.png", "*.tif", "*.svs", "*.xml"]'
2023-08-01 14:52:40,076 - ENV SETTINGS:: MONAI_LABEL_SERVER_PORT = 8000
2023-08-01 14:52:40,077 - ENV SETTINGS:: MONAI_LABEL_CORS_ORIGINS = '[]'
2023-08-01 14:52:40,077 - ENV SETTINGS:: MONAI_LABEL_SESSIONS = True
2023-08-01 14:52:40,077 - ENV SETTINGS:: MONAI_LABEL_SESSION_PATH = 
2023-08-01 14:52:40,077 - ENV SETTINGS:: MONAI_LABEL_SESSION_EXPIRY = 3600
2023-08-01 14:52:40,077 - ENV SETTINGS:: MONAI_LABEL_INFER_CONCURRENCY = -1
2023-08-01 14:52:40,077 - ENV SETTINGS:: MONAI_LABEL_INFER_TIMEOUT = 600
2023-08-01 14:52:40,077 - ENV SETTINGS:: MONAI_LABEL_TRACKING_ENABLED = True
2023-08-01 14:52:40,077 - ENV SETTINGS:: MONAI_LABEL_TRACKING_URI = 
2023-08-01 14:52:40,077 - ENV SETTINGS:: MONAI_ZOO_SOURCE = github
2023-08-01 14:52:40,077 - ENV SETTINGS:: MONAI_ZOO_REPO = Project-MONAI/model-zoo/hosting_storage_v1
2023-08-01 14:52:40,077 - ENV SETTINGS:: MONAI_ZOO_AUTH_TOKEN = 
2023-08-01 14:52:40,077 - ENV SETTINGS:: MONAI_LABEL_AUTO_UPDATE_SCORING = True
2023-08-01 14:52:40,077 - 
Allow Origins: ['*']
[2023-08-01 14:52:40,374] [82566] [MainThread] [INFO] (uvicorn.error:75) - Started server process [82566]
[2023-08-01 14:52:40,375] [82566] [MainThread] [INFO] (uvicorn.error:45) - Waiting for application startup.
[2023-08-01 14:52:40,375] [82566] [MainThread] [INFO] (monailabel.interfaces.utils.app:37) - Initializing App from: /home/monai/radiology; studies: http://127.0.0.1:8042/dicom-web; conf: {'models': 'segmentation'}
[2023-08-01 14:52:40,429] [82566] [MainThread] [INFO] (monailabel.utils.others.class_utils:57) - Subclass for MONAILabelApp Found: <class 'main.MyApp'>
[2023-08-01 14:52:40,433] [82566] [MainThread] [INFO] (monailabel.utils.others.class_utils:57) - Subclass for TaskConfig Found: <class 'lib.configs.localization_vertebra.LocalizationVertebra'>
[2023-08-01 14:52:40,433] [82566] [MainThread] [INFO] (monailabel.utils.others.class_utils:57) - Subclass for TaskConfig Found: <class 'lib.configs.localization_spine.LocalizationSpine'>
[2023-08-01 14:52:40,434] [82566] [MainThread] [INFO] (monailabel.utils.others.class_utils:57) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation_spleen.SegmentationSpleen'>
[2023-08-01 14:52:40,434] [82566] [MainThread] [INFO] (monailabel.utils.others.class_utils:57) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation.Segmentation'>
[2023-08-01 14:52:40,434] [82566] [MainThread] [INFO] (monailabel.utils.others.class_utils:57) - Subclass for TaskConfig Found: <class 'lib.configs.deepedit.DeepEdit'>
[2023-08-01 14:52:40,434] [82566] [MainThread] [INFO] (monailabel.utils.others.class_utils:57) - Subclass for TaskConfig Found: <class 'lib.configs.segmentation_vertebra.SegmentationVertebra'>
[2023-08-01 14:52:40,434] [82566] [MainThread] [INFO] (monailabel.utils.others.class_utils:57) - Subclass for TaskConfig Found: <class 'lib.configs.deepgrow_2d.Deepgrow2D'>
[2023-08-01 14:52:40,435] [82566] [MainThread] [INFO] (monailabel.utils.others.class_utils:57) - Subclass for TaskConfig Found: <class 'lib.configs.deepgrow_3d.Deepgrow3D'>
[2023-08-01 14:52:40,435] [82566] [MainThread] [INFO] (main:93) - +++ Adding Model: segmentation => lib.configs.segmentation.Segmentation
[2023-08-01 14:52:40,465] [82566] [MainThread] [INFO] (main:96) - +++ Using Models: ['segmentation']
[2023-08-01 14:52:40,466] [82566] [MainThread] [INFO] (monailabel.interfaces.app:134) - Init Datastore for: http://127.0.0.1:8042/dicom-web
[2023-08-01 14:52:40,466] [82566] [MainThread] [INFO] (monailabel.interfaces.app:155) - Using DICOM WEB: http://127.0.0.1:8042/dicom-web
[2023-08-01 14:52:40,466] [82566] [MainThread] [INFO] (monailabel.datastore.dicom:62) - DICOMWeb Datastore (cache) Path: /home/monai/.cache/monailabel/dicom/488fca1f7f3f98331f6f7756beca0d35; FetchByFrame: False
[2023-08-01 14:52:40,466] [82566] [MainThread] [INFO] (monailabel.datastore.dicom:63) - DICOMWeb Convert To Nifti: True
[2023-08-01 14:52:40,467] [82566] [MainThread] [INFO] (monailabel.datastore.local:130) - Auto Reload: True; Extensions: ('*.nii.gz', '*.nii')
[2023-08-01 14:52:40,467] [82566] [MainThread] [INFO] (monailabel.datastore.local:577) - Invalidate count: 0
[2023-08-01 14:52:40,467] [82566] [MainThread] [INFO] (monailabel.datastore.local:151) - Start observing external modifications on datastore (AUTO RELOAD)
[2023-08-01 14:52:40,468] [82566] [MainThread] [INFO] (main:126) - +++ Adding Inferer:: segmentation => <lib.infers.segmentation.Segmentation object at 0x7fb09cd1f910>
[2023-08-01 14:52:40,468] [82566] [MainThread] [INFO] (main:191) - {'segmentation': <lib.infers.segmentation.Segmentation object at 0x7fb09cd1f910>, 'Histogram+GraphCut': <monailabel.scribbles.infer.HistogramBasedGraphCut object at 0x7fb09d17f390>, 'GMM+GraphCut': <monailabel.scribbles.infer.GMMBasedGraphCut object at 0x7fb09cd1fb10>}
[2023-08-01 14:52:40,468] [82566] [MainThread] [INFO] (main:206) - +++ Adding Trainer:: segmentation => <lib.trainers.segmentation.Segmentation object at 0x7fb09cd30390>
[2023-08-01 14:52:40,468] [82566] [MainThread] [INFO] (monailabel.utils.sessions:51) - Session Path: /home/monai/.cache/monailabel/sessions
[2023-08-01 14:52:40,468] [82566] [MainThread] [INFO] (monailabel.utils.sessions:52) - Session Expiry (max): 3600
[2023-08-01 14:52:40,468] [82566] [MainThread] [INFO] (monailabel.interfaces.app:468) - App Init - completed
[2023-08-01 14:52:40,468] [timeloop] [INFO] Starting Timeloop..
[2023-08-01 14:52:40,468] [82566] [MainThread] [INFO] (timeloop:60) - Starting Timeloop..
[2023-08-01 14:52:40,469] [timeloop] [INFO] Registered job <function MONAILabelApp.on_init_complete.<locals>.run_scheduler at 0x7fb09cd21830>
[2023-08-01 14:52:40,469] [82566] [MainThread] [INFO] (timeloop:42) - Registered job <function MONAILabelApp.on_init_complete.<locals>.run_scheduler at 0x7fb09cd21830>
[2023-08-01 14:52:40,469] [timeloop] [INFO] Timeloop now started. Jobs will run based on the interval set
[2023-08-01 14:52:40,469] [82566] [MainThread] [INFO] (timeloop:63) - Timeloop now started. Jobs will run based on the interval set
[2023-08-01 14:52:40,469] [82566] [MainThread] [INFO] (uvicorn.error:59) - Application startup complete.
[2023-08-01 14:52:40,469] [82566] [MainThread] [INFO] (uvicorn.error:211) - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

**To Reproduce**
Os : Mint21, browser : chrome/firefox
1. Run commands 'monailabel start_server --app radiology --studies http://127.0.0.1:8042/dicom-web --conf models segmentation
'

**Expected behavior**
I expected the labeling gui app to start

**Screenshots**
![image](https://github.com/Project-MONAI/MONAILabel/assets/89722527/f3ea6352-8af1-4615-8e03-3b43ea22b5b0)

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
================================
Printing MONAI config...
================================
MONAI version: 1.1.0
Numpy version: 1.21.6
Pytorch version: 1.10.0+cu102
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: a2ec3752f54bfc3b40e7952234fbeb5452ed63e3
MONAI __file__: /home/monai/.local/lib/python3.7/site-packages/monai/__init__.py

Optional dependencies:
2023-08-01 15:07:32,085 - PyTorch version 1.10.0+cu102 available.
Pytorch Ignite version: 0.4.10
Nibabel version: 4.0.2
scikit-image version: 0.15.0
Pillow version: 9.5.0
Tensorboard version: 2.6.0
gdown version: 4.7.1
TorchVision version: 0.11.1+cu102
tqdm version: 4.65.0
lmdb version: 1.4.1
psutil version: 5.8.0
pandas version: 0.25.1
einops version: 0.6.1
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: 1.30.1
pynrrd version: 0.4.3

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Linux
Linux version: Linux Mint 21.2
Platform: Linux-5.15.0-76-generic-x86_64-with-debian-bookworm-sid
Processor: x86_64
Machine: x86_64
Python version: 3.7.16
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: [popenfile(path='/home/monai/.conda/envs/label/lib/libffi.so.8.1.2', fd=3, position=0, mode='r', flags=32768)]
Num physical CPUs: 8
Num logical CPUs: 16
Num usable CPUs: 16
CPU usage (%): [6.4, 7.1, 6.3, 6.3, 6.3, 7.1, 6.3, 6.3, 6.4, 6.3, 6.3, 7.1, 7.1, 5.5, 7.1, 100.0]
CPU freq. (MHz): 4050
Load avg. in last 1, 5, 15 mins (%): [1.0, 1.9, 2.2]
Disk usage (%): 27.1
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 94.2
Available memory (GB): 85.6
Used memory (GB): 7.5

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 10.2
cuDNN enabled: True
cuDNN version: 7605
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_70']
GPU 0 Name: NVIDIA GeForce GTX 1080 Ti
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 28
GPU 0 Total memory (GB): 10.9
GPU 0 CUDA capability (maj.min): 6.1

```

**Additional context**
NONE

**Comment by diazandr3s** [comment]
Hi @raghavzns,

Thanks for opening this issue.
The OHIF viewer is available at http://0.0.0.0:8000/ohif 
You could also use 3D Slicer for this. Just installed 3D Slicer and the MONAI Label plugin. More details here: https://youtu.be/KjwuFx0pTXU

Hope this helps,

**Comment by raghavzns** [comment]
Now i can see a black screen and this is the error log in chrome/mozilla

:8000/ohif/third_party/workbox/workbox-v5.1.4/workbox-window.dev.mjs:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
vendors~app.bundle.657e2cde54a5e7335512.js:2 Cornerstone Tools
vendors~app.bundle.657e2cde54a5e7335512.js:2 run localStorage.setItem("debug", "cornerstoneTools") to see console output
vendors~app.bundle.657e2cde54a5e7335512.js:2 The provided colorLUT only provides 0 labels, whereas segmentsPerLabelmap is set to 65535. Autogenerating the rest.
(anonymous) @ vendors~app.bundle.657e2cde54a5e7335512.js:2
app.bundle.2bc1cb175d40cd215f52.js:1 New 'CornerstoneTools@4' source added.
app.bundle.2bc1cb175d40cd215f52.js:1 New measurement mapping added to source 'CornerstoneTools@4'.
vendors~app.bundle.657e2cde54a5e7335512.js:2 Brush has already been added globally
c @ vendors~app.bundle.657e2cde54a5e7335512.js:2
vendors~app.bundle.657e2cde54a5e7335512.js:2 SphericalBrush has already been added globally
c @ vendors~app.bundle.657e2cde54a5e7335512.js:2
vendors~app.bundle.657e2cde54a5e7335512.js:2 CorrectionScissors has already been added globally
c @ vendors~app.bundle.657e2cde54a5e7335512.js:2
vendors~app.bundle.657e2cde54a5e7335512.js:2 BrushEraser has already been added globally
c @ vendors~app.bundle.657e2cde54a5e7335512.js:2
app.bundle.2bc1cb175d40cd215f52.js:1 Binding incrementActiveViewport to right
app.bundle.2bc1cb175d40cd215f52.js:1 Binding decrementActiveViewport to left
app.bundle.2bc1cb175d40cd215f52.js:1 Binding rotateViewportCW to r
app.bundle.2bc1cb175d40cd215f52.js:1 Binding rotateViewportCCW to l
app.bundle.2bc1cb175d40cd215f52.js:1 Binding invertViewport to i
app.bundle.2bc1cb175d40cd215f52.js:1 Binding flipViewportVertical to h
app.bundle.2bc1cb175d40cd215f52.js:1 Binding flipViewportHorizontal to v
app.bundle.2bc1cb175d40cd215f52.js:1 Binding scaleUpViewport to +
app.bundle.2bc1cb175d40cd215f52.js:1 Binding scaleDownViewport to -
app.bundle.2bc1cb175d40cd215f52.js:1 Binding fitViewportToWindow to =
app.bundle.2bc1cb175d40cd215f52.js:1 Binding resetViewport to space
app.bundle.2bc1cb175d40cd215f52.js:1 Binding nextImage to down
app.bundle.2bc1cb175d40cd215f52.js:1 Binding previousImage to up
app.bundle.2bc1cb175d40cd215f52.js:1 Binding previousViewportDisplaySet to pagedown
app.bundle.2bc1cb175d40cd215f52.js:1 Binding nextViewportDisplaySet to pageup
app.bundle.2bc1cb175d40cd215f52.js:1 Binding setZoomTool to z
app.bundle.2bc1cb175d40cd215f52.js:1 Binding windowLevelPreset1 to 1
app.bundle.2bc1cb175d40cd215f52.js:1 Binding windowLevelPreset2 to 2
app.bundle.2bc1cb175d40cd215f52.js:1 Binding windowLevelPreset3 to 3
app.bundle.2bc1cb175d40cd215f52.js:1 Binding windowLevelPreset4 to 4
app.bundle.2bc1cb175d40cd215f52.js:1 Binding windowLevelPreset5 to 5
app.bundle.2bc1cb175d40cd215f52.js:1 Binding windowLevelPreset6 to 6
app.bundle.2bc1cb175d40cd215f52.js:1 Binding windowLevelPreset7 to 7
app.bundle.2bc1cb175d40cd215f52.js:1 Binding windowLevelPreset8 to 8
app.bundle.2bc1cb175d40cd215f52.js:1 Binding windowLevelPreset9 to 9
vendors~app.bundle.657e2cde54a5e7335512.js:2 search for studies
:8000/proxy/dicom/qido/studies?limit=25&offset=0&fuzzymatching=true&includefield=00081030%2C00080060:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
vendors~app.bundle.657e2cde54a5e7335512.js:2 request failed:  XMLHttpRequest
u.onreadystatechange @ vendors~app.bundle.657e2cde54a5e7335512.js:2
vendors~app.bundle.657e2cde54a5e7335512.js:2 Error: request failed
    at u.onreadystatechange (vendors~app.bundle.657e2cde54a5e7335512.js:2:1832926)
    at t.attempt.e.onreadystatechange (app.bundle.2bc1cb175d40cd215f52.js:1:255529)
u.onreadystatechange @ vendors~app.bundle.657e2cde54a5e7335512.js:2
vendors~app.bundle.657e2cde54a5e7335512.js:2 null
u.onreadystatechange @ vendors~app.bundle.657e2cde54a5e7335512.js:2
StudyListRouting.bundle.b30f39eee529cb3f4401.js:1 Error: request failed
    at u.onreadystatechange (vendors~app.bundle.657e2cde54a5e7335512.js:2:1832926)
    at t.attempt.e.onreadystatechange (app.bundle.2bc1cb175d40cd215f52.js:1:255529)
(anonymous) @ StudyListRouting.bundle.b30f39eee529cb3f4401.js:1
app.bundle.2bc1cb175d40cd215f52.js:1 Requesting /proxy/dicom/qido/studies?limit=25&offset=0&fuzzymatching=true&includefield=00081030%2C00080060... (attempt: 2)
(anonymous) @ app.bundle.2bc1cb175d40cd215f52.js:1
StudyListRouting.bundle.b30f39eee529cb3f4401.js:1 Error: request failed
    at u.onreadystatechange (vendors~app.bundle.657e2cde54a5e7335512.js:2:1832926)
    at t.attempt.e.onreadystatechange (app.bundle.2bc1cb175d40cd215f52.js:1:255529)
(anonymous) @ StudyListRouting.bundle.b30f39eee529cb3f4401.js:1
app.bundle.2bc1cb175d40cd215f52.js:1 Requesting /proxy/dicom/qido/studies?limit=25&offset=0&fuzzymatching=true&includefield=00081030%2C00080060... (attempt: 3)
(anonymous) @ app.bundle.2bc1cb175d40cd215f52.js:1
(anonymous) @ vendors~app.bundle.657e2cde54a5e7335512.js:2
app.bundle.2bc1cb175d40cd215f52.js:1 Requesting /proxy/dicom/qido/studies?limit=25&offset=0&fuzzymatching=true&includefield=00081030%2C00080060... (attempt: 4)
(anonymous) @ app.bundle.2bc1cb175d40cd215f52.js:1
(anonymous) @ vendors~app.bundle.657e2cde54a5e7335512.js:2

**Comment by diazandr3s** [comment]
Sorry, did you check that the DICOMWeb (i.e. Orthanc) is up and running? Please check what you see in this IP: http://127.0.0.1:8042/

I suspect the issue comes from there. You should install and start Orthanc. Then upload DICOM images to annotate.

More information here: https://github.com/Project-MONAI/MONAILabel/tree/main/plugins/ohif#installing-orthanc-dicomweb

**Comment by diazandr3s** [comment]
This schema may help to understand the MONAI Label architecture: https://youtu.be/KtPE8m0LvcQ?t=235

**Comment by tangy5** [comment]
There are two part when using monailabel, monailabel start server command is for setup the server. You will need viewers, slicer, OHIF, etc to start annotation. Here are a few tutorials: https://github.com/Project-MONAI/tutorials/blob/main/monailabel/monailabel_HelloWorld_radiology_3dslicer.ipynb

Thanks for the issue and question. Let me convert this conversation to discussion panel and we can catch up there.
