### ISSUE TITLE
Monai Label for QuPAth not compatible with QuPAth 0.5.x

### ISSUE THREAD

**Issue by lacan** [Project-MONAI/MONAILabel#1694]
Here is the error log when instaling the extension into QuPath 0.5.1

```
Error loading extension qupath.lib.extension.monailabel.Extension@46956954: qupath/lib/gui/ActionTools
java.lang.NoClassDefFoundError: qupath/lib/gui/ActionTools
	at qupath.lib.extension.monailabel.Extension.installExtension(Extension.java:44)
	at qupath.lib.gui.ExtensionManager.refreshExtensions(ExtensionManager.java:148)
	at qupath.lib.gui.ExtensionManager.promptToCopyFilesToExtensionsDirectory(ExtensionManager.java:261)
	at qupath.lib.gui.viewer.DragDropImportListener.handleFileDropImpl(DragDropImportListener.java:334)
	at qupath.lib.gui.viewer.DragDropImportListener.handleFileDrop(DragDropImportListener.java:286)
	at qupath.lib.gui.viewer.DragDropImportListener.lambda$handle$0(DragDropImportListener.java:196)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: qupath.lib.gui.ActionTools
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 13 more
```

**Comment by SachidanandAlle** [comment]
very likely not compatible... try older qpath version only

https://github.com/qupath/qupath/releases/tag/v0.4.4
or
https://github.com/qupath/qupath/releases/tag/v0.3.2

**Comment by lemonsoda174** [comment]
has there been any updates on how to use this? if there is, would you mind sharing it? 
i'm stuck at the same issue. thanks!

**Comment by diazandr3s** [comment]
Hi @lemonsoda174,

Have you tried using version 0.4.4? Could you please share the logs you're getting?

**Comment by lemonsoda174** [comment]
Hi @diazandr3s,

I have had success with integrating the extension into version 0.4.4. However, I was just wondering if it could also be done with newer versions. I have been using version 0.5.1 and have installed other dependencies, which would be quite tiresome to just switch to an older version (0.4.4) and lose all of my pre-set configurations. 

Thanks for your reply!

**Comment by SachidanandAlle** [comment]
there are interface changes between 0.5 vs 0.4.  the code /classes are not compatible.  someone has to migrate the code for plugin to use based on 0.5 interfaces/classes. if tutorial is saying u can use 0.5 then it's wrong and needs to be fixed.  without plugin changes, it's not possible to use qupath 0.5+

**Comment by SachidanandAlle** [comment]
looking for some contributors to take care of this migration.  
please raise the PR.

**Comment by psobolewskiPhD** [comment]
FYI 0.6.0 of QuPath is just around the corner (they are on rc3).

**Comment by lemonsoda174** [comment]
Looking forward to new updates. I'm now encountering some lag issues on the older version which is compatible with MONAI-Label (QuPath 0.4.4). 

Hopefully new updates on MONAI-Label for compatibility with QuPath 0.5.x will be here soon
