### ISSUE TITLE
Unable to download prostate_mri_anatomy model

### ISSUE THREAD

**Issue by rjkowalski** [Project-MONAI/MONAILabel#1712]
**Describe the bug**
Download fails for the 'prostate_mri_anatomy' model when trying to start the MONAI Label server.  There is a "None" string present in the download URL.  I am starting MONAI Label server from a Dockerfile as follows:

FROM nvcr.io/nvidia/clara/monai-toolkit:2.0
# Add RUN command to download radiology app to /workspace/apps
RUN monailabel apps --name monaibundle --download --output apps
CMD ["monailabel", "start_server", "--app=apps/monaibundle", "--studies=/workspace/dataset", "--conf models prostate_mri_anatomy"]

**Server logs**
Using PYTHONPATH=/usr:
 
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: version = False
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: app = /opt/toolkit/apps/monaibundle
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: studies = /workspace/dataset
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: verbose = INFO
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: conf = [['models', 'prostate_mri_anatomy']]
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: host = 0.0.0.0
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: port = 8000
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: uvicorn_app = monailabel.app:app
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: ssl_keyfile = None
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: ssl_certfile = None
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: ssl_keyfile_password = None
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: ssl_ca_certs = None
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: workers = None
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: limit_concurrency = None
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: access_log = False
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: root_path =
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: log_level = info
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: log_config = None
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: dryrun = False
[2024-06-26 12:45:54,314] [1] [MainThread] [INFO] (__main__:285) - USING:: action = start_server
[2024-06-26 12:45:54,315] [1] [MainThread] [INFO] (__main__:296) -
[2024-06-26 12:45:55,172] [1] [MainThread] [INFO] (uvicorn.error:82) - Started server process [1]
[2024-06-26 12:45:55,172] [1] [MainThread] [INFO] (uvicorn.error:48) - Waiting for application startup.
[2024-06-26 12:45:55,173] [1] [MainThread] [INFO] (monailabel.interfaces.utils.app:37) - Initializing App from: /opt/toolkit/apps/monaibundle; studies: /workspace/dataset; conf: {'models': 'prostate_mri_anatomy'}
[2024-06-26 12:45:55,214] [1] [MainThread] [INFO] (monailabel.utils.others.class_utils:57) - Subclass for MONAILabelApp Found: <class 'main.MyApp'>
[2024-06-26 12:45:55,214] [1] [MainThread] [INFO] (monailabel.utils.others.generic:351) - +++ Adding Bundle from NGC: prostate_mri_anatomy => /opt/toolkit/apps/monaibundle/model/prostate_mri_anatomy
Allow Origins: ['*']
App Init...
2024-06-26 12:45:55,214 - INFO - --- input summary of monai.bundle.scripts.download ---
2024-06-26 12:45:55,214 - INFO - > name: 'prostate_mri_anatomy'
2024-06-26 12:45:55,214 - INFO - > bundle_dir: '/opt/toolkit/apps/monaibundle/model'
2024-06-26 12:45:55,215 - INFO - > source: 'ngc'
2024-06-26 12:45:55,215 - INFO - > remove_prefix: 'monai_'
2024-06-26 12:45:55,215 - INFO - > progress: True
2024-06-26 12:45:55,215 - INFO - ---
 
 
monai_prostate_mri_anatomy_vNone.zip: 0.00B [00:00, ?B/s]
2024-06-26 12:45:55,883 - ERROR - Download failed from [https://api.ngc.nvidia.com/v2/models/nvidia/monaitoolkit/monai_prostate_mri_anatomy/versions/None/zip](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.ngc.nvidia.com%2Fv2%2Fmodels%2Fnvidia%2Fmonaitoolkit%2Fmonai_prostate_mri_anatomy%2Fversions%2FNone%2Fzip&data=05%7C02%7CRichard.Kowalski%40nshealth.ca%7C977f802bd74e4b6684ff08dc96bca45a%7C8eb23313ce754345a56a297a2412b4db%7C0%7C0%7C638550984186771211%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=AwUs4uDWM9bzEpSoaslRv9zF1KkJ0B9ylBKFLHJA3eg%3D&reserved=0) to /tmp/tmptg58m84r/monai_prostate_mri_anatomy_vNone.zip.
[2024-06-26 12:45:55,887] [1] [MainThread] [ERROR] (uvicorn.error:121) - Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/monailabel/app.py", line 49, in lifespan
    instance = app_instance()
  File "/usr/local/lib/python3.10/dist-packages/monailabel/interfaces/utils/app.py", line 50, in app_instance
    app = c(app_dir=app_dir, studies=studies, conf=conf)
  File "/opt/toolkit/apps/monaibundle/main.py", line 36, in __init__
    self.models = get_bundle_models(app_dir, conf)
  File "/usr/local/lib/python3.10/dist-packages/monailabel/utils/others/generic.py", line 360, in get_bundle_models
    download(name=name, version=version, bundle_dir=model_dir, source=zoo_source)
  File "/usr/local/lib/python3.10/dist-packages/monai/bundle/scripts.py", line 390, in download
    _download_from_ngc(
  File "/usr/local/lib/python3.10/dist-packages/monai/bundle/scripts.py", line 218, in _download_from_ngc
    download_url(url=url, filepath=filepath, hash_val=None, progress=progress)
  File "/usr/local/lib/python3.10/dist-packages/monai/apps/utils.py", line 226, in download_url
    _download_with_progress(url, tmp_name, progress=progress)
  File "/usr/local/lib/python3.10/dist-packages/monai/apps/utils.py", line 119, in _download_with_progress
    raise e
  File "/usr/local/lib/python3.10/dist-packages/monai/apps/utils.py", line 112, in _download_with_progress
    urlretrieve(url, filepath, reporthook=t.update_to)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
 
[2024-06-26 12:45:55,887] [1] [MainThread] [ERROR] (uvicorn.error:59) - Application startup failed. Exiting.

**To Reproduce**
1. Run the Dockerfile listed above with a prostate MRI dataset mounted to /workspace/dataset

**Expected behavior**
prostate_mri_anatomy model downloads and MONAI Label server starts normally.

**Screenshots**
N/A

**Comment by diazandr3s** [comment]
Hi @rjkowalski,

Thanks for reporting this.

Can you please manually download the bundle and then start monailabel poitning to the local bundle? I'd like to rule out a potential issue in MONAI Label.

Please let us know,

**Comment by rjkowalski** [comment]
Hi @diazandr3s - sure, I can do that.  I have downloaded the 'prostate_mri_anatomy' model and will copy the files into /opt/toolkit/apps/monaibundle/model.  How would I start the MONAI Label server and point to this local bundle?  Currently, my Dockerfile uses: CMD ["monailabel", "start_server", "--app=apps/monaibundle", "--studies=/workspace/dataset", "--conf models prostate_mri_anatomy"]

Would I just exclude the "--conf models prostate_mri_anatomy" piece?

**Comment by diazandr3s** [comment]
Hi @rjkowalski,

I think you can still use the same command. MONAI Label will just skip the downloading part as it is already in the model folder.

Let us know,

**Comment by rjkowalski** [comment]
Hi @diazandr3s - It looks like MONAI Label does not skip the downloading step.  See below.

[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: version = False
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: app = /opt/toolkit/apps/monaibundle
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: studies = /workspace/dataset
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: verbose = INFO
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: conf = [['models', 'prostate_mri_anatomy']]
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: host = 0.0.0.0
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: port = 8000
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: uvicorn_app = monailabel.app:app
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: ssl_keyfile = None
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: ssl_certfile = None
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: ssl_keyfile_password = None
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: ssl_ca_certs = None
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: workers = None
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: limit_concurrency = None
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: access_log = False
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: root_path =
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: log_level = info
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: log_config = None
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: dryrun = False
[2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (__main__:285) - USING:: action = start_server
[2024-07-08 16:41:32,061] [1] [MainThread] [INFO] (__main__:296) -
[2024-07-08 16:41:32,873] [1] [MainThread] [INFO] (uvicorn.error:82) - Started server process [1]
[2024-07-08 16:41:32,873] [1] [MainThread] [INFO] (uvicorn.error:48) - Waiting for application startup.
[2024-07-08 16:41:32,873] [1] [MainThread] [INFO] (monailabel.interfaces.utils.app:37) - Initializing App from: /opt/toolkit/apps/monaibundle; studies: /workspace/dataset; conf: {'models': 'prostate_mri_anatomy'}
[2024-07-08 16:41:32,908] [1] [MainThread] [INFO] (monailabel.utils.others.class_utils:57) - Subclass for MONAILabelApp Found: <class 'main.MyApp'>
[2024-07-08 16:41:32,908] [1] [MainThread] [INFO] (monailabel.utils.others.generic:351) - +++ Adding Bundle from NGC: prostate_mri_anatomy => /opt/toolkit/apps/monaibundle/model/prostate_mri_anatomy
Allow Origins: ['*']
App Init...
2024-07-08 16:41:32,908 - INFO - --- input summary of monai.bundle.scripts.download ---
2024-07-08 16:41:32,908 - INFO - > name: 'prostate_mri_anatomy'
2024-07-08 16:41:32,908 - INFO - > bundle_dir: '/opt/toolkit/apps/monaibundle/model'
2024-07-08 16:41:32,908 - INFO - > source: 'ngc'
2024-07-08 16:41:32,908 - INFO - > remove_prefix: 'monai_'
2024-07-08 16:41:32,909 - INFO - > progress: True
2024-07-08 16:41:32,909 - INFO - ---


monai_prostate_mri_anatomy_vNone.zip: 0.00B [00:00, ?B/s]
2024-07-08 16:41:34,287 - ERROR - Download failed from https://api.ngc.nvidia.com/v2/models/nvidia/monaitoolkit/monai_prostate_mri_anatomy/versions/None/zip to /tmp/tmpgovlum6h/monai_prostate_mri_anatomy_vNone.zip.
[2024-07-08 16:41:34,291] [1] [MainThread] [ERROR] (uvicorn.error:121) - Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/monailabel/app.py", line 49, in lifespan
    instance = app_instance()
  File "/usr/local/lib/python3.10/dist-packages/monailabel/interfaces/utils/app.py", line 50, in app_instance
    app = c(app_dir=app_dir, studies=studies, conf=conf)
  File "/opt/toolkit/apps/monaibundle/main.py", line 36, in __init__
    self.models = get_bundle_models(app_dir, conf)
  File "/usr/local/lib/python3.10/dist-packages/monailabel/utils/others/generic.py", line 360, in get_bundle_models
    download(name=name, version=version, bundle_dir=model_dir, source=zoo_source)
  File "/usr/local/lib/python3.10/dist-packages/monai/bundle/scripts.py", line 390, in download
    _download_from_ngc(
  File "/usr/local/lib/python3.10/dist-packages/monai/bundle/scripts.py", line 218, in _download_from_ngc
    download_url(url=url, filepath=filepath, hash_val=None, progress=progress)
  File "/usr/local/lib/python3.10/dist-packages/monai/apps/utils.py", line 226, in download_url
    _download_with_progress(url, tmp_name, progress=progress)
  File "/usr/local/lib/python3.10/dist-packages/monai/apps/utils.py", line 119, in _download_with_progress
    raise e
  File "/usr/local/lib/python3.10/dist-packages/monai/apps/utils.py", line 112, in _download_with_progress
    urlretrieve(url, filepath, reporthook=t.update_to)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[2024-07-08 16:41:34,291] [1] [MainThread] [ERROR] (uvicorn.error:59) - Application startup failed. Exiting.
exit code: 3

**Comment by diazandr3s** [comment]
> Hi @diazandr3s - It looks like MONAI Label does not skip the downloading step. See below.
> 
> [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: version = False [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: app = /opt/toolkit/apps/monaibundle [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: studies = /workspace/dataset [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: verbose = INFO [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: conf = [['models', 'prostate_mri_anatomy']] [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: host = 0.0.0.0 [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: port = 8000 [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: uvicorn_app = monailabel.app:app [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: ssl_keyfile = None [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: ssl_certfile = None [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: ssl_keyfile_password = None [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: ssl_ca_certs = None [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: workers = None [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: limit_concurrency = None [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: access_log = False [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: root_path = [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: log_level = info [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: log_config = None [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: dryrun = False [2024-07-08 16:41:32,060] [1] [MainThread] [INFO] (**main**:285) - USING:: action = start_server [2024-07-08 16:41:32,061] [1] [MainThread] [INFO] (**main**:296) - [2024-07-08 16:41:32,873] [1] [MainThread] [INFO] (uvicorn.error:82) - Started server process [1] [2024-07-08 16:41:32,873] [1] [MainThread] [INFO] (uvicorn.error:48) - Waiting for application startup. [2024-07-08 16:41:32,873] [1] [MainThread] [INFO] (monailabel.interfaces.utils.app:37) - Initializing App from: /opt/toolkit/apps/monaibundle; studies: /workspace/dataset; conf: {'models': 'prostate_mri_anatomy'} [2024-07-08 16:41:32,908] [1] [MainThread] [INFO] (monailabel.utils.others.class_utils:57) - Subclass for MONAILabelApp Found: <class 'main.MyApp'> [2024-07-08 16:41:32,908] [1] [MainThread] [INFO] (monailabel.utils.others.generic:351) - +++ Adding Bundle from NGC: prostate_mri_anatomy => /opt/toolkit/apps/monaibundle/model/prostate_mri_anatomy Allow Origins: ['*'] App Init... 2024-07-08 16:41:32,908 - INFO - --- input summary of monai.bundle.scripts.download --- 2024-07-08 16:41:32,908 - INFO - > name: 'prostate_mri_anatomy' 2024-07-08 16:41:32,908 - INFO - > bundle_dir: '/opt/toolkit/apps/monaibundle/model' 2024-07-08 16:41:32,908 - INFO - > source: 'ngc' 2024-07-08 16:41:32,908 - INFO - > remove_prefix: 'monai_' 2024-07-08 16:41:32,909 - INFO - > progress: True 2024-07-08 16:41:32,909 - INFO - ---
> 
> monai_prostate_mri_anatomy_vNone.zip: 0.00B [00:00, ?B/s] 2024-07-08 16:41:34,287 - ERROR - Download failed from https://api.ngc.nvidia.com/v2/models/nvidia/monaitoolkit/monai_prostate_mri_anatomy/versions/None/zip to /tmp/tmpgovlum6h/monai_prostate_mri_anatomy_vNone.zip. [2024-07-08 16:41:34,291] [1] [MainThread] [ERROR] (uvicorn.error:121) - Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 732, in lifespan async with self.lifespan_context(app) as maybe_state: File "/usr/lib/python3.10/contextlib.py", line 199, in **aenter** return await anext(self.gen) File "/usr/local/lib/python3.10/dist-packages/monailabel/app.py", line 49, in lifespan instance = app_instance() File "/usr/local/lib/python3.10/dist-packages/monailabel/interfaces/utils/app.py", line 50, in app_instance app = c(app_dir=app_dir, studies=studies, conf=conf) File "/opt/toolkit/apps/monaibundle/main.py", line 36, in **init** self.models = get_bundle_models(app_dir, conf) File "/usr/local/lib/python3.10/dist-packages/monailabel/utils/others/generic.py", line 360, in get_bundle_models download(name=name, version=version, bundle_dir=model_dir, source=zoo_source) File "/usr/local/lib/python3.10/dist-packages/monai/bundle/scripts.py", line 390, in download _download_from_ngc( File "/usr/local/lib/python3.10/dist-packages/monai/bundle/scripts.py", line 218, in _download_from_ngc download_url(url=url, filepath=filepath, hash_val=None, progress=progress) File "/usr/local/lib/python3.10/dist-packages/monai/apps/utils.py", line 226, in download_url _download_with_progress(url, tmp_name, progress=progress) File "/usr/local/lib/python3.10/dist-packages/monai/apps/utils.py", line 119, in _download_with_progress raise e File "/usr/local/lib/python3.10/dist-packages/monai/apps/utils.py", line 112, in _download_with_progress urlretrieve(url, filepath, reporthook=t.update_to) File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve with contextlib.closing(urlopen(url, data)) as fp: File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen return opener.open(url, data, timeout) File "/usr/lib/python3.10/urllib/request.py", line 525, in open response = meth(req, response) File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response response = self.parent.error( File "/usr/lib/python3.10/urllib/request.py", line 563, in error return self._call_chain(*args) File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain result = func(*args) File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 404: Not Found
> 
> [2024-07-08 16:41:34,291] [1] [MainThread] [ERROR] (uvicorn.error:59) - Application startup failed. Exiting. exit code: 3

Hi @rjkowalski,

This is strange. Did you decompress the bundle file?
Can you please share a print screen of the model folder?

**Comment by diazandr3s** [comment]
Thanks for the update!

**Comment by diazandr3s** [comment]
Closing issue. Please reopen if needed
