### ISSUE TITLE
ImportError: cannot import name 'appengine' from 'urllib3.contrib'

### ISSUE THREAD

**Issue by lovergos** [Project-MONAI/MONAILabel#1727]
hello,when I followed the steps and reached this step, this error occurred:
(torch) PS D:\Demo_project\Segmentation1> monailabel start_server --app apps/radiology --studies datasets/Task09_Spleen/imagesTr --conf models deepedit
Using PYTHONPATH=D:\software\miniconda3\miniconda3\envs;
[2024-07-30 13:11:24,492] [33124] [MainThread] [INFO] (__main__:269) - USING:: app = D:\Demo_project\Segmentation1\apps\radiology
[2024-07-30 13:11:24,492] [33124] [MainThread] [INFO] (__main__:269) - USING:: studies = D:\Demo_project\Segmentation1\datasets\Task09_Spleen\imagesTr
[2024-07-30 13:11:24,493] [33124] [MainThread] [INFO] (__main__:269) - USING:: verbose = INFO
[2024-07-30 13:11:24,493] [33124] [MainThread] [INFO] (__main__:269) - USING:: conf = [['models', 'deepedit']]
[2024-07-30 13:11:24,493] [33124] [MainThread] [INFO] (__main__:269) - USING:: host = 0.0.0.0
[2024-07-30 13:11:24,493] [33124] [MainThread] [INFO] (__main__:269) - USING:: port = 8000
[2024-07-30 13:11:24,493] [33124] [MainThread] [INFO] (__main__:269) - USING:: uvicorn_app = monailabel.app:app
[2024-07-30 13:11:24,494] [33124] [MainThread] [INFO] (__main__:269) - USING:: ssl_keyfile = None
[2024-07-30 13:11:24,494] [33124] [MainThread] [INFO] (__main__:269) - USING:: ssl_certfile = None
[2024-07-30 13:11:24,494] [33124] [MainThread] [INFO] (__main__:269) - USING:: ssl_keyfile_password = None
[2024-07-30 13:11:24,494] [33124] [MainThread] [INFO] (__main__:269) - USING:: ssl_ca_certs = None
[2024-07-30 13:11:24,494] [33124] [MainThread] [INFO] (__main__:269) - USING:: workers = None
[2024-07-30 13:11:24,494] [33124] [MainThread] [INFO] (__main__:269) - USING:: limit_concurrency = None
[2024-07-30 13:11:24,495] [33124] [MainThread] [INFO] (__main__:269) - USING:: access_log = False
[2024-07-30 13:11:24,495] [33124] [MainThread] [INFO] (__main__:269) - USING:: log_config = None
[2024-07-30 13:11:24,495] [33124] [MainThread] [INFO] (__main__:269) - USING:: dryrun = False
[2024-07-30 13:11:24,495] [33124] [MainThread] [INFO] (__main__:269) - USING:: action = start_server
[2024-07-30 13:11:24,495] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_API_STR =
[2024-07-30 13:11:24,496] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_PROJECT_NAME = MONAILabel
[2024-07-30 13:11:24,496] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_APP_DIR =
[2024-07-30 13:11:24,496] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_STUDIES =
[2024-07-30 13:11:24,496] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_APP_CONF = '{}'
[2024-07-30 13:11:24,496] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_TASKS_TRAIN = True
[2024-07-30 13:11:24,496] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_TASKS_STRATEGY = True
[2024-07-30 13:11:24,496] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_TASKS_SCORING = True
[2024-07-30 13:11:24,497] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_TASKS_BATCH_INFER = True
[2024-07-30 13:11:24,497] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_USERNAME =
[2024-07-30 13:11:24,497] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_PASSWORD =
[2024-07-30 13:11:24,497] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CACHE_PATH =
[2024-07-30 13:11:24,497] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_QIDO_PREFIX =
[2024-07-30 13:11:24,498] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_WADO_PREFIX =
[2024-07-30 13:11:24,498] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_STOW_PREFIX =
[2024-07-30 13:11:24,498] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_FETCH_BY_FRAME = False
[2024-07-30 13:11:24,498] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_DATASTORE_AUTO_RELOAD = True
[2024-07-30 13:11:24,498] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_DATASTORE_FILE_EXT = '["*.nii.gz", "*.nii", "*.nrrd", "*.jpg", "*.png", "*.tif", "*.svs", "*.xml"]'
[2024-07-30 13:11:24,499] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_SERVER_PORT = 8000
[2024-07-30 13:11:24,499] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_CORS_ORIGINS = '[]'
[2024-07-30 13:11:24,499] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_SESSIONS = True
[2024-07-30 13:11:24,499] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_SESSION_PATH =
[2024-07-30 13:11:24,499] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_SESSION_EXPIRY = 3600
[2024-07-30 13:11:24,499] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_INFER_CONCURRENCY = -1
[2024-07-30 13:11:24,499] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_INFER_TIMEOUT = 600
[2024-07-30 13:11:24,499] [33124] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_AUTO_UPDATE_SCORING = True
[2024-07-30 13:11:24,500] [33124] [MainThread] [INFO] (__main__:274) -
Traceback (most recent call last):
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\monailabel\main.py", line 329, in <module>
    Main().run()
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\monailabel\main.py", line 126, in run
    self.action_start_server(args)
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\monailabel\main.py", line 227, in action_start_server
    uvicorn.run(
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\uvicorn\config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\monailabel\app.py", line 23, in <module>
    from monailabel.endpoints import (
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\monailabel\endpoints\infer.py", line 24, in <module>
    from requests_toolbelt import MultipartEncoder
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\requests_toolbelt\__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\requests_toolbelt\adapters\__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\requests_toolbelt\adapters\ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\requests_toolbelt\_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (D:\software\miniconda3\miniconda3\envs\torch\lib\site-packages\urllib3\contrib\__init__.py)

**Comment by diazandr3s** [comment]
Hi @lovergos,

Thanks for sharing the logs.
This seems to be an env issue. Did you get any error when installing the MONAI Label requirements?
Could you please try again with a fresh python env?

**Comment by diazandr3s** [comment]
Thanks for letting us know. Closing issue.
