### ISSUE TITLE
Monailabel cann't run correctly in windows 11

### ISSUE THREAD

**Issue by Xu-Charles** [Project-MONAI/MONAILabel#1794]
### Discussed in https://github.com/Project-MONAI/MONAILabel/discussions/1793

<div type='discussions-op-text'>

<sup>Originally posted by **Xu-Charles** December 10, 2024</sup>
I have python 3.9.20  environment with PyTorch and CUDA installed.
cuda version :12.4

(monailabel) C:\Users\Administrator>python
Python 3.9.20 (main, Oct  3 2024, 07:38:01) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.is_available())
True

But, I get the following error when running monailabel：

(monailabel) C:\Users\Administrator>monailabel
Using PYTHONPATH=C:\ProgramData\Anaconda3\envs;
""
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\envs\monailabel\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,

File "C:\ProgramData\Anaconda3\envs\monailabel\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)

File "C:\ProgramData\Anaconda3\envs\monailabel\lib\site-packages\monailabel\main.py", line 24, in <module>
from monailabel.config import settings

File "C:\ProgramData\Anaconda3\envs\monailabel\lib\site-packages\monailabel\config.py", line 23, in <module>
class Settings(BaseSettings):

File "C:\ProgramData\Anaconda3\envs\monailabel\lib\site-packages\monailabel\config.py", line 109, in Settings
if is_package_installed("SAM-2")

File "C:\ProgramData\Anaconda3\envs\monailabel\lib\site-packages\monailabel\config.py", line 20, in is_package_installed
return name in sorted(x.name for x in distributions())

File "C:\ProgramData\Anaconda3\envs\monailabel\lib\site-packages\monailabel\config.py", line 20, in <genexpr>
return name in sorted(x.name for x in distributions())

AttributeError: 'PathDistribution' object has no attribute 'name'</div>

**Comment by lassoan** [comment]
The issue is not that you use Windows11 but that you use Python-3.9.

I have run into the same issue. The problem was easy to fix (just use get method and tweak the sorting), but then when I noticed that there were further issues (SAM is not supported on Python 3.9) then I just gave up.

The error happens when you import MONAILabel, so it seems MONAILabel is not tested at all with Python-3.9 (or the failure is ignored), so I'm not sure if MONAILabel is supported on Python-3.9.

**Comment by SachidanandAlle** [comment]
Try: `pip install importlib_metadata==8.4.0`

**Comment by SachidanandAlle** [comment]
is all good?

**Comment by lassoan** [comment]
If it helps at all, for me, with Python-3.9 MONAILabel failed on this line:

https://github.com/Project-MONAI/MONAILabel/blob/1fe0e8f373a5f7a613d511aa2ab02946c67d6c04/monailabel/config.py#L20

I've tried installing various `importlib_metadata` versions but in the end I've fixed the issue by changing the code to this:

    return name in (x.metadata.get('Name') for x in distributions())

(It seems that I removed the sorting, I don't know why, maybe that was causing some issue, too, and you probably don't really need the sorting anyway)

Since then I decided to switch to Python-3.10, so I did not investigate Python-3.9 any further.

**Comment by SachidanandAlle** [comment]
https://github.com/Project-MONAI/MONAILabel/pull/1800

**Comment by linjy66** [comment]
@lassoan Hello, prof. lassoan. I had the same problem, and based on your suggestion, I changed the corresponding code of config. py to "return name in (x.metadata.get('Name') for x in distributions())".
I had no problem when I typed in 'monailabel'. Subsequently, I downloaded the app and dataset, and the code displayed in the Anaconda Prompt is shown in the attached image. 
However, when I went into 3D Slicer, monailabel failed to carry out the automatic segmentation, and there were no Models to choose from under Auto Segmentation. If possible, I would like to ask you how I should resolve this issue. Thank you!

<img width="865" alt="Image" src="https://github.com/user-attachments/assets/21006c9b-b055-4dc9-bb47-7132b7ca5733" />

<img width="896" alt="Image" src="https://github.com/user-attachments/assets/4e15426c-d499-43c2-9706-6ba792146772" />

<img width="1160" alt="Image" src="https://github.com/user-attachments/assets/58e178fd-25b3-4290-9c84-2d7ba5cb2007" />
