### ISSUE TITLE
Errors Downloading Masks from CVAT

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#1796]
### Discussed in https://github.com/Project-MONAI/MONAILabel/discussions/1791

<div type='discussions-op-text'>

<sup>Originally posted by **bilalcodehub** December  5, 2024</sup>
Hi,

I am currently using MONAILabel with CVAT in a Docker environment, utilising the default endoscopy app for 2D segmentation of surgical images. After completing a round of annotation and marking the job as finished, I encountered the following error:

```
Can't initialize NVML
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
[2024-12-05 19:16:03,247] [1330] [MainThread] [INFO] (main:199) - +++ Adding Trainer:: tooltracking => <lib.trainers.tooltracking.ToolTracking object at 0x793bd0660040>
[2024-12-05 19:16:03,247] [1330] [MainThread] [INFO] (main:217) - +++ Adding Strategy:: tooltracking_epistemic => <monailabel.tasks.activelearning.epistemic.Epistemic object at 0x793bd068d030>
[2024-12-05 19:16:03,247] [1330] [MainThread] [INFO] (main:220) - Active Learning Strategies:: ['random', 'tooltracking_epistemic']
[2024-12-05 19:16:03,357] [1330] [MainThread] [INFO] (monailabel.tasks.infer.bundle:142) - Model: endoscopic_tool_segmentation; Type: segmentation; Label: background => 0
[2024-12-05 19:16:03,357] [1330] [MainThread] [INFO] (monailabel.tasks.infer.bundle:142) - Model: endoscopic_tool_segmentation; Type: segmentation; Label: tools => 1
[2024-12-05 19:16:03,364] [1330] [MainThread] [INFO] (main:234) - +++ Adding Scoring Method:: tooltracking_epistemic => <lib.scoring.cvat.CVATEpistemicScoring object at 0x793bd068cfd0>
[2024-12-05 19:16:03,364] [1330] [MainThread] [INFO] (main:237) - Active Learning Scoring Methods:: ['tooltracking_epistemic']
[2024-12-05 19:16:03,364] [1330] [MainThread] [INFO] (monailabel.utils.sessions:51) - Session Path: /root/.cache/monailabel/sessions
[2024-12-05 19:16:03,364] [1330] [MainThread] [INFO] (monailabel.utils.sessions:52) - Session Expiry (max): 3600
[2024-12-05 19:16:03,364] [1330] [MainThread] [INFO] (monailabel.tasks.scoring.epistemic_v2:103) - Starting Epistemic Uncertainty scoring
[2024-12-05 19:16:03,364] [1330] [MainThread] [INFO] (monailabel.tasks.scoring.epistemic_v2:118) - EPISTEMIC:: Total unlabeled images: 384; max_samples: 0
[2024-12-05 19:16:03,377] [1330] [MainThread] [INFO] (monailabel.tasks.scoring.epistemic_v2:162) - EPISTEMIC:: {'total': 384, 'skipped': 384, 'executed': 0, 'latency': 0.013}
[2024-12-05 19:16:05,931] [1330] [MainThread] [INFO] (lib.scoring.cvat:63) - Existing Task Status: completed; Scoring/Result: {'total': 384, 'skipped': 384, 'executed': 0, 'latency': 0.013}
[2024-12-05 19:16:05,932] [1330] [MainThread] [INFO] (lib.scoring.cvat:76) - Latest Active Learning Task in CVAT is under progress/not-consumed. Skip to create new!
[2024-12-05 19:16:05,932] [1330] [MainThread] [INFO] (__main__:61) - Result: {"total": 384, "skipped": 384, "executed": 0, "latency": 0.013}
[2024-12-05 19:16:06,620] [1190] [ThreadPoolExecutor-0_0] [INFO] (monailabel.utils.async_tasks.utils:83) - Return code: 0
[2024-12-05 19:17:04,063] [1190] [Thread-5] [INFO] (monailabel.datastore.cvat:190) - Preparing to download/update final labels from: 3 => 3 => ActiveLearning_Iteration_1
[2024-12-05 19:17:14,409] [1190] [Thread-5] [ERROR] (monailabel.datastore.cvat:238) - 0 => Failed to download...
[2024-12-05 19:17:24,758] [1190] [Thread-5] [ERROR] (monailabel.datastore.cvat:237) - /tmp/tmpqbjfyeyo.zip is not a zip file
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/monailabel/datastore/cvat.py", line 205, in download_from_cvat
    shutil.unpack_archive(tmp_zip, tmp_folder)
  File "/usr/lib/python3.10/shutil.py", line 1314, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "/usr/lib/python3.10/shutil.py", line 1201, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: /tmp/tmpqbjfyeyo.zip is not a zip file
[2024-12-05 19:17:24,760] [1190] [Thread-5] [ERROR] (monailabel.datastore.cvat:238) - 1 => Failed to download...
[2024-12-05 19:17:35,103] [1190] [Thread-5] [ERROR] (monailabel.datastore.cvat:237) - /tmp/tmpqbjfyeyo.zip is not a zip file
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/monailabel/datastore/cvat.py", line 205, in download_from_cvat
    shutil.unpack_archive(tmp_zip, tmp_folder)
  File "/usr/lib/python3.10/shutil.py", line 1314, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "/usr/lib/python3.10/shutil.py", line 1201, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: /tmp/tmpqbjfyeyo.zip is not a zip file
[2024-12-05 19:17:35,104] [1190] [Thread-5] [ERROR] (monailabel.datastore.cvat:238) - 2 => Failed to download...
```

It appears that the MONAILabel server is failing to download the results due to a corrupted or improperly created archive file. Could someone please guide me on how to resolve this issue?

Many thanks and 
Kind regards,
Bilal
</div>

**Comment by SachidanandAlle** [comment]
https://github.com/Project-MONAI/MONAILabel/pull/1795
