### ISSUE TITLE
Cannot Download QuPath Extension

### ISSUE THREAD

**Issue by abadgerw** [Project-MONAI/MONAILabel#1798]
I am following the following tutorial: https://github.com/Project-MONAI/tutorials/blob/main/monailabel/monailabel_pathology_nuclei_segmentation_QuPath.ipynb

I have an Apple M1 Pro and successfully created an anaconda environment and installed monailabel and the pathology app. However, when I download QuPath 0.5.0 and then place the .jar file in the running instance I get the following error:

11:53:19.708	[JavaFX Application Thread]	ERROR	qupath.lib.gui.ExtensionManager	Error loading extension qupath.lib.extension.monailabel.Extension@52ad2a2b: qupath/lib/gui/ActionTools	java.lang.NoClassDefFoundError: qupath/lib/gui/ActionTools
	at qupath.lib.extension.monailabel.Extension.installExtension(Extension.java:57)
	at qupath.lib.gui.ExtensionManager.refreshExtensions(ExtensionManager.java:148)
	at qupath.lib.gui.ExtensionManager.promptToCopyFilesToExtensionsDirectory(ExtensionManager.java:261)
	at qupath.lib.gui.viewer.DragDropImportListener.handleFileDropImpl(DragDropImportListener.java:334)
	at qupath.lib.gui.viewer.DragDropImportListener.handleFileDrop(DragDropImportListener.java:286)
	at qupath.lib.gui.viewer.DragDropImportListener.lambda$handle$0(DragDropImportListener.java:196)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: java.lang.ClassNotFoundException: qupath.lib.gui.ActionTools
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 10 more

Any insight into how to address this?

**Comment by SachidanandAlle** [comment]
It's compatible only with 4.x version or below of qupath.  u might be using latest qupath.
https://github.com/qupath/qupath/releases/tag/v0.4.4

**Comment by abadgerw** [comment]
Thank you @SachidanandAlle! The tutorial said one can use qupath 0.5.0 or below so I was using 0.5.0. However, when I switched down to 0.4.4 it worked.

**Comment by SachidanandAlle** [comment]
possibly the document/tutorial is wrong.  needs to mention explicitly.  
need some help from somebody who knows qupath/community to migrate to latest version.  there are lots of breaking changes in the latest qupath 5.x+ version for plugin development.
