### ISSUE TITLE
failed  to save Label to MONAI Label Server

### ISSUE THREAD

**Issue by blacksino** [Project-MONAI/MONAILabel#260]
Traceback (most recent call last):
  File "/home/SENSETIME/xulixin2/Slicer-4.13.0-2021-08-03-linux-amd64/NA-MIC/Extensions-30092/MONAILabel/lib/Slicer-4.13/qt-scripted-modules/MONAILabel.py", line 980, in onSaveLabel
    result = self.logic.save_label(self.current_sample["id"], label_in)
  File "/home/SENSETIME/xulixin2/Slicer-4.13.0-2021-08-03-linux-amd64/NA-MIC/Extensions-30092/MONAILabel/lib/Slicer-4.13/qt-scripted-modules/MONAILabel.py", line 1302, in save_label
    return MONAILabelClient(self.server_url, self.tmpdir).save_label(image_in, label_in)
  File "/home/SENSETIME/xulixin2/Slicer-4.13.0-2021-08-03-linux-amd64/NA-MIC/Extensions-30092/MONAILabel/lib/Slicer-4.13/qt-scripted-modules/client.py", line 75, in save_label
    status, response, _ = MONAILabelUtils.http_multipart("PUT", self._server_url, selector, fields, files)
  File "/home/SENSETIME/xulixin2/Slicer-4.13.0-2021-08-03-linux-amd64/NA-MIC/Extensions-30092/MONAILabel/lib/Slicer-4.13/qt-scripted-modules/client.py", line 192, in http_multipart
    content_type, body = MONAILabelUtils.encode_multipart_formdata(fields, files)
  File "/home/SENSETIME/xulixin2/Slicer-4.13.0-2021-08-03-linux-amd64/NA-MIC/Extensions-30092/MONAILabel/lib/Slicer-4.13/qt-scripted-modules/client.py", line 260, in encode_multipart_formdata
    with open(filename, mode="rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/Slicer-SENSETIME\\xulixin2/slicer-monai-label2021-08-05_14+19+35.457/tmpqlk_1wlb.nii.gz'

**Comment by nikgiannotti** [comment]
I do get a similar issue after performing the segmentation, is anyone able to solve this or point me in the right direction)?

See message error below:
Traceback (most recent call last):
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/NA-MIC/Extensions-31382/MONAILabel/lib/Slicer-5.2/qt-scripted-modules/MONAILabel.py", line 1465, in onSaveLabel
    result = self.logic.save_label(self.current_sample["id"], label_in, {"label_info": label_info})
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/NA-MIC/Extensions-31382/MONAILabel/lib/Slicer-5.2/qt-scripted-modules/MONAILabel.py", line 2285, in save_label
    return self._client().save_label(image_in, label_in, params=params)
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/NA-MIC/Extensions-31382/MONAILabel/lib/Slicer-5.2/qt-scripted-modules/MONAILabel.py", line 2237, in _client
    if mc.auth_enabled():
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/NA-MIC/Extensions-31382/MONAILabel/lib/Slicer-5.2/qt-scripted-modules/MONAILabelLib/client.py", line 83, in auth_enabled
    status, response, _, _ = MONAILabelUtils.http_method("GET", self._server_url, selector)
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/NA-MIC/Extensions-31382/MONAILabel/lib/Slicer-5.2/qt-scripted-modules/MONAILabelLib/client.py", line 521, in http_method
    conn.request(method, selector, body=body, headers=headers)
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/http/client.py", line 946, in connect
    self.sock = self._create_connection(
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/home/ubuntu/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
