### ISSUE TITLE
Scribbles - SimpleCRF compilation fails on Windows machine

### ISSUE THREAD

**Issue by masadcv** [Project-MONAI/MONAILabel#363]
The external dependency SimpleCRF at: https://github.com/HiLab-git/SimpleCRF is needed to run the GraphCut optimisation in Scribbles methods. 

Currently its compilation/installation is failing on Windows. There is a quick fix for this in SimpleCRF's branch that has been submitted as PR at: https://github.com/HiLab-git/SimpleCRF/pull/5

Going forward there could be two solutions to have this working in our current release:
- Plan A: Wait for the changes to be merged into SimpleCRF repo. Then add `pip install SimpleCRF` to requirements.txt for individual app/monailabel module. 
- Plan B: If changes to SimpleCRF are not merged in time, then we could temporarily add `pip install git+https://github.com/masadcv/SimpleCRF.git@fix-windows-error` to requirements.txt for our release.

**Comment by masadcv** [comment]
Addressed through Plan B via https://github.com/Project-MONAI/MONAILabel/pull/367

**Comment by taigw** [comment]
@masadcv Thanks for your effort. I have merged your commit.

**Comment by masadcv** [comment]
@taigw many thanks for merging this. There were some additional dependency issue when building simplecrf for python3.6 on some integration machines. I have another PR that fixes these.

**Comment by ralkalay** [comment]
Hi, I am trying to install monilabel on a AMD pro windows workstation and coming up with this error, can any one help.  Thanks, Ron

Building wheels for collected packages: simplecrf, gdown
  Building wheel for simplecrf (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Conda\envs\monailabel_env\python.exe' 'C:\Users\Conda\envs\monailabel_env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\RONALK~1\AppData\Local\Temp\tmpfv7lvq6i'
       cwd: C:\Users\Ron Alkalay\AppData\Local\Temp\pip-install-7i6lbq1t\simplecrf_ac5abd2060964fc39480b213ed85e2e2
  Complete output (4 lines):
  running bdist_wheel
  running build
  running build_ext
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for simplecrf
  Building wheel for gdown (PEP 517) ... done
  Created wheel for gdown: filename=gdown-4.2.0-py3-none-any.whl size=14262 sha256=177a74804ba3cb02c0ce0228153a633674c7e0ce0c690f491830419021e117d4
  Stored in directory: c:\users\ron alkalay\appdata\local\pip\cache\wheels\2b\3c\51\52c46deda5cd1d59c6ce3d441ea5f3d155495dc294c4535a25
Successfully built gdown
Failed to build simplecrf
ERROR: Could not build wheels for simplecrf which use PEP 517 and cannot be installed directly

I tried removing simpleCRF from the requirement file, and the error did not appear, however monai label needs the following library 

[2022-01-24 13:58:00,426] [12836] [MainThread] [INFO] (__main__:277) - USING:: studies = D:\Monai-datasets\Datasets\Task09_Spleen\Task09_Spleen
[2022-01-24 13:58:00,427] [12836] [MainThread] [INFO] (__main__:277) - USING:: debug = False
[2022-01-24 13:58:00,429] [12836] [MainThread] [INFO] (__main__:277) - USING:: conf = None
[2022-01-24 13:58:00,430] [12836] [MainThread] [INFO] (__main__:277) - USING:: host = 0.0.0.0
[2022-01-24 13:58:00,430] [12836] [MainThread] [INFO] (__main__:277) - USING:: port = 8000
[2022-01-24 13:58:00,431] [12836] [MainThread] [INFO] (__main__:277) - USING:: log_config = None
[2022-01-24 13:58:00,431] [12836] [MainThread] [INFO] (__main__:277) - USING:: dryrun = False
[2022-01-24 13:58:00,432] [12836] [MainThread] [INFO] (__main__:277) - USING:: action = start_server
[2022-01-24 13:58:00,432] [12836] [MainThread] [INFO] (__main__:278) -
[2022-01-24 13:58:51,657] [12836] [MainThread] [INFO] (uvicorn.error:64) - Started server process [12836]
[2022-01-24 13:58:51,658] [12836] [MainThread] [INFO] (uvicorn.error:26) - Waiting for application startup.
[2022-01-24 13:58:51,659] [12836] [MainThread] [INFO] (monailabel.interfaces.utils.app:38) - Initializing App from: D:\Monai-datasets\MONAILabel\sample-apps\deepedit; studies: D:\Monai-datasets\Datasets\Task09_Spleen\Task09_Spleen; conf: {}
[2022-01-24 13:58:51,700] [12836] [MainThread] [ERROR] (uvicorn.error:89) - Traceback (most recent call last):
  File "C:\Users\Conda\envs\monailabel_env\lib\site-packages\starlette\routing.py", line 540, in lifespan
    async for item in self.lifespan_context(app):
  File "C:\Users\Conda\envs\monailabel_env\lib\site-packages\starlette\routing.py", line 481, in default_lifespan
    await self.startup()
  File "C:\Users\Conda\envs\monailabel_env\lib\site-packages\starlette\routing.py", line 516, in startup
    await handler()
  File "D:\Monai-datasets\MONAILabel\monailabel\app.py", line 99, in startup_event
    instance = app_instance()
  File "D:\Monai-datasets\MONAILabel\monailabel\interfaces\utils\app.py", line 44, in app_instance
    c = get_class_of_subclass_from_file("main", main_py, "MONAILabelApp")
  File "D:\Monai-datasets\MONAILabel\monailabel\utils\others\class_utils.py", line 53, in get_class_of_subclass_from_file
    return get_class_of_subclass(module_from_file(module_name, file_path), class_c)
  File "D:\Monai-datasets\MONAILabel\monailabel\utils\others\class_utils.py", line 25, in module_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Monai-datasets\MONAILabel\sample-apps\deepedit\main.py", line 27, in <module>
    from monailabel.scribbles.infer import HistogramBasedGraphCut
  File "D:\Monai-datasets\MONAILabel\monailabel\scribbles\infer.py", line 15, in <module>
    from monailabel.scribbles.transforms import (
  File "D:\Monai-datasets\MONAILabel\monailabel\scribbles\transforms.py", line 15, in <module>
    import denseCRF
ModuleNotFoundError: No module named 'denseCRF'

@masadcv

**Comment by masadcv** [comment]
Hi @ralkalay ,
Many thanks for putting detailed log for your error.

It seems like you are missing C++ compilation tools which are needed to compile code for SimpleCRF. More specifically, look at the following message from your log:
"error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/"

Can you please follow the link to cpp build tools (https://visualstudio.microsoft.com/visual-cpp-build-tools/), install them and retry?

(Not recommended, but a quick workaround) Alternatively, if you do not intend on using any scribbles related functionality from monai label, you can comment line 15 from the following message:
"File "D:\Monai-datasets\MONAILabel\monailabel\scribbles\transforms.py", line 15, in
import denseCRF"
