### ISSUE TITLE
Getting "500 Server Error: Internal Server Error" while running segmentation model in OHIF

### ISSUE THREAD

**Issue by kevinpatel13896** [Project-MONAI/MONAILabel#480]
Hello Project-MONAI Team,

I have built the OHIF viewer plugin and the Orthanc server by following [this link](https://github.com/Project-MONAI/MONAILabel/tree/main/plugins/ohif). The OHIF viewer is being connected with the MONAI Label as I can see the MONAI Label app and segmentation model name. But, When I am clicking on the segmentation model run button it is throwing an error. I am sharing the error trace below. 

```
[2021-10-31 10:01:23,347] [4803] [MainThread] [INFO] (dicomweb_client.api:2147) - retrieve series "1.3.46.670589.10.1.1.2163374719.1137684481.588647" of study "1.2.124.113532.192.70.134.138.20060119.151934.4823473"
[2021-10-31 10:01:23,352] [4803] [MainThread] [ERROR] (uvicorn.error:399) - Exception in ASGI application
Traceback (most recent call last):
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/fastapi/routing.py", line 214, in app
    raw_response = await run_endpoint_function(
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/kevinp/MONAILabel/monailabel/endpoints/infer.py", line 149, in run_inference
    result = instance.infer(request)
  File "/home/kevinp/MONAILabel/monailabel/interfaces/app.py", line 209, in infer
    request["image"] = datastore.get_image_uri(request["image"])
  File "/home/kevinp/MONAILabel/monailabel/datastore/dicom.py", line 64, in get_image_uri
    dicom_web_download_series(None, image_id, image_dir, self._client)
  File "/home/kevinp/MONAILabel/monailabel/datastore/utils/dicom.py", line 73, in dicom_web_download_series
    instances = client.retrieve_series(study_id, series_id)
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/dicomweb_client/api.py", line 2212, in retrieve_series
    self._get_series(
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/dicomweb_client/api.py", line 2161, in _get_series
    return self._http_get_multipart_application_dicom(
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/dicomweb_client/api.py", line 1054, in _http_get_multipart_application_dicom
    response = self._http_get(
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/dicomweb_client/api.py", line 616, in _http_get
    response.raise_for_status()
  File "/home/kevinp/MONAILabel/env/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8042/dicom-web//studies/1.2.124.113532.192.70.134.138.20060119.151934.4823473/series/1.3.46.670589.10.1.1.2163374719.1137684481.588647
```

I am not sure if this is from MONAI Label or OHIF viewer or Orthanc server but I guess it may be from the Orthanc server. 

Thank you in advance

**Comment by SachidanandAlle** [comment]
when you run the monailabel, please remove the trailing slash.. 
something like `--studies http://127.0.0.1:8042/dicom-web`

I think that's the reason why url access for `http://127.0.0.1:8042/dicom-web//studies/` is failing to fetch the series.  

Of-course the orthanc could have handled URIs better.. but that's not an excuse.  monailabel server can also take care while building the URIs for dicom web.  We can get that fixed soon on main branch.. or otherwise feel free to raise a PR (as it's open source for anyone to contribute back)

Possible something like this.. 

https://github.com/Project-MONAI/MONAILabel/blob/main/monailabel/interfaces/app.py#L118
`self.studies = self.studies.rstrip("/").strip()`

**Comment by kevinpatel13896** [comment]
Hello @SachidanandAlle 
Thanks for your reply.

I have checked the command which I am executing and it doesn't have a trailing slash but yes, in the URL it has two trailing slashes after the base URL. I dug into the source code and found that the [dicomweb_client](https://github.com/MGHComputationalPathology/dicomweb-client) is being used to [retriving series](https://github.com/Project-MONAI/MONAILabel/blob/main/monailabel/datastore/utils/dicom.py#L72) from the Orthanc server. The trailing slash is being added at the time of adding the [WADO URI](https://github.com/MGHComputationalPathology/dicomweb-client/blob/master/src/dicomweb_client/api.py#L409). The WADO URI Prefix is blank this is why there are two slashes.

Could you please take a look into this scenario? I think, there should be some WADO URI prefix and because of that the Otthanc is throwing error.

Thank you once again.

**Comment by SachidanandAlle** [comment]
> Hello @SachidanandAlle Thanks for your reply.
> 
> I have checked the command which I am executing and it doesn't have a trailing slash but yes, in the URL it has two trailing slashes after the base URL. I dug into the source code and found that the [dicomweb_client](https://github.com/MGHComputationalPathology/dicomweb-client) is being used to [retriving series](https://github.com/Project-MONAI/MONAILabel/blob/main/monailabel/datastore/utils/dicom.py#L72) from the Orthanc server. The trailing slash is being added at the time of adding the [WADO URI](https://github.com/MGHComputationalPathology/dicomweb-client/blob/master/src/dicomweb_client/api.py#L409). The WADO URI Prefix is blank this is why there are two slashes.
> 
> Could you please take a look into this scenario? I think, there should be some WADO URI prefix and because of that the Otthanc is throwing error.
> 
> Thank you once again.

can you please provide more details on the setup and command u are using..  little more details.. as you are still facing this issue..  because this is been verified by lot of other folks.. wondering what corner case went wrong and you are not able to use/connect to dicomweb...

also have you tried using other dicomweb clients to connect to your orthanc server? for example: 
https://dicomweb-client.readthedocs.io/en/latest/package.html#module-dicomweb_client.cli

**Comment by kevinpatel13896** [comment]
I'm using Ubuntu 20.04 with Python 3.8.10 version.

I took the latest pull yesterday itself and ran this command to start the MONAILabel server.

```
./monailabel/scripts/monailabel start_server -a sample-apps/segmentation_spleen/ -s http://127.0.0.1:8042/dicom-web
```

I following [this](https://github.com/Project-MONAI/MONAILabel/tree/main/plugins/ohif) tutorial to set up the OHIF viewer.

**Comment by SachidanandAlle** [comment]
The URL looks fine.. are you still not able to use OHIF viewer connected to your dicomweb..?
In that case, you can try some simple dicom list/fetch using the dicomweb client CLI.. if you are able to do so that.. u should be able to do the same in OHIF/MONAILabel

sometimes browser cache can be tricky.. you can try in private window.. to avoid any previous browser cache.. (i don't think this is an issue in your case)

**Comment by kevinpatel13896** [comment]
I am new to the [dicomweb_client](https://dicomweb-client.readthedocs.io/en/latest/package.html#module-dicomweb_client.cli) so please correct me if I am wrong.

```
dicomweb_client retrieve series --study 1.2.124.113532.192.70.134.138.20060119.151934.4823473 --series 1.3.46.670589.10.1.1.2163374719.1137684481.588647 full
```
I ran this command and got this response

```
2021-11-09 21:14:07 | ERROR    | dicomweb_client.cli                      | expected string or bytes-like object
```

**Comment by aihsani** [comment]
@kevinpatel13896 have you followed the script in the code box under: https://docs.monai.io/projects/label/en/latest/quickstart.html#ubuntu ... We found that there are compatibility issues if the `.so` files aren't updated independently.

**Comment by kevinpatel13896** [comment]
@aihsani After following the shared instructions, it's working fine now. However, I have followed the same steps earlier but unfortunately, it didn't work.

Thank you so much @aihsani @SachidanandAlle and the whole MONAILabel Team for the support.

**Comment by lambacini** [comment]
i think the problem is caused by prefix address parameters in dicomweb_client.
When i use a custom dicomweb server address, it adds two trailing spaces after the address. 
like this  http://127.0.0.1/dicomweb//series?Modality=CT

no trailing space at the end of the address when starting the server 
start command:  monailabel start_server --app apps/radiology --studies http://127.0.0.1/dicomweb --conf models all

in dicomweb_client _get_transaction_url function
"self.qido_url_prefix is not None" or "self.wado_url_prefix is not None" logic always returns True. 
it needs to be checked whether it is none or empty.

https://github.com/herrmannlab/dicomweb-client/blob/a9d6b09a347d41b245d0bf2054ec323fdc7ddb33/src/dicomweb_client/web.py#L318
