### ISSUE TITLE
Deepedit/DynUNetV1 not supporting MULTI GPU training

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#492]
```
[2021-11-04 07:58:18.666][ERROR](ignite.engine.engine.SupervisedTrainer) - Current run is terminating due to exception: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 1: 91 92 93 94 95 96 97 98
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
[2021-11-04 07:58:18.666][ERROR](ignite.engine.engine.SupervisedTrainer) - Engine run is terminating due to exception: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 1: 91 92 93 94 95 96 97 98
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/local/sachi/Projects/MONAILabel/monailabel/interfaces/utils/app.py", line 132, in <module>
    run_main()
  File "/local/sachi/Projects/MONAILabel/monailabel/interfaces/utils/app.py", line 117, in run_main
    result = a.train(request)
  File "/local/sachi/Projects/MONAILabel/monailabel/interfaces/app.py", line 346, in train
    result = task(request, self.datastore())
  File "/local/sachi/Projects/MONAILabel/monailabel/tasks/train/basic_train.py", line 317, in __call__
    torch.multiprocessing.spawn(main_worker, nprocs=world_size, args=(world_size, req, datastore, self))
  File "/local/sachi/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/local/sachi/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/local/sachi/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:
```

**Comment by nvahmadi** [comment]
Thanks Sachi. This is currently preventing multi-GPU usage with the DeepEdit default configuration.

**Comment by wyli** [comment]
Btw please upgrade to use the latest dynunet in the upcoming release, this dynunet v1 is deprecating https://github.com/Project-MONAI/MONAI/blob/6d2c1dce10895d8860898ec5271dbfbcb373c90c/monai/networks/nets/dynunet_v1.py#L27

**Comment by yiheng-wang-nv** [comment]
Hi @SachidanandAlle , there was a similar issue in https://github.com/Project-MONAI/MONAI/issues/1564
Can you please try DynUNet rather than the out-dated v1 version?

**Comment by SachidanandAlle** [comment]
Same issue.. with dynunet
```
[2021-11-05 02:42:07.260][ INFO](ignite.engine.engine.SupervisedTrainer) - Epoch: 1/20, Iter: 1/2 -- train_loss: 0.9693
[2021-11-05 02:42:14.748][ERROR](ignite.engine.engine.SupervisedTrainer) - Current run is terminating due to exception: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 35 36 37 38 39 40 41 42
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
[2021-11-05 02:42:14.748][ERROR](ignite.engine.engine.SupervisedTrainer) - Exception: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 35 36 37 38 39 40 41 42
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
Traceback (most recent call last):
  File "/local/sachi/.local/lib/python3.8/site-packages/ignite/engine/engine.py", line 834, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "/local/sachi/Projects/MONAILabel/monailabel/deepedit/interaction.py", line 111, in __call__
    return engine._iteration(engine, batchdata)
  File "/local/sachi/.local/lib/python3.8/site-packages/monai/engines/trainer.py", line 200, in _iteration
    _compute_pred_loss()
  File "/local/sachi/.local/lib/python3.8/site-packages/monai/engines/trainer.py", line 186, in _compute_pred_loss
    engine.state.output[Keys.PRED] = self.inferer(inputs, self.network, *args, **kwargs)
  File "/local/sachi/.local/lib/python3.8/site-packages/monai/inferers/inferer.py", line 95, in __call__
    return network(inputs, *args, **kwargs)
  File "/local/sachi/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/local/sachi/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 787, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 35 36 37 38 39 40 41 42
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error

```

**Comment by SachidanandAlle** [comment]
FYI.. 

```
pip list | grep monai
monai                   0.7.0               

```

**Comment by yiheng-wang-nv** [comment]
How did you use the `DistributedDataParallel` module? Did you set `find_unused_parameters=True`?
the dynunet tutorial also uses DDP for a part of decathlon tasks, please refer to: https://github.com/Project-MONAI/tutorials/blob/master/modules/dynunet_pipeline/train.py#L55

**Comment by SachidanandAlle** [comment]
`Note that traversing the autograd graph introduces extra overheads, so applications should only set find_unused_parameters to True when necessary.`

It solves the problem but only concern to enable this by default for DDP is.. training can become slow.  Need to evaluate the training speed with and without the flag.. Do you have any test results on that..?

**Comment by yiheng-wang-nv** [comment]
> `Note that traversing the autograd graph introduces extra overheads, so applications should only set find_unused_parameters to True when necessary.`
> 
> It solves the problem but only concern to enable this by default for DDP is.. training can become slow. Need to evaluate the training speed with and without the flag.. Do you have any test results on that..?

Hi @SachidanandAlle , thanks for the suggestions. With the updates in https://github.com/Project-MONAI/MONAI/pull/3427 , `find_unused_parameters` is not needed in DDP.
