### ISSUE TITLE
Training on during active learning is failing

### ISSUE THREAD

**Issue by j-sieger** [Project-MONAI/MONAILabel#637]
Facing below error while training the model as part of active learning.

Please help me to resolve this.

```
[2022-02-16 14:34:49.352][ INFO](ignite.engine.engine.SupervisedTrainer) - Epoch: 1/50, Iter: 1/2 -- train_loss: 0.0717
[2022-02-16 14:34:51.410][ERROR](ignite.engine.engine.SupervisedTrainer) - Current run is terminating due to exception: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 35 36 37 38 39 40 41 42
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
[2022-02-16 14:34:51.410][ERROR](ignite.engine.engine.SupervisedTrainer) - Exception: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 35 36 37 38 39 40 41 42
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 834, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monailabel/deepedit/interaction.py", line 111, in __call__
    return engine._iteration(engine, batchdata)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monai/engines/trainer.py", line 200, in _iteration
    _compute_pred_loss()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monai/engines/trainer.py", line 186, in _compute_pred_loss
    engine.state.output[Keys.PRED] = self.inferer(inputs, self.network, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monai/inferers/inferer.py", line 83, in __call__
    return network(inputs, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 873, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 35 36 37 38 39 40 41 42
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
[2022-02-16 14:34:51.411][ERROR](ignite.engine.engine.SupervisedTrainer) - Engine run is terminating due to exception: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 35 36 37 38 39 40 41 42
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
[2022-02-16 14:34:51.412][ERROR](ignite.engine.engine.SupervisedTrainer) - Exception: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 35 36 37 38 39 40 41 42
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 744, in _internal_run
    time_taken = self._run_once_on_dataset()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 848, in _run_once_on_dataset
    self._handle_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 467, in _handle_exception
    self._fire_event(Events.EXCEPTION_RAISED, e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 424, in _fire_event
    func(*first, *(event_args + others), **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monai/handlers/stats_handler.py", line 158, in exception_raised
    raise e
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 834, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monailabel/deepedit/interaction.py", line 111, in __call__
    return engine._iteration(engine, batchdata)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monai/engines/trainer.py", line 200, in _iteration
    _compute_pred_loss()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monai/engines/trainer.py", line 186, in _compute_pred_loss
    engine.state.output[Keys.PRED] = self.inferer(inputs, self.network, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monai/inferers/inferer.py", line 83, in __call__
    return network(inputs, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 873, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 35 36 37 38 39 40 41 42
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monailabel/interfaces/utils/app.py", line 132, in <module>
    run_main()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monailabel/interfaces/utils/app.py", line 117, in run_main
    result = a.train(request)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monailabel/interfaces/app.py", line 347, in train
    result = task(request, self.datastore())
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monailabel/tasks/train/basic_train.py", line 362, in __call__
    torch.multiprocessing.spawn(main_worker, nprocs=world_size, args=(world_size, req, datalist, self))
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monailabel/tasks/train/basic_train.py", line 574, in main_worker
    task.train(rank, world_size, request, datastore)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monailabel/tasks/train/basic_train.py", line 413, in train
    context.trainer.run()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monai/engines/trainer.py", line 56, in run
    super().run()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monai/engines/workflow.py", line 258, in run
    super().run(data=self.data_loader, max_epochs=self.state.max_epochs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 701, in run
    return self._internal_run()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 774, in _internal_run
    self._handle_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 467, in _handle_exception
    self._fire_event(Events.EXCEPTION_RAISED, e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 424, in _fire_event
    func(*first, *(event_args + others), **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monai/handlers/stats_handler.py", line 158, in exception_raised
    raise e
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 744, in _internal_run
    time_taken = self._run_once_on_dataset()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 848, in _run_once_on_dataset
    self._handle_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 467, in _handle_exception
    self._fire_event(Events.EXCEPTION_RAISED, e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 424, in _fire_event
    func(*first, *(event_args + others), **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monai/handlers/stats_handler.py", line 158, in exception_raised
    raise e
  File "/home/ec2-user/.local/lib/python3.9/site-packages/ignite/engine/engine.py", line 834, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monailabel/deepedit/interaction.py", line 111, in __call__
    return engine._iteration(engine, batchdata)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monai/engines/trainer.py", line 200, in _iteration
    _compute_pred_loss()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monai/engines/trainer.py", line 186, in _compute_pred_loss
    engine.state.output[Keys.PRED] = self.inferer(inputs, self.network, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/monai/inferers/inferer.py", line 83, in __call__
    return network(inputs, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 873, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 35 36 37 38 39 40 41 42
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
/opt/conda/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 3 leaked semaphore objects to clean up at shutdown
```

**Comment by SachidanandAlle** [comment]
Try with multi gpu disabled.. u can that by enabling developer option in slicer (edit -> application settings I guess -> monailabel)

And then u should see options drop list on the monailabel plugin.. against the training model u can enable or disable multi gpu

**Comment by j-sieger** [comment]
@SachidanandAlle : Thanks for the quick reply.
It works. But single GPU(22GB) is not sufficient. 
1. If i run the training and then fetch the next image for the labelling. Then inference will  `RuntimeError: CUDA out of memory`
2. If i first fetch the image and then run the training after labelling. then training is failing with `RuntimeError: CUDA out of memory` 

Either ways 22GB GPU memory is not sufficient. And i could not find any other instance with more the 22GB per instance. So i have chosen multiple GPU instance instance on AWS (4 GPUs , 22GB each). 

How much GB GPU is required ? or How can make training success on multi GPU instance ?

**Note:**I am using basic deepedit model for labelling `Task02_Heart` dataset

**Comment by SachidanandAlle** [comment]
This looks more of env issue for me.. otherwise I am training day-in day-out on multiple gpus.. so i asked to cross check if single gpu works for u..

it depends on the model/batch-size you are training.. try to reduce the batch size.. 
@diazandr3s can you help..

**Comment by SachidanandAlle** [comment]
Ok.. my bad.. based the exception.. i see you are using older version of monai or monai label.. you can update both of them to latest available.. that should solve the problem..

there was an issue in monai (core) related to this error..

`RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.`

**Comment by SachidanandAlle** [comment]
Or simple solution is..
https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/deepedit/main.py#L160

Set this flag `find_unused_parameters` to True

**Comment by SachidanandAlle** [comment]
If i run the training and then fetch the next image for the labelling. Then inference will RuntimeError: CUDA out of memory

This is basically training is running.. and CUDA memory is not available.. u can disable to run inference on Fetch Next (
Slicer => Edit => Application Settings => MONAI Label => Auto Run Pretrained Model => False

**Comment by diazandr3s** [comment]
> @SachidanandAlle : Thanks for the quick reply. It works. But single GPU(22GB) is not sufficient.
> 
>     1. If i run the training and then fetch the next image for the labelling. Then inference will  `RuntimeError: CUDA out of memory`
> 
>     2. If i first fetch the image and then run the training after labelling. then training is failing with `RuntimeError: CUDA out of memory`
> 
> 
> Either ways 22GB GPU memory is not sufficient. And i could not find any other instance with more the 22GB per instance. So i have chosen multiple GPU instance instance on AWS (4 GPUs , 22GB each).
> 
> How much GB GPU is required ? or How can make training success on multi GPU instance ?
> 
> **Note:**I am using basic deepedit model for labelling `Task02_Heart` dataset

Thanks for reporting this, @j-sieger.
As Sachi suggested, please install/use the latest MONAI Label. I even go further and suggest you use the weekly release: https://pypi.org/project/monailabel-weekly/

Please let us know how that goes.

**Comment by j-sieger** [comment]
@SachidanandAlle @diazandr3s . 
 I had `monai 0.8.0`  so i have updgraded to today's version `0.8.1`  and also installed `monaillabel weekly`. And now training is working on multiple GPUs. But i dont which one has helped resolved my issue. **any how thanks**.

I still have CUDA memory issue. I need to figure out which GPU based instance will work for me if i want to parallelly label and train the model in the backend.

**Comment by diazandr3s** [comment]
Glad to hear this!
