### ISSUE TITLE
Cannot start MONAILabel app on Windows due to missing openslide DLL

### ISSUE THREAD

**Issue by cpinter** [Project-MONAI/MONAILabel#683]
**Describe the bug**
Starting MONAILabel apps is not possible using the latest version on WIndows due to a missing openslide DLL.

**To Reproduce**
1. Create and activate MONAILabel environment in anaconda
2. Install prerequisites
3. Start MONAILabel server.

<details><summary>See command and output here</summary>

(monai_env) c:\d\_Extensions\_MONAI\MONAILabel>monailabel\scripts\monailabel start_server -a .\sample-apps\segmentation -s d:\_download\MONAIImages
Using PYTHONPATH=c:\d\_Extensions\_MONAI\MONAILabel;
[2022-03-10 11:41:58,367] [7240] [MainThread] [INFO] (__main__:293) - USING:: app = C:\d\_Extensions\_MONAI\MONAILabel\sample-apps\segmentation
[2022-03-10 11:41:58,367] [7240] [MainThread] [INFO] (__main__:293) - USING:: studies = D:\_download\MONAIImages
[2022-03-10 11:41:58,368] [7240] [MainThread] [INFO] (__main__:293) - USING:: verbose = INFO
[2022-03-10 11:41:58,369] [7240] [MainThread] [INFO] (__main__:293) - USING:: conf = None
[2022-03-10 11:41:58,369] [7240] [MainThread] [INFO] (__main__:293) - USING:: host = 0.0.0.0
[2022-03-10 11:41:58,370] [7240] [MainThread] [INFO] (__main__:293) - USING:: port = 8000
[2022-03-10 11:41:58,370] [7240] [MainThread] [INFO] (__main__:293) - USING:: uvicorn_app = monailabel.app:app
[2022-03-10 11:41:58,371] [7240] [MainThread] [INFO] (__main__:293) - USING:: ssl_keyfile = None
[2022-03-10 11:41:58,371] [7240] [MainThread] [INFO] (__main__:293) - USING:: ssl_certfile = None
[2022-03-10 11:41:58,372] [7240] [MainThread] [INFO] (__main__:293) - USING:: ssl_keyfile_password = None
[2022-03-10 11:41:58,372] [7240] [MainThread] [INFO] (__main__:293) - USING:: ssl_ca_certs = None
[2022-03-10 11:41:58,373] [7240] [MainThread] [INFO] (__main__:293) - USING:: workers = 1
[2022-03-10 11:41:58,373] [7240] [MainThread] [INFO] (__main__:293) - USING:: limit_concurrency = None
[2022-03-10 11:41:58,374] [7240] [MainThread] [INFO] (__main__:293) - USING:: access_log = False
[2022-03-10 11:41:58,374] [7240] [MainThread] [INFO] (__main__:293) - USING:: log_config = None
[2022-03-10 11:41:58,375] [7240] [MainThread] [INFO] (__main__:293) - USING:: dryrun = False
[2022-03-10 11:41:58,375] [7240] [MainThread] [INFO] (__main__:293) - USING:: action = start_server
[2022-03-10 11:41:58,375] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_API_STR =
[2022-03-10 11:41:58,376] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_PROJECT_NAME = MONAILabel
[2022-03-10 11:41:58,377] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_APP_DIR =
[2022-03-10 11:41:58,377] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_STUDIES =
[2022-03-10 11:41:58,379] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_APP_CONF = '{}'
[2022-03-10 11:41:58,379] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_USERNAME =
[2022-03-10 11:41:58,380] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_PASSWORD =
[2022-03-10 11:41:58,380] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CACHE_PATH =
[2022-03-10 11:41:58,380] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_QIDO_PREFIX =
[2022-03-10 11:41:58,381] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_WADO_PREFIX =
[2022-03-10 11:41:58,381] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_STOW_PREFIX =
[2022-03-10 11:41:58,381] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_FETCH_BY_FRAME = False
[2022-03-10 11:41:58,382] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_DATASTORE_AUTO_RELOAD = True
[2022-03-10 11:41:58,382] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_DATASTORE_FILE_EXT = '["*.nii.gz", "*.nii", "*.nrrd", "*.jpg", "*.png", "*.tif", "*.svs"]'
[2022-03-10 11:41:58,384] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_SERVER_PORT = 8000
[2022-03-10 11:41:58,385] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_CORS_ORIGINS = '[]'
[2022-03-10 11:41:58,385] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_SESSION_PATH =
[2022-03-10 11:41:58,386] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_SESSION_EXPIRY = 3600
[2022-03-10 11:41:58,386] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_INFER_CONCURRENCY = -1
[2022-03-10 11:41:58,387] [7240] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_INFER_TIMEOUT = 600
[2022-03-10 11:41:58,387] [7240] [MainThread] [INFO] (__main__:298) -
Traceback (most recent call last):
  File "C:\Users\pinte\anaconda3\envs\monai_env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\pinte\anaconda3\envs\monai_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\d\_Extensions\_MONAI\MONAILabel\monailabel\main.py", line 353, in <module>
    Main().run()
  File "c:\d\_Extensions\_MONAI\MONAILabel\monailabel\main.py", line 126, in run
    self.action_start_server(args)
  File "c:\d\_Extensions\_MONAI\MONAILabel\monailabel\main.py", line 251, in action_start_server
    uvicorn.run(
  File "C:\Users\pinte\anaconda3\envs\monai_env\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\pinte\anaconda3\envs\monai_env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\pinte\anaconda3\envs\monai_env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\pinte\anaconda3\envs\monai_env\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\pinte\anaconda3\envs\monai_env\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\Users\pinte\anaconda3\envs\monai_env\lib\site-packages\uvicorn\config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\pinte\anaconda3\envs\monai_env\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\pinte\anaconda3\envs\monai_env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\d\_Extensions\_MONAI\MONAILabel\monailabel\app.py", line 23, in <module>
    from monailabel.endpoints import (
  File "c:\d\_Extensions\_MONAI\MONAILabel\monailabel\endpoints\activelearning.py", line 18, in <module>
    from monailabel.interfaces.app import MONAILabelApp
  File "c:\d\_Extensions\_MONAI\MONAILabel\monailabel\interfaces\app.py", line 42, in <module>
    from monailabel.interfaces.utils.wsi import create_infer_wsi_tasks
  File "c:\d\_Extensions\_MONAI\MONAILabel\monailabel\interfaces\utils\wsi.py", line 16, in <module>
    import openslide
  File "C:\Users\pinte\anaconda3\envs\monai_env\lib\site-packages\openslide\__init__.py", line 35, in <module>
    from openslide import lowlevel
  File "C:\Users\pinte\anaconda3\envs\monai_env\lib\site-packages\openslide\lowlevel.py", line 43, in <module>
    _lib = cdll.LoadLibrary('libopenslide-0.dll')
  File "C:\Users\pinte\anaconda3\envs\monai_env\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\pinte\anaconda3\envs\monai_env\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'libopenslide-0.dll' (or one of its dependencies). Try using the full path with constructor syntax.

</details>

**Expected behavior**
Server starts without errors

**Environment**

<details><summary>See here</summary>

(monai_env) c:\d\_Extensions\_MONAI\MONAILabel>python -c "import monai; monai.config.print_debug_info()"
================================
Printing MONAI config...
================================
MONAI version: 0.8.1
Numpy version: 1.22.3
Pytorch version: 1.10.2+cpu
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 71ff399a3ea07aef667b23653620a290364095b1

Optional dependencies:
Pytorch Ignite version: 0.4.8
Nibabel version: 3.2.2
scikit-image version: 0.19.2
Pillow version: 9.0.1
Tensorboard version: 2.8.0
gdown version: 4.4.0
TorchVision version: 0.11.3+cpu
tqdm version: 4.63.0
lmdb version: 1.3.0
psutil version: 5.9.0
pandas version: NOT INSTALLED or UNKNOWN VERSION.
einops version: 0.3.2
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

================================
Printing system config...
================================
System: Windows
Win32 version: ('10', '10.0.19043', 'SP0', 'Multiprocessor Free')
Win32 edition: Professional
Platform: Windows-10-10.0.19043-SP0
Processor: Intel64 Family 6 Model 158 Stepping 12, GenuineIntel
Machine: AMD64
Python version: 3.8.12
Process name: python.exe
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: [popenfile(path='C:\\Windows\\System32\\en-US\\KernelBase.dll.mui', fd=-1), popenfile(path='C:\\Windows\\System32\\en-US\\kernel32.dll.mui', fd=-1)]
Num physical CPUs: 6
Num logical CPUs: 6
Num usable CPUs: 6
CPU usage (%): [14.2, 5.8, 4.8, 18.3, 9.6, 67.3]
CPU freq. (MHz): 3696
Load avg. in last 1, 5, 15 mins (%): [0.0, 0.0, 0.0]
Disk usage (%): 76.5
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 31.9
Available memory (GB): 16.9
Used memory (GB): 15.1

================================
Printing GPU config...
================================
Num GPUs: 0
Has CUDA: False
cuDNN enabled: False

</details>

**Additional context**
The revision 6ab09d6c261696a422c25d5b93dc9aba82026a82 reproduces this issue, but in be7db0c482ce1a8a9ad91a30b617c1e8a4fb8bb9 the server starts correctly, so this is a recent regression, probably related to the pathology feature.

**Comment by SachidanandAlle** [comment]
Correct.. openslide dependency is incomplete.. when you install openslide py package, they don't do a good job of installing the required dll/so files.. you have to install openslide (core) manually and keep the dll file also available in lib path.. 

Tried to suggest a better solution for them.. but no luck.. looks like the community is not able to understand the problem or they don't want to solve it for now..
https://github.com/openslide/openslide-python/pull/151

meanwhile will try to fix the error handling and see what other way we can install the openslide correctly

**Comment by cpinter** [comment]
I downloaded openslide and tried to copy the DLLs to places where I assumed they will be found. Any suggestions how to make the DLLs accessible on Windows?

**Comment by SachidanandAlle** [comment]
If you are not using pathology app.. u should be fine..

If you are using pathology app.. then edit the openslide py file and modify something like this..
https://github.com/openslide/openslide-python/pull/151

**Comment by diazandr3s** [comment]
> I downloaded openslide and tried to copy the DLLs to places where I assumed they will be found. Any suggestions how to make the DLLs accessible on Windows?

Thanks, @cpinter.
@SachidanandAlle fixed this. You should not have this issue now :)

**Comment by cpinter** [comment]
Excellent, thank you for the quick fix!!

**Comment by j-sieger** [comment]
@SachidanandAlle  @diazandr3s 

I am facing the same issue on Amazon linux2(EC2) while starting the MONAILalbel App. I need 'libopenslide.so.0' file. I am not able find `.so` file in my system path to add the path like you edited the `lowlevel.py` file.

Can you please help me here.

**Comment by SachidanandAlle** [comment]
Can you help to shout out loud on openslide github..

**Comment by diazandr3s** [comment]
> @SachidanandAlle @diazandr3s
> 
> I am facing the same issue on Amazon linux2(EC2) while starting the MONAILalbel App. I need 'libopenslide.so.0' file. I am not able find `.so` file in my system path to add the path like you edited the `lowlevel.py` file.
> 
> Can you please help me here.

Thanks for reporting this, @j-sieger 
Are you using the Pathology App? Which MONAI Label version are you using?

**Comment by j-sieger** [comment]
I am using pre release version i.e 0.4*

**Comment by SachidanandAlle** [comment]
Are you trying on Ubuntu/Linux? In that case you can try
`apt install openslide-tools`

**Comment by SachidanandAlle** [comment]
More easy way is use monailabel latest docker.. it has the dependency pre installed

**Comment by j-sieger** [comment]
@SachidanandAlle :
I am using Amazon linux machine. It won't support `apt`. It support `yum`. but yum does not have `openslide-tool` or `openslide` package

Let me try to install MONAILabel from docker.

**Comment by SachidanandAlle** [comment]
https://openslide.org/download/

> First, install [EPEL](https://fedoraproject.org/wiki/EPEL).
> yum install openslide
>

**Comment by j-sieger** [comment]
@SachidanandAlle  and @all

Please find the solution which worked for me on AMI. Sharing it, as it will be helpful for others.

1. to install EPEL
        `sudo amazon-linux-extras install epel`
2. Install openslide
        `sudo yum install openslide`

After this i tried starting monailabel server with pathology app. But i faced same issue.

Then followed below steps.
3.    `sudo yum install openslide-tools`
4.     `pip install openslide-python`

After 4th step i was able to start the monai label server with pathology application.

**Comment by diazandr3s** [comment]
For Windows users working with the Pathology app:

- Download openslide from here: https://openslide.org/download/

- Add the openslide/bin folder into windows PATH env. 

To add a path into the Windows PATH env please follow these instructions: https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

![add_path](https://user-images.githubusercontent.com/11991079/207303660-6129782b-5eee-49df-b3c1-e58dff9d5edf.png)

- restart the command prompt terminal
