### ISSUE TITLE
Inference of radiology sample app fails

### ISSUE THREAD

**Issue by bhoeckendorf** [Project-MONAI/MONAILabel#714]
**Describe the bug**
Inference fails when running radiology sample app using latest git of MONAI and MONAILabel through the Slicer plugin. From the traceback (below), it looks as if the issue is related with writing intermediate results through ITK.

**To Reproduce**
1. Install MONAI and MONAILabel latest git
2. Run radiology sample app with `-c models segmentation`
3. Train segmentation model for a few iterations via Slicer
4. Run inference using that model via Slicer

**Expected behavior**
Should show a (really bad, because essentially untrained) segmentation.

**Screenshots**
```
[2022-03-31 14:17:09,438] [165672] [MainThread] [INFO] (monailabel.interfaces.tasks.infer:252) - Infer Request (final): {'largest_cc': True, 'model': 'segmentation', 'image': '/research/sharedresources/cbi/common/burkhard/src/label/datasets/testdata/015.000.t2.img.IDESFT1303.2014-03-14.nii.gz', 'client_id': 'user-xyz', 'description': 'A pre-trained model for volumetric (3D) segmentation over 3D Images', 'device': 'cuda'}
[2022-03-31 14:17:09,441] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:62) - PRE - Run Transform(s)
[2022-03-31 14:17:09,504] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:63) - PRE - Input Keys: ['largest_cc', 'model', 'image', 'client_id', 'description', 'device', 'image_path']
[2022-03-31 14:17:11,334] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:99) - PRE - Transform (LoadImaged): Time: 1.7465; image: (384, 384, 57)(float32)
[2022-03-31 14:17:11,335] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:99) - PRE - Transform (AddChanneld): Time: 0.0000; image: (1, 384, 384, 57)(float32)
[2022-03-31 14:17:13,108] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:99) - PRE - Transform (Spacingd): Time: 1.7720; image: (1, 290, 290, 337)(float32)
[2022-03-31 14:17:13,270] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:99) - PRE - Transform (ScaleIntensityRanged): Time: 0.1613; image: (1, 290, 290, 337)(float32)
[2022-03-31 14:17:13,270] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:99) - PRE - Transform (EnsureTyped): Time: 0.0001; image: torch.Size([1, 290, 290, 337])(torch.float32)
[2022-03-31 14:17:13,272] [165672] [MainThread] [INFO] (monailabel.interfaces.tasks.infer:391) - Inferer:: SlidingWindowInferer => {'roi_size': (160, 160, 160), 'sw_batch_size': 1, 'overlap': 0.25, 'mode': <BlendMode.CONSTANT: 'constant'>, 'sigma_scale': 0.125, 'padding_mode': <PytorchPadMode.CONSTANT: 'constant'>, 'cval': 0.0, 'sw_device': None, 'device': None, 'progress': False}
[2022-03-31 14:17:13,273] [165672] [MainThread] [INFO] (monailabel.interfaces.tasks.infer:339) - Infer model path: /research/sharedresources/cbi/common/burkhard/src/label/apps/MONAILabel/sample-apps/radiology/model/segmentation.pt
[2022-03-31 14:17:17,913] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:62) - POST - Run Transform(s)
[2022-03-31 14:17:17,913] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:63) - POST - Input Keys: ['largest_cc', 'model', 'image', 'client_id', 'description', 'device', 'image_path', 'image_meta_dict', 'image_transforms', 'pred']
[2022-03-31 14:17:17,914] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:99) - POST - Transform (EnsureTyped): Time: 0.0001; image: torch.Size([1, 290, 290, 337])(torch.float32); pred: torch.Size([14, 290, 290, 337])(torch.float32)
[2022-03-31 14:17:17,920] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:99) - POST - Transform (Activationsd): Time: 0.0052; image: torch.Size([1, 290, 290, 337])(torch.float32); pred: torch.Size([14, 290, 290, 337])(torch.float32)
[2022-03-31 14:17:17,927] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:99) - POST - Transform (AsDiscreted): Time: 0.0062; image: torch.Size([1, 290, 290, 337])(torch.float32); pred: torch.Size([1, 290, 290, 337])(torch.float32)
[2022-03-31 14:17:23,860] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:99) - POST - Transform (KeepLargestConnectedComponentd): Time: 5.9335; image: torch.Size([1, 290, 290, 337])(torch.float32); pred: torch.Size([1, 290, 290, 337])(torch.float32)
[2022-03-31 14:17:23,987] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:99) - POST - Transform (ToNumpyd): Time: 0.1257; image: torch.Size([1, 290, 290, 337])(torch.float32); pred: (1, 290, 290, 337)(float32)
[2022-03-31 14:17:24,056] [165672] [MainThread] [INFO] (monailabel.interfaces.utils.transform:99) - POST - Transform (Restored): Time: 0.0690; image: torch.Size([1, 290, 290, 337])(torch.float32); pred: (384, 384, 57)(float32)
[2022-03-31 14:17:24,056] [165672] [MainThread] [INFO] (monailabel.interfaces.tasks.infer:427) - Writing Result...
[2022-03-31 14:17:24,058] [165672] [MainThread] [INFO] (monailabel.transform.writer:96) - Result ext: .nii.gz; write_to_file: True; dtype: None
[2022-03-31 14:17:24,149] [165672] [MainThread] [ERROR] (uvicorn.error:369) - Exception in ASGI application
Traceback (most recent call last):
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/fastapi/applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/monailabel/endpoints/infer.py", line 177, in api_run_inference
    return run_inference(background_tasks, model, image, session_id, params, file, label, output)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/monailabel/endpoints/infer.py", line 160, in run_inference
    result = instance.infer(request)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/monailabel/interfaces/app.py", line 255, in infer
    result_file_name, result_json = task(request)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/monailabel/interfaces/tasks/infer.py", line 278, in __call__
    result_file_name, result_json = self.writer(data)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/monailabel/interfaces/tasks/infer.py", line 434, in writer
    return writer(data)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/monailabel/transform/writer.py", line 114, in __call__
    write_itk(image_np, output_file, affine, dtype, compress)
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/monailabel/transform/writer.py", line 56, in write_itk
    result_image.SetDirection(itk.matrix_from_array(direction))
  File "/research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/itk/itkImagePython.py", line 7019, in SetDirection
    self.__SetDirection_orig__(direction)
TypeError: in method 'itkImageBase2___SetDirection_orig__', argument 2 of type 'itkMatrixD22 const &'
```

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
================================
Printing MONAI config...
================================
MONAI version: 0.8.1+184.gaf725d7
Numpy version: 1.22.3
Pytorch version: 1.11.0
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: af725d75c3d0e6ee41194851ee798f1a34bc4e45
MONAI __file__: /research/sharedresources/cbi/common/burkhard/var/conda/envs/label/lib/python3.9/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.8
Nibabel version: 3.2.2
scikit-image version: 0.19.2
Pillow version: 9.0.1
Tensorboard version: 2.8.0
gdown version: 4.4.0
TorchVision version: 0.12.0
tqdm version: 4.63.1
lmdb version: 1.3.0
psutil version: 5.9.0
pandas version: 1.4.1
einops version: 0.4.1
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 21.10
Platform: Linux-4.18.0-240.22.1.el8_3.x86_64-x86_64-with-glibc2.34
Processor: x86_64
Machine: x86_64
Python version: 3.9.12
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: [popenfile(path='/home/bhoecken/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-lock.bhoecken.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1', fd=99, position=0, mode='w', flags=32769)]
Num physical CPUs: 16
Num logical CPUs: 32
Num usable CPUs: 32
CPU usage (%): [0.9, 0.7, 0.5, 0.0, 0.2, 0.5, 0.2, 0.2, 0.0, 65.3, 2.3, 0.2, 2.8, 0.5, 0.7, 0.0, 0.9, 0.0, 0.2, 0.0, 0.5, 0.7, 0.9, 0.5, 0.0, 0.2, 0.2, 0.0, 0.5, 0.5, 0.0, 0.2]
CPU freq. (MHz): 1
Load avg. in last 1, 5, 15 mins (%): [0.4, 0.4, 0.5]
Disk usage (%): 69.1
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 251.3
Available memory (GB): 243.4
Used memory (GB): 5.2

================================
Printing GPU config...
================================
Num GPUs: 2
Has CUDA: True
CUDA version: 11.5
cuDNN enabled: True
cuDNN version: 8302
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
GPU 0 Name: NVIDIA GeForce RTX 2080 Ti
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 68
GPU 0 Total memory (GB): 10.8
GPU 0 CUDA capability (maj.min): 7.5
GPU 1 Name: NVIDIA GeForce GTX 1080
GPU 1 Is integrated: False
GPU 1 Is multi GPU board: False
GPU 1 Multi processor count: 20
GPU 1 Total memory (GB): 7.9
GPU 1 CUDA capability (maj.min): 6.1
```

**Additional context**
Thanks for any help

**Comment by SachidanandAlle** [comment]
looks some issue with the image/metadata.. `015.000.t2.img.IDESFT1303.2014-03-14.nii.gz`

have you tried some simple images.. and you see this basic issue? if not then, you might want to dig deeper into itk libraries which it's causing some issue.. what went wrong in direction.. or what is the attribute something not compatible..

**Comment by SachidanandAlle** [comment]
you can download some public datasets (MSD) using monailabel.. 
`monailabel datasets`

**Comment by bhoeckendorf** [comment]
You're right, it works well with the public dataset. I'm not exactly sure what or why, but the underlying problem indeed seems to be with the images' metadata. Thanks for the quick pointer.
