### ISSUE TITLE
Unsuccessful `pip install monailabel>=0.4.0rc2` on Windows platform with Python 3.10

### ISSUE THREAD

**Issue by jamesobutler** [Project-MONAI/MONAILabel#744]
**Describe the bug**
`monailabel` has a python requirement that is >= 3.7, but does it support Python 3.10? On PyPI it appears to use the below specification for what it shows on the webpage. PyTorch 1.11.0 provides Python 3.10 wheels [directly](https://download.pytorch.org/whl/torch_stable.html) and [on PyPI](https://pypi.org/project/torch/1.11.0/#files).
https://github.com/Project-MONAI/MONAILabel/blob/c9c84518aac9d5a6371610f0e9ab01e95296f40d/setup.cfg#L18-L19

On Windows I'm experiencing issues installing `monailabel==0.4.0rc2`:
```PS
PS C:\Users\JamesButler\AppData\Local\Programs\Python\Python310> ./Python.exe -m pip install monailabel==0.4.0rc2
Collecting monailabel==0.4.0rc2
  Downloading monailabel-0.4.0rc2-202204061125-py3-none-any.whl (5.1 MB)
     ---------------------------------------- 5.1/5.1 MB 13.1 MB/s eta 0:00:00
Collecting fastapi==0.73.0
  Using cached fastapi-0.73.0-py3-none-any.whl (52 kB)
Collecting watchdog==2.1.6
  Using cached watchdog-2.1.6-py3-none-win_amd64.whl (76 kB)
Collecting pydantic==1.9.0
  Downloading pydantic-1.9.0-cp310-cp310-win_amd64.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 33.5 MB/s eta 0:00:00
Collecting opencv-python-headless==4.5.5.64
  Using cached opencv_python_headless-4.5.5.64-cp36-abi3-win_amd64.whl (35.3 MB)
Collecting httpx==0.22.0
  Using cached httpx-0.22.0-py3-none-any.whl (84 kB)
Collecting python-dotenv==0.19.2
  Using cached python_dotenv-0.19.2-py2.py3-none-any.whl (17 kB)
Collecting filelock==3.4.2
  Using cached filelock-3.4.2-py3-none-any.whl (9.9 kB)
Collecting numpy>=1.21.5
  Downloading numpy-1.22.3-cp310-cp310-win_amd64.whl (14.7 MB)
     ---------------------------------------- 14.7/14.7 MB 25.2 MB/s eta 0:00:00
Collecting einops>=0.3.2
  Using cached einops-0.4.1-py3-none-any.whl (28 kB)
Collecting pynetdicom==2.0.1
  Using cached pynetdicom-2.0.1-py3-none-any.whl (1.6 MB)
Collecting Shapely==1.8.0
  Downloading Shapely-1.8.0.tar.gz (278 kB)
     ---------------------------------------- 278.3/278.3 KB 16.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\JamesButler\AppData\Local\Temp\pip-install-f_z4fi69\shapely_259fa21df06444599df38a4126b5f1d1\setup.py", line 74, in <module>
          from shapely._buildcfg import geos_version_string, geos_version, \
        File "C:\Users\JamesButler\AppData\Local\Temp\pip-install-f_z4fi69\shapely_259fa21df06444599df38a4126b5f1d1\shapely\_buildcfg.py", line 204, in <module>
          lgeos = CDLL("geos_c.dll")
        File "C:\Users\JamesButler\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
          self._handle = _dlopen(self._name, mode)
      FileNotFoundError: Could not find module 'geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
````

**Comment by SachidanandAlle** [comment]
have u tried latest version of shapely?
https://github.com/shapely/shapely/issues/1263#issuecomment-1042292592

**Comment by SachidanandAlle** [comment]
```
PS C:\Users\salle\AppData\Local\Programs\Python\Python310> .\python.exe -m pip install shapely
Collecting shapely
  Downloading Shapely-1.8.1.post1-cp310-cp310-win_amd64.whl (1.3 MB)
     ---------------------------------------- 1.3/1.3 MB 4.8 MB/s eta 0:00:00
Installing collected packages: shapely
Successfully installed shapely-1.8.1.post1
```

waiting for scribbles.. then we can push this change also as part of rc3 for monailabel

**Comment by SachidanandAlle** [comment]
I see there are more such dependency issues not yet ready for 3.10.. I see monai also doesn't yet support 3.10...
For example.. i can not install ` SimpleITK!=2.1.1.1` or opencv packages..

**Comment by SachidanandAlle** [comment]
its done by automation.. keep it reopened for tracking..
